### ISSUE TITLE
tls-crypt not supported

### ISSUE THREAD

**Issue by fkooman** [eduvpn/python-eduvpn-client#100]
![screenshot from 2018-05-08 10-13-18](https://user-images.githubusercontent.com/616885/39745780-93410d20-52a8-11e8-8f61-ce5979421992.png)

**Comment by fkooman** [comment]
modern deploys use `--tls-crypt` and no longer `--tls-auth`.

**Comment by fkooman** [comment]
See also https://github.com/eduvpn/documentation/blob/master/SECURITY.md

**Comment by fkooman** [comment]
You do now, see PM :)

**Comment by gijzelaerr** [comment]
ok thanks. vpn.tuxed.net seems down?

**Comment by fkooman** [comment]
Not from here.

**Comment by gijzelaerr** [comment]
can't reach it from here (while connected to eduVPN).

**Comment by gijzelaerr** [comment]
ok issue confirmed.

**Comment by gijzelaerr** [comment]
this has been fixed
