### ISSUE TITLE
add 2fa enroll flow

### ISSUE THREAD

**Issue by gijzelaerr** [eduvpn/python-eduvpn-client#103]
looks like the 2fa flow changed slightly since the last release or we missed this:

https://github.com/eduvpn/documentation/blob/master/API.md#two-factor-enrollment

related issue: https://github.com/eduvpn/python-eduvpn-client/issues/102

**Comment by gijzelaerr** [comment]
to trigger:
* add custom remote `debian-vpn.tuxed.net`
* log in using LDAP credentials
* see error, need to enroll first

**Comment by gijzelaerr** [comment]
i've made a start, but it is not really easy to develop and debug if I can't revoke the 2fa enrollment from my side.

**Comment by gijzelaerr** [comment]
1. start 2FA flow
2. generate a base32 secret key
3. generate a QR code, present to user with instructions
4. let user type ion authentication code
5. check if authentication code is correct (compare with current code `pytotp.now()`)
6. if codes match, enable 2fa remotely with the secret key and the latest code. If code doesn't match go to step 3

**Comment by fkooman** [comment]
> 5. check if authentication code is correct (compare with current code pytotp.now())
> 6. if codes match, enable 2fa remotely with the secret key and the latest code. If code doesn't match go to step 3

The API will also perform these steps, so you don't have to.

**Comment by fkooman** [comment]
https://github.com/eduvpn/documentation/commit/8ed6cdb2c68bb1c8cab3d9e986592d9da20a888d

**Comment by gijzelaerr** [comment]
should be implemented now https://github.com/eduvpn/python-eduvpn-client/commit/220b3455f0c8af33cf865caa17a84d06cf9c2475
