### ISSUE TITLE
comp-lzo should not (always) be on

### ISSUE THREAD

**Issue by fkooman** [eduvpn/python-eduvpn-client#107]
![image](https://user-images.githubusercontent.com/616885/40550514-957dc304-603a-11e8-9dce-720d157dba4b.png)

It is not part of the configuration at all. How did it get enabled and set to yes?

Note: some profiles do have `comp-lzo`, but newer ones not.
Note 2: this makes it impossible to transfer traffic over the VPN.

**Comment by gijzelaerr** [comment]
should be picked up from the config file: https://github.com/eduvpn/python-eduvpn-client/blob/master/eduvpn/openvpn.py#L91

it defaults to no. change to default yes?

**Comment by fkooman** [comment]
It's quite subtle:

```
       --comp-lzo [mode]
              DEPRECATED This option will  be  removed  in  a  future  OpenVPN
              release.  Use the newer --compress instead.

              Use  LZO  compression  --  may  add  up to 1 byte per packet for
              incompressible data.  mode may be  "yes",  "no",  or  "adaptive"
              (default).

              In  a server mode setup, it is possible to selectively turn com‐
              pression on or off for individual clients.

              First, make sure the client-side config file  enables  selective
              compression by having at least one --comp-lzo directive, such as
              --comp-lzo no.  This will turn off compression by  default,  but
              allow  a  future  directive  push from the server to dynamically
              change the on/off/adaptive setting.

              Next in a --client-config-dir file, specify the compression set‐
              ting for the client, for example:

                  comp-lzo yes
                  push "comp-lzo yes"

              The  first line sets the comp-lzo setting for the server side of
              the link, the second sets the client side.
```

If you read this correctly, it turns out there are 4 (FOUR!) different "configurations" of `--comp-lzo`.

* no `comp-lzo` at all (disables compression framing)
* `comp-lzo` or `comp-lzo adaptive`
* `comp-lzo yes`
* `comp-lzo no`

As it seems you are not using the import routine of OpenVPN configurations in NM (otherwise this would work by default), you have to parse this yourself and do the right thing in each case...

**Comment by gijzelaerr** [comment]
i think the values are taken over one on one from the config file, so the question is more what the default is right?

**Comment by fkooman** [comment]
there are two defaults here:

* no comp-lzo at all (disables compression framing)
* comp-lzo or comp-lzo adaptive

The important thing to understand here is that a *missing* `comp-lzo` is NOT the same as `comp-lzo no`.

**Comment by gijzelaerr** [comment]
ah right, i'll just remove the default, i expect that to have the wanted behavior.

**Comment by gijzelaerr** [comment]
should be fixed now

**Comment by fkooman** [comment]
when `comp-lzo` is in the config file it is not handled properly.

**Comment by gijzelaerr** [comment]
fixed per https://github.com/eduvpn/python-eduvpn-client/commit/791b2e36fae186d886e80918371ba1bd1f885883
