### ISSUE TITLE
messages tab is not updated when switching between providers

### ISSUE THREAD

**Issue by fkooman** [eduvpn/python-eduvpn-client#109]
when you configure multiple providers and switch between them, the messages tab is not updated with the message for that provider.

![image](https://user-images.githubusercontent.com/616885/40551681-f1dc1ad0-603d-11e8-8c6f-7b87a051a32e.png)

**Comment by gijzelaerr** [comment]
i can't replicate this issue, for me the messages are updated.

**Comment by fkooman** [comment]
can't reproduce anymore.
