### ISSUE TITLE
deleting one provider deletes multiple from list

### ISSUE THREAD

**Issue by fkooman** [eduvpn/python-eduvpn-client#112]
I had three providers and wanted to delete one. It actually deleted two!

**Comment by fkooman** [comment]
maybe the state they were in had something to do with this:
* frkovpn.tuxed.net was expired, so needed to reauthorize
* nl.eduvpn.org was broken because i revoked it which the client didn't "get"

**Comment by gijzelaerr** [comment]
i think this was a bug in updating configurations, where if the update failed the previous entry was deleted. I think this is solved now.
