### ISSUE TITLE
fix renew X.509 certificate

### ISSUE THREAD

**Issue by fkooman** [eduvpn/python-eduvpn-client#115]
the client should request a new x.509 client cert when the current one expired.

**Comment by fkooman** [comment]
@gijzelaerr can you imagine what will happen? Is this situation dealt with?

**Comment by fkooman** [comment]
You can use https://github.com/eduvpn/documentation/blob/master/API.md#check-certificate to query the server about this.

**Comment by gijzelaerr** [comment]
ah i was confused since you self assigned.

**Comment by fkooman** [comment]
use `/check_certificate` API call.

https://github.com/eduvpn/documentation/blob/master/API.md#check-certificate

**Comment by gijzelaerr** [comment]
so if expired/invalid use CA from openvpn config?  I think I always update the CA at  the moment.

**Comment by gijzelaerr** [comment]
but I check for a new config upon every connect... so what is the point of checking if it the ca is invalid?

**Comment by fkooman** [comment]
There is no point checking if the CA is valid, I am referring to the **client** certificate.

**Comment by gijzelaerr** [comment]
ah right, what is returned by `create_keypair`. 

I actually already check if it is expired:

https://github.com/eduvpn/python-eduvpn-client/blob/master/eduvpn/actions/activate.py#L59

but i'll add the remote check also.

**Comment by fkooman** [comment]
That checks the client certificate, or the OAuth token expiry?

**Comment by gijzelaerr** [comment]
ah yes, that is expire moment of token. not sure what i was thinkin. i will replace that with the certificate check.
