### ISSUE TITLE
2fa is "used" when connecting to profile that has no 2fa

### ISSUE THREAD

**Issue by fkooman** [eduvpn/python-eduvpn-client#118]
Observed:

1. add vpn.tuxed.net
2. choose e.g. "no TLS protection"
3. connect
4. see how the "totp" user is used in the right side of the app.

Expected:
only "2FA Internet Access" requires 2FA and only that one should have the "totp" (or "yubi") user set.

![image](https://user-images.githubusercontent.com/616885/41822511-fba12482-77f0-11e8-8dc4-a2d2d125f3e3.png)

**Comment by gijzelaerr** [comment]
this has been fixed in the reworked 2fa flow.
