### ISSUE TITLE
do not (re)authorize client when adding new profile of already known server

### ISSUE THREAD

**Issue by fkooman** [eduvpn/python-eduvpn-client#120]
Once you have an access_token of a particular server (institute access) you can reuse this when adding a new profile. No need to trigger the authorization again through the browser.

**Comment by fkooman** [comment]
Not sure, it'd be best to reuse tokens whenever possible yes. But wasn't this solved already by the updated flow?

**Comment by gijzelaerr** [comment]
token re-use based on hostname no. I base it now on the `instance_base_uri` (like u'https://demo.eduvpn.nl/'); if a configuration with the same `instance_base_uri` already exists that token is copied. I can take out the 'Institute Access' restriction, i guess it should work in all cases?

**Comment by fkooman** [comment]
- for secure internet (distributed) you can use a token at all mentioned instances;
- for institute access (local) you can only use a token at the issuing instance;

in both cases you need to renew the token at the original issueing oauth server, even though it is usable at other servers.

**Comment by gijzelaerr** [comment]
for distributed that was already implemented, but what about a custom URL instance?

**Comment by fkooman** [comment]
> but what about a custom URL instance?

treat it like "local".

**Comment by gijzelaerr** [comment]
ok then this should be working now.

**Comment by fkooman** [comment]
It does not for me... it will still open the browser. Using custom URL.

**Comment by gijzelaerr** [comment]
that should happen right? Get a token that way?

https://github.com/eduvpn/documentation/blob/master/API.md#local

"See API Discovery section above for determining the OAuth endpoints. The application MUST store the obtained access token and bind it to the instance the token was obtained from. If a user wants to use multiple VPN instances, a token MUST be obtained from all of them individually."

**Comment by fkooman** [comment]
profile !== instance

**Comment by fkooman** [comment]
https://github.com/eduvpn/documentation/blob/master/API.md#definitions

**Comment by gijzelaerr** [comment]
sorry, i don't get your comment.

**Comment by fkooman** [comment]
An instance, aka a server, is not the same as a profile. So, to add a new profile the user does not need to reauthorize.

**Comment by gijzelaerr** [comment]
should be working now.

**Comment by fkooman** [comment]
Check! :+1:
