### ISSUE TITLE
tls-auth or tls-crypt not required in config file

### ISSUE THREAD

**Issue by fkooman** [eduvpn/python-eduvpn-client#125]
https://github.com/eduvpn/python-eduvpn-client/blob/2384f6017988d802c8c0f093bceb53bfcede698a/eduvpn/openvpn.py#L127

it seems either tls-crypt or tls-auth MUST be present. This is not a valid assuption as we have profiles where neither is set.

**Comment by gijzelaerr** [comment]
hm? sorry, what do you mean. it now only prints a message stating that both are not present and it then continues. You want to change it to debug level?

**Comment by fkooman** [comment]
Ah :)
