### ISSUE TITLE
lets connect VPN integration

### ISSUE THREAD

**Issue by gijzelaerr** [eduvpn/python-eduvpn-client#134]
voor windows en android hebben we al een "let's connect" versie
 daar kan je eventueel inspiratie opdoen
logo's staan hier: https://github.com/letsconnectvpn/artwork

**Comment by gijzelaerr** [comment]
So basically this is just:
* Different icons
* no 'institute access' and 'internet access' only 'custom url'

right @fkooman ?

**Comment by fkooman** [comment]
Exactly. See the Windows and Android apps as examples, https://app.letsconnect-vpn.org/
