### ISSUE TITLE
connect-timeout setting not supported by old network-manager-openvpn

### ISSUE THREAD

**Issue by efef** [eduvpn/python-eduvpn-client#138]
since upgrade to 1.0rc14  the client can't connect anymore, before it was working.
After login and viewing the profile it is impossible to connect. I just immediately disconnects.
No usefull log info is available.

**Comment by efef** [comment]
tested under debian 9.4

**Comment by efef** [comment]
when clicking in the left on VPN profile I get this error in the terminal: type error: select () takes exactly 2 arguments (4 given)

**Comment by gijzelaerr** [comment]
ok this one slipped through, the connect-timeout setting is not supported on older network managers. Unfortunatly you can just set invalid setting, network manager will only complain during connecting.

affected versions (debian 9,5):
```
network-manager                  1.6.2-3
network-manager-gnome            1.4.4-1
network-manager-openvpn(-gnome)  1.2.8-2
```

working (ubuntu 18.04):
```
network-manager                    1.10.6-2ubuntu12
network-manager-gnome              1.8.10-2ubuntu1
network-manager-openvpn(-gnome)    1.8.2-1
```

**Comment by gijzelaerr** [comment]
I can detect what the NetworkManager version is. Just like Ubuntu, CentOS has network-manager 1.10.x but also doesn't support `connect-timeout` (!).

**Comment by gijzelaerr** [comment]
the `connect-timeout` seems to be only supported by `network-manager-openvpn 1.8.10`. Maybe older versions also support this, but at least 1.2.8  deosnt have support. I can query the NetworkManager version, but I can't reliably figure out what the VPN plugin version is. I think the only thing for now is that I can't enable this feature, which means the default will be used (timeout of 60 seconds).

**Comment by gijzelaerr** [comment]
For now we disable the timeout setting, since we can't reliably figure out what the version of `network-manager-openvpn` is
