### ISSUE TITLE
debian tls-crypt config parse bug

### ISSUE THREAD

**Issue by efef** [eduvpn/python-eduvpn-client#157]
it seems the tls-crypt config isn't parsed correctly. I've tested with debian 9.5.
When viewing network-manager settings - advanced. The TLS-crypt configuration is missing.
![image](https://user-images.githubusercontent.com/3393474/45027290-4910ca00-b041-11e8-9036-165e67afac39.png)

**Comment by efef** [comment]
when using an ubuntu client, the tls-crypt settings are correctly shown:
![image](https://user-images.githubusercontent.com/3393474/45027360-75c4e180-b041-11e8-8711-3048d2a11fc5.png)

**Comment by gijzelaerr** [comment]
journalctl -u NetworkManager shows: "property tls-crypt invalid or not supported" when enabling the configuration. We set this property but this version of network manager doesn't support it.

**Comment by gijzelaerr** [comment]
it looks like the network manager bundled with Debian doesn't support tls-crypt (although openvpn does since 2.4?). I guess this has been recently been enabled for the server you are testing with?

**Comment by gijzelaerr** [comment]
a manual import of a ovpn config file also fails on the tsl-crypt part. tls-crypt is unsupported on Debian 9.

**Comment by gijzelaerr** [comment]
this works for:
```
network-manager 1.10.6-2ubuntu1
network-manager-openvpn 1.8.2-1
```

but not for:
```
network-manager 1.6.2
network-manager-openvpn 1.2.8
```

**Comment by fkooman** [comment]
it only works in network-manager-openvpn >= 1.2.10.

**Comment by fkooman** [comment]
Maybe we can ask the package maintainer to create a backport for Debian 9? That would help a lot.

**Comment by fkooman** [comment]
https://github.com/eduvpn/documentation/blob/master/PROFILE_CONFIG.md#linux

this seems to be the most up to date info i could gather...

**Comment by gijzelaerr** [comment]
reported at Debian, lets see what happens https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=910511

**Comment by gijzelaerr** [comment]
I've been thinking about this, but i'm not really in favour of adding a warning popup to the client, since it might harm the user experience. I've updated the documentation manual with a section about supported platforms, basically a copy of @fkooman his table. I think it is probably just better to warn people on the install page and if they decide to continue they are on their own?

**Comment by fkooman** [comment]
I actually think that backports is good enough. You can mention that in the installation instructions as well, once available I'll also update my Debian 9 instructions. There's nothing else we can do, except drop `tls-crypt` at the server side...

**Comment by fkooman** [comment]
This is / was also an issue with CentOS 7. There is an update that hopefully within 2 weeks will be in "stable" EPEL that from then on supports `tls-crypt`, just like Fedora: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2018-8d5937661c

On CentOS you can install this (for now) by running:
```
$ sudo yum update --enablerepo=epel-testing NetworkManager-openvpn-gnome NetworkManager-openvpn
```

**Comment by gijzelaerr** [comment]
for debian, network-manager `1.12.4`  has been uploaded to backports, network-manage-openvpn will follow soon.

To enable backports you need to have this line in `/etc/apt/sources.list`:
```
deb http://ftp.debian.org/debian stretch-backports main
```
Once it is there run as root:

```
apt-get update
apt-get -t stretch-backports install network-manager network-manager-openvpn
```

**Comment by gijzelaerr** [comment]
```
network-manager-openvpn_1.8.6-2~bpo9+1_amd64.changes ACCEPTED into stretch-backports
```
And I just verified, after installing the updated network manager packages from backports the client connects successfully.

**Comment by fkooman** [comment]
Awesome!!! :man_dancing:

**Comment by fkooman** [comment]
When I follow the instructions here: https://backports.debian.org/Instructions/ it seems to update a bunch of packages when I upgrade `network-manager-openvpn`, is this expected?

```
fkooman@frkodeb:~$ sudo apt-get -t stretch-backports upgrade network-manager-openvpn
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  iputils-arping libnm-glib-vpn1
Use 'sudo apt autoremove' to remove them.
The following packages have been kept back:
  aptly bind9-host debhelper devscripts dirmngr e2fslibs e2fsprogs exim4-base exim4-daemon-light gir1.2-javascriptcoregtk-4.0 gir1.2-lokdocview-0.1
  gir1.2-webkit2-4.0 gnome-orca gnupg gnupg-agent libcomerr2 libdrm-amdgpu1 libdrm2 libegl1-mesa libgbm1 libgl1-mesa-dri libgl1-mesa-glx
  libglapi-mesa libgles2-mesa libgpgme11 libjavascriptcoregtk-4.0-18 liblibreofficekitgtk libreoffice libreoffice-avmedia-backend-gstreamer
  libreoffice-base libreoffice-base-core libreoffice-base-drivers libreoffice-calc libreoffice-common libreoffice-core libreoffice-draw
  libreoffice-evolution libreoffice-gnome libreoffice-gtk3 libreoffice-help-en-us libreoffice-impress libreoffice-java-common libreoffice-math
  libreoffice-ogltrans libreoffice-pdfimport libreoffice-report-builder libreoffice-report-builder-bin libreoffice-script-provider-bsh
  libreoffice-script-provider-js libreoffice-script-provider-python libreoffice-sdbc-hsqldb libreoffice-sdbc-postgresql libreoffice-style-tango
  libreoffice-writer libreofficekit-data libss2 libwayland-egl1-mesa libwebkit2gtk-4.0-37 libxatracker2 lintian linux-image-amd64 mesa-va-drivers
  mesa-vdpau-drivers python-gpg python3-uno systemd-sysv uno-libs3 ure
The following packages will be upgraded:
  ant ant-optional at-spi2-core dh-autoreconf dh-python distro-info-data exim4-config fonts-opensymbol geoip-database gir1.2-atk-1.0 gir1.2-atspi-2.0
  git git-man gpgv iproute2 iptables libassuan0 libatk-adaptor libatk-bridge2.0-0 libatk1.0-0 libatk1.0-data libatspi2.0-0 libbrlapi0.6 libdrm-intel1
  libdrm-nouveau2 libdrm-radeon1 libfastjson4 libgpg-error0 libidn2-0 libimobiledevice6 libip4tc0 libip6tc0 libiptc0 libjs-jquery-tablesorter
  libldap-2.4-2 libldap-common liblognorm5 libnm0 libnma0 libnss-myhostname libpam-systemd libreoffice-librelogo libreoffice-nlpsolver
  libreoffice-wiki-publisher libservlet3.1-java libssh-gcrypt-4 libsystemd0 libtalloc2 libudev1 libwayland-client0 libwayland-cursor0
  libwayland-server0 libxapian30 libxtables12 linux-libc-dev manpages manpages-dev network-manager network-manager-gnome network-manager-openvpn
  network-manager-openvpn-gnome openvpn python-idna python-lxml python-talloc python3-brlapi python3-pyatspi rsyslog systemd udev xbrlapi
71 upgraded, 0 newly installed, 0 to remove and 68 not upgraded.
Need to get 36.5 MB of archives.
After this operation, 13.7 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
```

Are those all dependencies of the new `network-manager-openvpn`?

**Comment by gijzelaerr** [comment]
try:
```
apt-get -t stretch-backports install network-manager network-manager-openvpn network-manager-openvpn-gnome
```
I guess `upgrade` upgrades all packages from backports.

**Comment by fkooman** [comment]
That seems to work better! Thanks! :)

**Comment by fkooman** [comment]
Documented it [here](https://github.com/eduvpn/documentation/blob/master/CLIENT_COMPAT.md#linux-1) as well.

**Comment by gijzelaerr** [comment]
i've updated the installation instructions also, I think we can just close this issue now.

https://python-eduvpn-client.readthedocs.io/en/master/introduction.html#installation
