### ISSUE TITLE
when obtaining new token for 1 profile for one server, other profiles should not ask again

### ISSUE THREAD

**Issue by fkooman** [eduvpn/python-eduvpn-client#159]
vpn.tuxed.net has 4 profiles. When the refresh token expires, the client wants to obtain a new access token for all of the profiles, so 4 times. It should only be needed one time. Access tokens need to be bound to the server, not to the profile.

**Comment by fkooman** [comment]
* Ubuntu 18.04 LTS
* eduVPN Linux client version 0.0dev
* pip3 install --user --upgrade git+https://github.com/eduvpn/python-eduvpn-client.git

**Comment by gijzelaerr** [comment]
this is sort of related to https://github.com/eduvpn/python-eduvpn-client/issues/151 since we don't keep track of shared resources.

**Comment by gijzelaerr** [comment]
This is going to be addressed in the new 2.0 workflow
