### ISSUE TITLE
Broken callback?

### ISSUE THREAD

**Issue by leenaars** [eduvpn/python-eduvpn-client#161]
There is a new two step process. The first callback to the local server works as before, but after selecting "Internet Access" instead of TFA the next (second) callback to the server ends up nowhere.

http://127.0.0.1:37347/callback?code=mNxE8owfbye.....

Which results in "Unable to connect: Firefox can’t establish a connection to the server at ... "

# Installation
Through Debian Stretch repository, as indicated.

# Version
Latest. 
eduVPN Linux client version 0.0dev

# OS/Distribution

What operating system/distribution and version you are running?

# Logs

Are there any interesting logs appearing when you try to connect?

have a look at `$ sudo journalctl -u NetworkManager`

**Comment by gijzelaerr** [comment]
@leenaars thanks for your report. Interesting. I'm not aware of a second callback, are you sure you think a second call back is happening?

Also i'm not sure what verison you are using, you say from the debian stretch repository, but also 'latest' with version 0.0dev? 0.0dev probably means you did a pip install?

**Comment by leenaars** [comment]
No, I did install on Stretch from the Stretch repo.

dpkg -s eduvpn-client says:

Package: eduvpn-client
Status: install ok installed
Priority: optional
Section: python
Installed-Size: 21
Maintainer: Gijs Molenaar (launchpad ppa build key) <gijs@pythonic.nl>
Architecture: all
Source: python-eduvpn-client
Version: 1.0.1-2
Depends: python:any (>= 2.6~), python-eduvpn-client, network-manager, network-manager-openvpn, network-manager-openvpn-gnome, openvpn
Conflicts: lets-connect-client
Description: VPN client for educational networks
 EduVPN enables students, employees and researchers to connect securely and
 encrypted to the Internet from any standard device. EduVPN integrates with
 the institutional network so that internal ICT services can be made available
 in a secure manner.
Homepage: https://github.com/gijzelaerr/python-eduvpn-client

What I mean with 'second callback': 

First you are prompted to choose a profile and then select an organisation, for instance the demo server instance. The client then sends you to the browser, to confirm with e.g. Onegini.me. The result is sent back to a localhost endpoint. At that point, you are told "bye" and that you can close the browser. Now a follow up menu makes you choose between "Internet Access" and "2FA". When you choose Internet Access, another call to the browser is made. This time, however, the browser does not finally meet with a confirmation. It somehow does not connect to the localhost end point it is sent to...

**Comment by gijzelaerr** [comment]
This is very weird, and I don't understand what could trigger that behaviour. I will investigate asap.

**Comment by gijzelaerr** [comment]
I can't replicate the issue.

* Do you have other profiles created?
* What browser are you using?
* What authenticator are you using (onegini.me)?

**Comment by gijzelaerr** [comment]
@leenaars is this still an issue?

**Comment by gijzelaerr** [comment]
closing this issue since no response from the reporter and unable to replicate the issue.

**Comment by leenaars** [comment]
@gijzelaerr: Meanwhile some clarity. What I thought was a second callback to localhost, was actually the window of the first callback ("Opening your default browser now") that pops back up from below the (new) option screen between internet connection and totp when that window is closed again. Opening the first callback twice obviously ends in predictable failure...
What is not clear to me, is why registering a demo account does not result in an active, working connection. I'll send you the logs.

**Comment by gijzelaerr** [comment]
In case of stretch you might be encountering this issue: https://github.com/eduvpn/python-eduvpn-client/issues/157

which you can solve by installing network-manager packages from backports (documented in issue, will update installation docs soon).

**Comment by leenaars** [comment]
Fairly sure, but I cannot prove it. I'm running into a TOTP issue that prevents me from creating a new test account.

**Comment by leenaars** [comment]
Reproduced (a few times to be sure). The screen indeed disappears when the browser is redirected, but it *reappears* when the session dialogue is closed.

**Comment by gijzelaerr** [comment]
what session dialog?
