### ISSUE TITLE
Create red hat 8 rpm

### ISSUE THREAD

**Issue by gijzelaerr** [eduvpn/python-eduvpn-client#171]

**Comment by gijzelaerr** [comment]
Although it is impossible for me to make a red hat 8 RPM, we are close to having a centos 8 RPM.

**Comment by gijzelaerr** [comment]
uploaded the centos8 packages to copr, but can't complete since some dependencies are missing https://github.com/eduvpn/python-eduvpn-client/issues/202

**Comment by amarsman** [comment]
Now that the dependencies are no longer needed this can be finished?

**Comment by gijzelaerr** [comment]
we can close this issue when a red hat 8 rpm lives on copr :)

**Comment by amarsman** [comment]
Do we have listed somewhere what the definition of done is for the different distributions? I wasn't aware that it needed to build without network access, which makes sense now I think of it.

**Comment by gijzelaerr** [comment]
I've set up a release procedure checklist:

https://python-eduvpn-client.readthedocs.io/en/master/developer.html#how-to-make-a-release

which sort of is what you ask for.

**Comment by amarsman** [comment]
Yes, looks good. 

I'm trying to update CHANGES.md at a commit if useful to be able to see what the current state is.

**Comment by gijzelaerr** [comment]
I guess now we have an rpm for EPEL 8, Red hat 8 is also supported?

https://copr.fedorainfracloud.org/coprs/gijzelaerr/eduvpn-client/build/1343899/
