### ISSUE TITLE
Enable travis integration

### ISSUE THREAD

**Issue by gijzelaerr** [eduvpn/python-eduvpn-client#179]
Somehow the travis integration for github has been switched off. Travis builds still get triggered, but the pull request links don't work anymore. I can't change anything from my side.

 @mkoelewijn @efef ?

**Comment by fkooman** [comment]
> but the pull request links don't work anymore

what does that mean?

**Comment by gijzelaerr** [comment]
for example https://github.com/casacore/python-casacore/pull/170

travis integrates nicely with GitHub by having links and notifications to the travis builds.

**Comment by fkooman** [comment]
Ah! So travis needs "write" access to the repository issues/PRs to be able to add this information I guess?

**Comment by fkooman** [comment]
Now hopefully this can be organizd _per repository_ and not for the whole organization...

**Comment by gijzelaerr** [comment]
this issue seems to be resolved.
