### ISSUE TITLE
kill switch

### ISSUE THREAD

**Issue by efef** [eduvpn/python-eduvpn-client#187]
design kill-switch to avoid leaking when eduVPN is down

**Comment by efef** [comment]
maybe do something like: https://github.com/ProtonVPN/protonvpn-cli-ng/blob/master/USAGE.md#kill-switch

**Comment by gijzelaerr** [comment]
I would say this is a 'nice to have', and should not block the 2.0 release.

**Comment by jwijenbergh** [comment]
It is nice to have but I see lots of problems with this

- We need root privileges in order to modify iptables/nftables rules
  - Could implement a popup with password, but this is not ideal
- When to reset these rules?
  - Will they be removed when the application is removed?

**Comment by gijzelaerr** [comment]
ok agreed, lets postpone this to a future release, then we decide if we drop the plan or not.

**Comment by jwijenbergh** [comment]
Maybe we can document the steps that an user should take to enable a killswitch manually

**Comment by jwijenbergh** [comment]
We should document how to do this but not implement it in core IMO

**Comment by jwijenbergh** [comment]
This repository was moved to Codeberg: https://codeberg.org/eduVPN/linux-app/issues/187
