### ISSUE TITLE
Missing packages for CentOS 8

### ISSUE THREAD

**Issue by gijzelaerr** [eduvpn/python-eduvpn-client#202]
Centos 8 contains most python3 packages for eduVPN, except:

* `python3-configparser`
* `python3-mock`
* `python3-repoze-lru`

Python2 support is minimal, so that is a dead-end anyway.

**Comment by gijzelaerr** [comment]
@fkooman what did we do last time to get packages into centos again? These packages are not really special nor extraordinary and should probably be easy to get accepted upstream.

**Comment by fkooman** [comment]
You can check out EPEL-8 if they are there. The way to get packages in CentOS is to get them in Fedora first. But for now I think a COPR repository would be good enough...

**Comment by fkooman** [comment]
https://copr.fedorainfracloud.org/coprs/gijzelaerr/eduvpn-client/monitor/

**Comment by gijzelaerr** [comment]
These are already in fedora.

**Comment by fkooman** [comment]
> These are already in fedora.

What do you mean by this?

**Comment by gijzelaerr** [comment]
all 3 listed packages are already in fedora31.

**Comment by fkooman** [comment]
Right, however:

* `python3-configparser`
* `python3-mock`

are part of the standard library of Python 3 so they can be used directly without needing a "polyfill" dependency. As for `python3-repoze-lru` that is a tiny dependency that hasn't seen any development in the last 2 to 3 years. So either it can be added to the source, or better be replaced by something locally (if really needed)...

**Comment by gijzelaerr** [comment]
dropping py2 support will indirectly solve this issue.

**Comment by amarsman** [comment]
We can close this issue now as we don't need the previously missing packages anymore?

**Comment by fkooman** [comment]
Yes! And I tested it! It works on CentOS 8!

**Comment by gijzelaerr** [comment]
did you test the packaging without an internet connection? If I remember correctly, setup.py will automatically download unfulfilled requirements if they are not found on the system. Which means the package will successfully build on a system with an internet connection but not on copr.

**Comment by gijzelaerr** [comment]
made a new issue for that https://github.com/eduvpn/python-eduvpn-client/issues/220
