### ISSUE TITLE
tests failure in headless Linux build environment

### ISSUE THREAD

**Issue by guillomovitch** [eduvpn/python-eduvpn-client#208]
Running tests seems to requires a a working D-Bus service, as some tests fails on a non-interactive headless build environment, as used by all Linux distributions:

```
======================================================================
ERROR: test_vpn_change (tests.test_actions.TestActions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/guillaume/eduvpn-client/BUILD/eduvpn_client-1.0.3/tests/test_actions.py", line 45, in test_vpn_change
    vpn_change(builder=self.builder, lets_connect=False)
  File "/home/guillaume/eduvpn-client/BUILD/eduvpn_client-1.0.3/eduvpn/actions/vpn_status.py", line 64, in vpn_change
    notify(notification, u"eduVPN Disconnected", u"Disconnected from '{}'".format(meta.display_name))
  File "/home/guillaume/eduvpn-client/BUILD/eduvpn_client-1.0.3/eduvpn/notify.py", line 33, in notify
    notification.show()
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files (2)
```
The exact list of failing tests is:

- test_vpn_change (tests.test_actions.TestActions)
- test_switched_off (tests.actions.test_switch.TestActions)
- test_switched_on (tests.actions.test_switch.TestActions)
- test_activate_connection (tests.actions.test_activate.TestActions)
- test_notify (tests.test_notify.TestNotify)
- test_insert_config (tests.test_manager.TestNm)
- test_store_provider (tests.test_manager.TestNm)

I fixed the issue by removing the corresponding test files before running the tests. However, either having those tests automatically disabling themselves when no suitable service is found, or running a test-dedicated private dbus service would probably be a better solution.

Also, those tests works OK when running them manually in a normal user environment, but they also mess with my own user settings by introducing dummy VPN profiles, which is another motivation to isolate them better from background environment.

**Comment by gijzelaerr** [comment]
hey! Yes, all true. all solutions have advantages and disadvantages, but maybe what you propose is cleaner.

Yes, the tests create dummy profiles. Maybe we should clean them up.

All nice to have, but for my development process not required. If you want to improve them, please do so! Thanks!

**Comment by guillomovitch** [comment]
I just created a PR implementing the first strategy (automatic test disabling if notification service isn't available).

I also had a look at dbus-run-session (https://dbus.freedesktop.org/doc/dbus-run-session.1.html), which seems the perfect tool for running tests, however I couldn't find how to have the python tests run in a child environment, excepted manually invocating them as "dbus-run-session -- python3 setup.py test". Also, this new bus doesn't seem to inheritate from current session bus, and apparently need to be manually populated with a notification service.

**Comment by gijzelaerr** [comment]
interesting, dbus-run-session is new to me. Could be an interesting path forward. Most important is that the Docker containers somehow run properly, that would make it easier to test and verify all the supported platforms.

Great work.

**Comment by gijzelaerr** [comment]
We are moving away in 2.0 from d-bus and just use nmlib, and we are mocking this away in the test suite, eliminating the requirement on external services during testing. Thanks for reporting!
