### ISSUE TITLE
use stdlib instead of python3-configparser dependency

### ISSUE THREAD

**Issue by fkooman** [eduvpn/python-eduvpn-client#210]
https://docs.python.org/3.7/library/configparser.html

related #202

**Comment by gijzelaerr** [comment]
If we drop py2 support we can drop this dependency also.

**Comment by gijzelaerr** [comment]
i expect just removing this dependency from the packaging files (spec etc) should be enough

**Comment by gijzelaerr** [comment]
done! Thanks @amarsman
