### ISSUE TITLE
use stdlib instead of python3-mock dependency

### ISSUE THREAD

**Issue by fkooman** [eduvpn/python-eduvpn-client#211]
https://docs.python.org/3.7/library/unittest.mock.html

related #202

**Comment by gijzelaerr** [comment]
If we drop py2 support we can drop this dependency.

**Comment by gijzelaerr** [comment]
same here, just dropping the dependency in the spec file is required, but additionally, the tests need to be modified to use the right module (module has different location in stdlib).

**Comment by gijzelaerr** [comment]
done! Thanks @amarsman
