### ISSUE TITLE
use stdlib instead of python3-repoze-lru

### ISSUE THREAD

**Issue by fkooman** [eduvpn/python-eduvpn-client#212]
it is not (yet) there

related #202

**Comment by gijzelaerr** [comment]
If we drop py2 support we can drop this dependency also.

**Comment by fkooman** [comment]
Ah, what would be used in Python 3 instead?

**Comment by gijzelaerr** [comment]
https://docs.python.org/3/library/functools.html#functools.lru_cache

**Comment by gijzelaerr** [comment]
done!
