### ISSUE TITLE
Do not show VPN entries already in NetworkManager

### ISSUE THREAD

**Issue by fkooman** [eduvpn/python-eduvpn-client#213]
The eduVPN UI shows the already existing VPN configuration in NetworkManager. Is it possible to only show the ones that were added by the eduVPN client itself?

**Comment by gijzelaerr** [comment]
This is probably possible, but if we are going to change this, maybe a good moment to take a step back and rethink the whole VPN NM profile management. I was discussing a redesign met Rogier, there are multiple scenarios possible. We could also choose to have only one eduVPN configuration in NetworkManager which is managed by eduVPN.

**Comment by gijzelaerr** [comment]
This is going to be adressed in the 2.0 release, since we will have only one eduVPN Network Manager profile.
