### ISSUE TITLE
Merge all RPM spec files into one

### ISSUE THREAD

**Issue by fkooman** [eduvpn/python-eduvpn-client#221]
There's no need to have separate ones for CentOS 8 / Fedora and Let's Connect! / eduVPN. Both eduVPN and Let's Connect! could be subpackages.

**Comment by fkooman** [comment]
For CentOS 7 there was a reason to have a separate package...

**Comment by gijzelaerr** [comment]
i guess it can be difficult to get this properly working with the different setup.py files for eduvpn and letsconnect, but if you know how to simply do this please do.

**Comment by gijzelaerr** [comment]
I've merged the setup.py for letsconnect into the main setup.py. The only disadvantage is that a `pip install eduvpn-client` will now also install a `letsconnect-client` script in your bin folder.

**Comment by gijzelaerr** [comment]
https://github.com/eduvpn/python-eduvpn-client/pull/228/commits/903bb90f56917dcd1d3f54ddabcbade7a10558b4
