### ISSUE TITLE
Create new ui files for all screens

### ISSUE THREAD

**Issue by gijzelaerr** [eduvpn/python-eduvpn-client#222]
We need to create 5 new screens:

* organisation selection screen
* server selection screen
* profile screen
* main screen
* settings screen

**Comment by amarsman** [comment]
See branch 2.0.x.

The screens are mostly there, remaining functionality is being added.

**Comment by amarsman** [comment]
- [ ] 
- [ ] 
- [ ]

**Comment by gijzelaerr** [comment]
the UI files are present, I've made new github issues for the items in your todo list.
