### ISSUE TITLE
Use DBus in case of VPN connection status change

### ISSUE THREAD

**Issue by gijzelaerr** [eduvpn/python-eduvpn-client#233]
https://developer.gnome.org/libnm-glib/stable/NMClient.html#nm-client-check-connectivity-async

**Comment by gijzelaerr** [comment]
This doesn't seem to do what we want, it only returns the status once. I guess we have to do it the old way:

https://github.com/eduvpn/python-eduvpn-client/blob/01a1fc972aade816ccbede4ccc60de9bd433dbdc/notebooks/monitor_status_change.ipynb

See eduvpn 1.0 source code for more examples.

**Comment by amarsman** [comment]
Actual vpn connection status is now used, async behaviour made it hard to debug.

When there is already an active vpn connection it is disconnected first before using the new vpn connection.
