### ISSUE TITLE
Switch the country_code instead of display_name for "Secure Internet"

### ISSUE THREAD

**Issue by fkooman** [eduvpn/python-eduvpn-client#235]
https://github.com/eduvpn/documentation/commit/ed2877bd0f23eb63436ec094e309b04fe4aa653a

with the `country_code` tag you can select both the flag from the artwork repository and either use the OS to do the mapping from country code to (internationalized) country name or the mentioned JSON file embedded in the app.

**Comment by amarsman** [comment]
This is fixed in branch 2.0.x
