### ISSUE TITLE
add logic to refresh configuration / certificates

### ISSUE THREAD

**Issue by gijzelaerr** [eduvpn/python-eduvpn-client#24]

**Comment by fkooman** [comment]
get new configuration before every connection attempt, certificates only when they are about to expire.

**Comment by gijzelaerr** [comment]
it is quite hard to change the config for network manager. workaround would be to delete the config and then recreate.

the expire date of the certificates can be found in the oauth token.

**Comment by gijzelaerr** [comment]
implemented
