### ISSUE TITLE
The repository 'https://repo.eduvpn.org/debian stretch Release' no longer has a Release file

### ISSUE THREAD

**Issue by mr-c** [eduvpn/python-eduvpn-client#240]
# Installation

https://python-eduvpn-client.readthedocs.io/en/master/introduction.html#debian-and-ubuntu

# Version

N/A

# OS/Distribution

Debian Bullseye

**Comment by gijzelaerr** [comment]
Thanks for reporting this. But, the release file is there right?

https://repo.eduvpn.org/debian/dists/stretch/Release

**Comment by mr-c** [comment]
`apt-get update` finds it now! Maybe my apt cacher was having a networking issue and it manifested this way. Sorry to bother!

**Comment by gijzelaerr** [comment]
no worries :)
