### ISSUE TITLE
new UI: improve token handling

### ISSUE THREAD

**Issue by amarsman** [eduvpn/python-eduvpn-client#246]
De "sessie" verloopt heel snel bij vpn.sp??r.nu
Acces token in 1 minuut (dan moet je dus nieuwe access token ophalen met refresh token), refresh token na 3 minuten
dan moet je de authorization opnieuw starten.

https://tools.ietf.org/html/rfc6749#section-5.2

Elke 15 minuten, om x:00,x:15,x:30, x:45 vindt er een server-reinstall plaats. Dan zijn alle tokens (oauth en x509) ongeldig. Dan moet de app netjes detecteren (tokens ongeldig) en browser openen voor relogin.

**Comment by gijzelaerr** [comment]
This depends on issue https://github.com/eduvpn/python-eduvpn-client/issues/251

When this is implemented, the token should be refreshed directly. If invalid, the user should be redirected to the auth step.

have a look at this schema:

https://github.com/eduvpn/python-eduvpn-client/blob/2.0.x/doc/flow.png

**Comment by gijzelaerr** [comment]
the refresh() in the CLI handles this properly, it will refresh the token using the token endpoint, if the signature is invalid the whole auth flow should start over.

**Comment by gijzelaerr** [comment]
This has been implemented
