### ISSUE TITLE
Retrieving of files from eduVPN server is done too often, conform to described flow

### ISSUE THREAD

**Issue by gijzelaerr** [eduvpn/python-eduvpn-client#255]

**Comment by amarsman** [comment]
See https://github.com/eduvpn/documentation/blob/v2/SERVER_DISCOVERY.md

**Comment by amarsman** [comment]
François K. @mentioned you in App must keep working when discovery server is down…

I added a little section to the SERVER_DISCOVERY document (https://github.com/eduvpn/documentation/blob/v2/SERVER_DISCOVERY.md):

The application MUST keep working when the discovery file(s) can not be downloaded and/or verified for whatever reason, including, but not limit to DNS does not resolve, traffic to the discovery server is blocked, server returns unexpected error code. In this case an user dismissable error MUST be shown, but it MUST NOT block the application from working with the old data already available to the app. Application releases SHOULD include the latest version from the discovery server before publishing the binary, if practical. This in case the discovery server is down on the application's first launch.

Maybe you already implemented it like this, i.e. that the app doesn't fail when the discovery server is gone, but if not, please implement this  Dániel  Aschwin  Roopesh

**Comment by jwijenbergh** [comment]
Fixed in version 4, install instructions https://python-eduvpn-client.readthedocs.io/en/latest/installation.html
