### ISSUE TITLE
Disconnecting from an already disconnected session doesnt work

### ISSUE THREAD

**Issue by WebSpider** [eduvpn/python-eduvpn-client#288]
# Installation

apt install eduvpn-client

# Version

1.1-1

# OS/Distribution

Ubuntu 18.04.5 LTS

# Logs

## Do you have a problem while adding a profile?

No problems adding a profile

## Do you have a problem during connecting?

No problems during connection phase

## Problem

When the underlying openvpn session is aborted, for instance due to long-term absence of wifi or suspending longterm (say, a weekend), the eduvpn-client still shows a 'Connected' state. Pressing 'Disconnect' in the UI will then trigger an error, reporting the network connection cannot be found.

There is no other way to get the client to work again other than restarting it

## Suggested fix

When detecting the underlying session from a connection is gone, reset the state to disconnected, instead of just showing the user an error and doing nothing to help the user to restart the VPN again

**Comment by gijzelaerr** [comment]
hi @WebSpider , thank you for your bug report. we are currently working hard to create a new 2.0, which changes a lot of the inner logic and I expect this to not happen anymore. We don't have a lot of time left to perform bug fixes for 1.1, so i don't think we will investigate this much further, sorry about that.

**Comment by WebSpider** [comment]
No problem, glad you are already addressing it!

I will check if the behaviour on 2.0 has changed, and will close the issue myself once confirmed.

**Comment by alvra** [comment]
This has been fixed. The app now tracks changes made to the connection outside of the app itself.

**Comment by WebSpider** [comment]
I don't see a new release since the version this bug is in?

**Comment by alvra** [comment]
Correct. This issue is fixed on the master branch but the new version is not completely ready for release. I'm working towards a 2.0 release.

**Comment by WebSpider** [comment]
Great stuff!

I'll keep a track on the new release, and will test ASAP after.

**Comment by gijzelaerr** [comment]
since this issue is resolved we can close it.
