### ISSUE TITLE
oauthlib deprication warning on Ubuntu 20.04

### ISSUE THREAD

**Issue by gijzelaerr** [eduvpn/python-eduvpn-client#310]
```
tests/test_oauth.py::TestOauth::test_get_oauth
  /usr/lib/python3/dist-packages/oauthlib/oauth2/rfc6749/clients/base.py:479: DeprecationWarning: Please switch to the public method populate_token_attributes.
```

**Comment by alvra** [comment]
The issue here is with how `requests-oauthlib` uses `oauthlib`, which has already been solved there: https://github.com/requests/requests-oauthlib/issues/334. Using version 1.1 doesn't give this warning.
I don't know what we can do on our side other than using newer version of `requests-oauthlib`.

**Comment by gijzelaerr** [comment]
ok fine, then we just leave it as it is! perfect.
