### ISSUE TITLE
CentOS: VPN service 'org.freedesktop.NetworkManager.openvpn' was not installed

### ISSUE THREAD

**Issue by katsel** [eduvpn/python-eduvpn-client#316]
# Installation

How did you install the eduVPN client?

```
sudo yum install yum-plugin-copr
sudo yum copr enable gijzelaerr/eduvpn-client
sudo yum install eduvpn-client
```

# Version

eduVPN Linux client version 0.0dev

# OS/Distribution

CentOS 8

# Logs

Running the commands above, eduVPN client installs flawlessly.
However, trying to install a profile for my organisation, results in an pop-up window with the following error message:
> org.freedesktop.NetworkManager.ConnectionNotAvailable: The VPN service 'org.freedesktop.NetworkManager.openvpn' was not installed

I was able to fix this issue by running
```
sudo dnf install NetworkManager-openvpn
```

So I guess that `NetworkManager-openvpn` should be in the Requires: for the `eduvpn-client` CentOS package.

**Comment by gijzelaerr** [comment]
oops, we missed that dependency! Thanks for reporting.
