### ISSUE TITLE
no notification

### ISSUE THREAD

**Issue by efef** [eduvpn/python-eduvpn-client#32]
in console I see:

INFO:eduvpn.ui:a configuration was selected
TypeError: select_config() takes exactly 2 arguments (4 given)

**Comment by gijzelaerr** [comment]
Is this the full stack trace (no more details for the error? What distribution is this?

**Comment by efef** [comment]
rogier@debian:~$ eduvpn-client 
INFO:eduvpn.ui:a configuration was selected
INFO:eduvpn.ui:a configuration was selected
TypeError: select_config() takes exactly 2 arguments (4 given)
^Z
[1]+  Stopped                 eduvpn-client
rogier@debian:~$ bg
[1]+ eduvpn-client &

rogier@debian:~$ cat /etc/debian_version 
9.1

**Comment by gijzelaerr** [comment]
I think this is unrelated to the no notification right?

**Comment by gijzelaerr** [comment]
ok the notifications are working
