### ISSUE TITLE
Implement the "change location" button on the main page.

### ISSUE THREAD

**Issue by alvra** [eduvpn/python-eduvpn-client#333]
Implement the "change location" button as described on [screen 1B](https://github.com/eduvpn/artwork/tree/master/App#screen-1b---first-screen-when-used-app-before).

**Comment by gijzelaerr** [comment]
This is implemented right? I already see a "change location" button

**Comment by alvra** [comment]
The button is there but the functionality not. Clicking it doesn't do anything yet
