### ISSUE TITLE
Implement a settings page

### ISSUE THREAD

**Issue by alvra** [eduvpn/python-eduvpn-client#334]
Implement the settings page as described on [screen 9](https://github.com/eduvpn/artwork/tree/master/App#screen-9---settings).

**Comment by efef** [comment]
settings page should contain a button to:
-force TCP (basically remove the UDP connect-lines from the .ovpn config)

In the past we were discussing a second item too, default gateway yes/no
But is seems this can be automated, so it doesn't require a configuration option anymore:
https://github.com/eduvpn/python-eduvpn-client/issues/167
There is an API change  https://github.com/eduvpn/documentation/blob/v2/API.md that toggles gateway true/false
