### ISSUE TITLE
Improve the UX around exceptions

### ISSUE THREAD

**Issue by alvra** [eduvpn/python-eduvpn-client#335]
Currently, for all exceptions the user is redirected to an error page with the technical error message, and a button to go back to the main page.

For instance, the UX can be hugely improved by:
  1. Provide better feedback on the problem encountered and possible solutions to resolve it.
  2. The "OK" button for errors is a common but serious anti-pattern.
  3. For solvable problems, don't interrupt the user's intended action entirely but instead show a message on the page directly inline, with instructions on how to proceed (for example, when an invalid custom server address was entered).
  4. For transient problems, provide a "retry" button so the user doesn't have to start over completely (for example, when loading an essential remote resource).

**Comment by jwijenbergh** [comment]
We now show an error revealer in version 4, which hopefully is nicer. Install instructions https://python-eduvpn-client.readthedocs.io/en/latest/installation.html
