### ISSUE TITLE
can't fetch instances - discovery not available due to rate limit (client v1 only)

### ISSUE THREAD

**Issue by efef** [eduvpn/python-eduvpn-client#342]
the python-eduvpn-client V1.x  uses the V1 discovery. This V1 discovery server is TCP rate limited because we once experienced a DOS on this server. Nowadays we have many institutes in the discovery-file and it seems the client is creating 50+ TCP sessions which might hit the TCP rate limit server side (in particular with many clients in a NAT-network).
Probably the client is downloading the institute images one by one and therefor generating many tcp sessions.

An error like this will be shown:
![image](https://user-images.githubusercontent.com/3393474/112320773-9e6c5f80-8caf-11eb-8b2d-057f1ce12ac0.png)

For eduVPN client v2 please make sure we optimize the amount of TCP sessions.

**Comment by mrvanes** [comment]
The 'Network is unreachable' is a side effect of the 'Connection refused' on the IPv4 address and following fallback to an unavailable IPv6 connection. This made the problem a bit harder to debug.

**Comment by gijzelaerr** [comment]
We are about to release 2.0, which doesn't do parallel fetching of icons anymore. People experiencing this issue are advised to upgrade to 2.0 once it becomes broadly available.
