### ISSUE TITLE
Add tray icon

### ISSUE THREAD

**Issue by gijzelaerr** [eduvpn/python-eduvpn-client#352]
We want a tray icon that runs the client in the background. I know gnome considers this bad UI, but this enables us to perform tasks like cert renewal in the background (#188)

**Comment by alvra** [comment]
@gijzelaerr I cannot get your suggestion to hide/show the window when minimized to tray, to work. The `window.show()` causes a segfault. It appears we do need a GTK application to get this to work.
https://stackoverflow.com/a/10972241
https://marc.info/?l=gtkmm&m=146693165929685

**Comment by alvra** [comment]
As "tray icons" (Gtk StatusIcon) have been [deprecated](https://docs.gtk.org/gtk3/class.StatusIcon.html#description) and don't show on modern Gnome desktops, notifications should be used instead.

The plan is to show a notification while a connection is active, even when the app window is closed. The app will remain running in the background and notify the user through messages when the session is about to expire (15min before expiry). When the app window is closed while no connection is active, it will exit completely.

**Comment by jwijenbergh** [comment]
StatusNotifier should probably be fine to implement

**Comment by jwijenbergh** [comment]
I had a look at this and everywhere I look I see deprecated APIs. The APIs that are non-deprecated are forks or poorly documented. I think it's not worth it
