### ISSUE TITLE
command line config not working in GUI mode

### ISSUE THREAD

**Issue by efef** [eduvpn/python-eduvpn-client#360]
Installed the master version, via read the docs instructions for debian 10

When I am trying:
eduvpn-cli configure https://demo.eduvpn.nl

next I login in webbrowser, click 'approve'. In the terminal I read an .ovpn was downloaded. So it looks good.
Next I run the "eduvpn-gui" client and try to connect to the demo-server by clicking on 'demo.eduvpn.nl'
I get a "finishing authorization" with spinning wheel. Next I get this error in the GUI:
**HTTPSConnectionPool(host='demo.eduvpn.nlinfo.json', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f81da440ac8>: Failed to establish a new connection: [Errno -2] Name or service not known'))**

**Comment by alvra** [comment]
I've published a fix: #361.

As a workaround, it probably works if you append a `/` to the address.

**Comment by gijzelaerr** [comment]
should be fixed
