### ISSUE TITLE
archlinux package

### ISSUE THREAD

**Issue by fkooman** [eduvpn/python-eduvpn-client#365]
Someone created an archlinux package for the client! :+1: 

Maybe this can be mentioned in the documentation as well.

https://aur.archlinux.org/packages/python-eduvpn-client/

**Comment by alvra** [comment]
I haven't been able to test this arch package myself and I cannot tell what the source is or who is behind it. As such, I'm reluctant to mention it in the docs. Maybe if we have more information, we can refer to it in the docs as an "third-party contribution without official support".

**Comment by burgerga** [comment]
Using the PKGBUILD you can see who is the maintainer and what steps are done to build and install the package: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-eduvpn-client

It is not working for me though (on Manjaro)... I'm trying to figure out more,  will let you know via a separate issue.
