### ISSUE TITLE
app logic error when cancelling request

### ISSUE THREAD

**Issue by gijzelaerr** [eduvpn/python-eduvpn-client#368]
to reproduce:
 * search for surf
 * click surfnet secure internet
 * directly cancel
 * search again
 * the previous action (select surfnet secure internet) is executed

expected behavior:
 * I should be able to search again

**Comment by alvra** [comment]
I can reproduce this, but not exactly as you describe.
1. Click cancel during oauth.
2. The search page is shown again.
3. Enter the first character of a search query.
4. The item directly below the one selected in step 1 is immediately chosen. This happens even if it is not one of the results in the new search.

Note this problem does not occur when there is no next item (ie. when selecting the last item in the result list).

I'm not sure why this happens but it seems to be something strange related to how gtk manages selections.

**Comment by gijzelaerr** [comment]
yeah, i don't rule out that this could be a gtk bug or a result of suttle unintended bug on our side caused by misuse of the GTK lib. If that's the case, I've been here before, and it is not trivial to figure out what could be causing this.

**Comment by gijzelaerr** [comment]
i'm unable to reproduce this, the issue seems to be resolved.
