### ISSUE TITLE
modify 'display_name' to "eduVPN for Linux"

### ISSUE THREAD

**Issue by fkooman** [eduvpn/python-eduvpn-client#37]
https://github.com/gijzelaerr/python-eduvpn-client/blob/41df2b9ec0ece49638c91a16b0ed1fae5d7bd89b/eduvpn/remote.py#L122

currently this is `notebook`, not really descriptive. Better make this `eduVPN for Linux`. Don't forget HTTP POST encoding if needed.

**Comment by gijzelaerr** [comment]
ah right
