### ISSUE TITLE
venv: error: the following arguments are required: ENV_DIR

### ISSUE THREAD

**Issue by fantostisch** [eduvpn/python-eduvpn-client#388]
The README says to run `python3 -m venv`, but this results in:
```
$ python3 -m venv
usage: venv [-h] [--system-site-packages] [--symlinks | --copies] [--clear] [--upgrade] [--without-pip]
            [--prompt PROMPT] [--upgrade-deps]
            ENV_DIR [ENV_DIR ...]
venv: error: the following arguments are required: ENV_DIR
```

using Python 3.9.2 on Debian Unstable.

Is it supposed to say `python3 -m venv venv`?

**Comment by gijzelaerr** [comment]
yes, you are right, fixed.

**Comment by arefnajafkia** [comment]
Python does not execute all the codes and gives this error
$ python3 -m venv
usage: venv [-h] [--system-site-packages] [--symlinks | --copies] [--clear] [--upgrade] [--without-pip]
            [--prompt PROMPT] [--upgrade-deps]
            ENV_DIR [ENV_DIR ...]
venv: error: the following arguments are required: ENV_DIR
