### ISSUE TITLE
Make RPM

### ISSUE THREAD

**Issue by gijzelaerr** [eduvpn/python-eduvpn-client#39]
https://fedoraproject.org/wiki/Packaging:Python

**Comment by fkooman** [comment]
Not sure you are also using "eggs", but: https://fedoraproject.org/wiki/Packaging:Python_Eggs

**Comment by gijzelaerr** [comment]
This should do the trick https://github.com/eduvpn/python-eduvpn-client/blob/master/eduvpn-client.spec
