### ISSUE TITLE
Make Wireguard notebook prototype

### ISSUE THREAD

**Issue by gijzelaerr** [eduvpn/python-eduvpn-client#402]
https://github.com/eduvpn/documentation/blob/v2/API_V3.md

**Comment by gijzelaerr** [comment]
@fkooman When I do a standard instance discovery I only get instances that support API#2 but no #3 (yet), is this right? If so, is there a #3 test server?

**Comment by fkooman** [comment]
Yes there is: https://vpn-next.tuxed.net/  you can use the same credentials as for vpn.tuxed.net with FrKoIdP.

**Comment by gijzelaerr** [comment]
A change that has not been mentioned in the v3 document `api_base_uri -> api_endpoint`

**Comment by fkooman** [comment]
> A change that has not been mentioned in the v3 document `api_base_uri -> api_endpoint`

It is mentioned here: https://github.com/eduvpn/documentation/blob/v2/API_V3.md#endpoint-discovery or do you mean something else?

**Comment by gijzelaerr** [comment]
at the top of the document is stated 'The only difference between APIv2 and APIv3 is that refresh tokens are now single use' but this seems to be another difference.

**Comment by fkooman** [comment]
Right, that was referring to OAuth 2, I'll improve that section. The rest of the API is completely different...

**Comment by gijzelaerr** [comment]
yes, noticing that now, working down the document.

**Comment by fkooman** [comment]
https://github.com/eduvpn/documentation/commit/13ed958d65981a2744683ffbffae1c0d2c51e36d

**Comment by gijzelaerr** [comment]
also getting a 401 user not found with my FrKoIdP credentials

**Comment by fkooman** [comment]
> also getting a 401 user not found with my FrKoIdP credentials

mailed you new credentials

**Comment by gijzelaerr** [comment]
looks like my mail VM died yesterday, can you mail it to gijsmolenaar@gmail.com?

**Comment by fkooman** [comment]
> looks like my mail VM died yesterday, can you mail it to [gijsmolenaar@gmail.com](mailto:gijsmolenaar@gmail.com)?

Done!

**Comment by gijzelaerr** [comment]
I get a 400 when I call `https://vpn-next.tuxed.net/vpn-user-portal/api.php/v3/connect` with `{'profile_id': 'default-gw',
 'public_key': 'reVX/RPDnGiuYJuUkTP8gj3ec74LcDP34eDWCUhi9gA='}` as data. The requests looks like:
```
POST / HTTP/1.1
Host: localhost:8765
User-Agent: python-requests/2.24.0
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Content-Length: 81
Content-Type: application/x-www-form-urlencoded

profile_id=default-gw&public_key=reVX%2FRPDnGiuYJuUkTP8gj3ec74LcDP34eDWCUhi9gA%3D
```

Which as far  as I know is almost identical to the request in the v3 doc:
```
POST / HTTP/1.1
Host: localhost:8765
User-Agent: curl/7.68.0
Accept: */*
Content-Length: 78
Content-Type: application/x-www-form-urlencoded

profile_id=employees&public_key=nmZ5ExqRpLgJV9yWKlaC7KQ7EAN7eRJ4XBz9eHJPmUU%3D
```

So I'm not sure what I'm doing wrong there?

If I (wrongfully) JSON encode the arguments and send them to the server returns a 500 error which Is probably a server bug:
```
POST / HTTP/1.1
Host: localhost:8765
User-Agent: python-requests/2.24.0
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Content-Length: 90

{"profile_id": "default-gw", "public_key": "reVX/RPDnGiuYJuUkTP8gj3ec74LcDP34eDWCUhi9gA="}
```

**Comment by fkooman** [comment]
`default-gw` -> `default-wg`

**Comment by fkooman** [comment]
And yes, I agree that the error handling is currently very very bad... will fix that in the next weeks.

**Comment by fkooman** [comment]
Not sure if you saw this one already, maybe it didn't make its way to you: https://paste.sr.ht/~fkooman/04fbb9a3d849a831ce3c8a31fa7d57d6f5b1f648

**Comment by fkooman** [comment]
```
$ curl -i -d "profile_id=employees" --data-urlencode "public_key=nmZ5ExqRpLgJV9yWKlaC7KQ7EAN7eRJ4XBz9eHJPmUU=" -H "Authorization: Bearer ${B}"     "https://vpn-next.tuxed.net/vpn-user-portal/api.php/v3/connect"
HTTP/1.1 400 Bad Request
Date: Thu, 29 Jul 2021 13:35:08 GMT
Server: Apache/2.4.48 (Fedora) OpenSSL/1.1.1k
X-Powered-By: PHP/7.4.21
Strict-Transport-Security: max-age=15768000
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json

{"error":"profile not available or no permission"}
```

The error is actually already quite clear for the wrong profile ID.

**Comment by fkooman** [comment]
```
$ curl -i -d '{"profile_id":"employees"}' -H "Content-Type: application/json" -H "Authorization: Bearer ${B}"     "https://vpn-next.tuxed.net/vpn-user-portal/api.php/v3/connect"
HTTP/1.1 500 Internal Server Error
Date: Thu, 29 Jul 2021 13:38:55 GMT
Server: Apache/2.4.48 (Fedora) OpenSSL/1.1.1k
X-Powered-By: PHP/7.4.21
Strict-Transport-Security: max-age=15768000
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json

{"error":"missing post parameter \"profile_id\""}
```

This should indeed be a 400.

**Comment by gijzelaerr** [comment]
This is almost done:

https://github.com/eduvpn/python-eduvpn-client/blob/master/notebooks/demo_enroll_wireguard.ipynb

This does the v3 enrollment, creates a wireguard profile and activates it, all from python + network manager calls.

The main conclusions are:
 * We can do everything from python without the need for new python libraries or other dependencies
 * It is actually quite simpleMain
 * Network Manager > 1.16 has good support for wireguard
 * The gnome shell/ui doesn't have support for wireguard yet, there is no UI integration as is with openVPN. No visual hints that wireguard is active.

two remaining issues:
 * The connection isn't functional, I guess I'm missing a setting but I didn't figure out which one yet. If I manually import the config file it just works. Maybe a mistake with IP parsing or something.
 * The key generating is still done using `wg`, this is the only external requirement.

**Comment by gijzelaerr** [comment]
I think the notebooks show that wireguard can be used, and integration with the eduvpn client is possible. We are not going to add wireguard support for 2.2, probably this is going to be 2.3+.
