### ISSUE TITLE
Investigate multi user support and document findings and results

### ISSUE THREAD

**Issue by gijzelaerr** [eduvpn/python-eduvpn-client#403]

**Comment by alvra** [comment]
NetworkManager "make available to other users" works exactly as you might expect:
- If selected (default), the VPN is active for all users. It is configurable for all through NM, but in the EduVPN client only for the user that created it.
- If unselected, it will not be active nor configurable for other users; thus effectively making it unobservable for other users.

As such, there seem to be the following approaches to multi-user support:
1. Leave the situation as it is now, with availability selected.
  Those who require multi-user support, can do so through NM itself. For this to work, reusing the NM connection like we do now is required.
2. Always unselect availability, and require each user to setup their own vpn connection. In other words; no multi-user support.
  Those who run multiple services (eg. servers) from multiple user accounts would be required to setup a vpn connection for each of these, or they could explicitly make it available for all users.
3. Make EduVPN completely systemwide, by storing the config where it's accessible for all users.
  Like (1) except that all users can manage the connection through EduVPN.
4. Introduce a EduVPN systemwide service that manages a system-wide vpn connection and allow users to configure it in their local apps.
  Like (3) except that it would allow the app greater control to avoid complications with conflicting connections from different users.
