### ISSUE TITLE
Investigate possibilities to have a headless mode (no X-server)  and document findings and results here

### ISSUE THREAD

**Issue by gijzelaerr** [eduvpn/python-eduvpn-client#404]

**Comment by jwijenbergh** [comment]
I have looked at this but I guess this can be considered out of scope. Headless oauth is hard to implement reliably for every organisation

**Comment by gijzelaerr** [comment]
agreed, lets move this to a future release and decide then if we still want this.

**Comment by gijzelaerr** [comment]
i guess we just really dont want to add support for this to the client, people can set this up manually if they need to.
