### ISSUE TITLE
Re-do the CLI again

### ISSUE THREAD

**Issue by gijzelaerr** [eduvpn/python-eduvpn-client#405]
the current CLI works, but can be more user-friendly

**Comment by jwijenbergh** [comment]
The CLI has been rewritten, interactive mode "eduvpn-cli interactive" should be pretty user friendly but the normal CLI needs documentation

**Comment by mmahmoudian** [comment]
The `interactive` subcommand is heavily missing the point of the major use-case of a CLI. The CLI is usually used for automation and scripting. Therefore, the interactive is useless in 100% of automation use-cases, and it is only and only helpful if one wants to use it as an alternative to GUI.

Having manpage, infopage, better error and messaging and clarifying the steps for the sake of logging and finding the point of failure is what that can improve the CLI experience imho.

Maybe at some point I add manpage and add the missing documentation.

**Comment by jwijenbergh** [comment]
> The interactive subcommand is heavily missing the point of the major use-case of a CLI. The CLI is usually used for automation and scripting. Therefore, the interactive is useless in 100% of automation use-cases, and it is only and only helpful if one wants to use it as an alternative to GUI.

That's exactly why it's been made, as an alternative to the GUI. For scripting there are a bunch of flags that you can use. The reason why I have not extensively documented these outside of `--help` is that I am not super happy with them. I think I have to rewrite the CLI again but this time make a document of how it should work beforehand

**Comment by jwijenbergh** [comment]
This repository was moved to Codeberg: https://codeberg.org/eduVPN/linux-app/issues/405
