### ISSUE TITLE
setup.py SyntaxError

### ISSUE THREAD

**Issue by gothicVI** [eduvpn/python-eduvpn-client#411]
Running python 3.9.7, I'm getting the following error when trying to build the AUR package:
```
==> Starting build()...
  File "setup.py", line 39
    def extra_files_line(dir_: str):
                             ^
SyntaxError: invalid syntax
==> ERROR: A failure occurred in build().
    Aborting...
error making: python-eduvpn-client
```
EDIT: Somewhat solved:
I have `~/bin/python` being a symlink to `/bin/python2` in order to have some old scripts working.
Removing that symlink allowed for a smooth build...
Maybe this can be addressed somehow by not calling `python` (blindly) and assuming `python3`?
Could an explicit shebang solve this?

**Comment by alvra** [comment]
Arch linux isn't something we officially support. How exactly are you building the AUR package?

We could add the shebang if that helps people running Arch, but maybe this needs to be fixed in the build script that is maintained by a third-party. Where do you propose adding the shebang?

**Comment by gijzelaerr** [comment]
To me it looks like python2 is somehow called, since the syntax is only incorrect for python2 (it doesn’t support type annotation for function arguments)

**Comment by gothicVI** [comment]
@alvra, @gijzelaerr thanks for your replies.

Find the packagebuild [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-eduvpn-client&id=1bef8095d885d81f455626430fcd4bb1a67293cc) (it has since been changed - see following).
There, the `build` function sinply calls `python` which in my case links to `python2`. Removing the link calls `python3` which makes it build and install properly.

The maintainer today pushed a [change](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-eduvpn-client&id=3f400c8914b77964cd5ec806c07519f034e69708) where `python` now explicitly is `/usr/bin/python`. I haven't tested this change yet but I'd assume this already does the trick.

Anyhow, I'd suggest somehow checking in `setup.py` which `python` version is actually calling the script and failing if it's `python2`.

**Comment by alvra** [comment]
If Arch still defaults `python` to `python2` then it seems like the build script sound explicitly use `python3`. However, you'd have to discuss that with the maintainers of the third-party package.

I don't think us adding checks for a legacy python version just to have a nicer error message is a good tradeoff here.

**Comment by gijzelaerr** [comment]
I agree with @alvra , we clearly state in the doc which Python version is supported, no need for adding extra checks. I think we can close this issue since the problem has been identified.

**Comment by gothicVI** [comment]
@alvra no, Arch does not. As stated that was my symlink and the package maintainer "fixed" it with the hard link.
Still, your package requires `python3` but at no time you're checking what `python` version is calling `setup.py`. You might want to do that especially since it's an official `python` packaging recommendation.

**Comment by gijzelaerr** [comment]
The version is documented and indicated in the metadata:

https://github.com/eduvpn/python-eduvpn-client/blob/master/setup.py#L75

if a user then uses the wrong, old and end of life python version is a user error.  Even if we would add a check it makes the code harder to read and maintain since the syntax changed. Take this `setup.py` as an example:

```
from sys import version_info

if version_info.major != 3:
    raise Exception("update your python")

def func(bla: str):
    print("func called with " + bla)
```

will still raise a syntax error:
```
$ python2 setup.py.py
  File "bla.py", line 6
    def func(bla: str):
                ^
SyntaxError: invalid syntax
```
so unless we move the actual setup code to another module that is loaded after the `setup.py` is parsed this is not going to work. Just to give an error for the obscure case where someone calls `setup.py` with python2 does not justify that added complexity.
