### ISSUE TITLE
CLI and GUI do not start (on FC33)

### ISSUE THREAD

**Issue by arjenpdevries** [eduvpn/python-eduvpn-client#415]
# Installation

I followed the Fedora Linux instructions on `ru.eduvpn.nl`.

# Version

`eduVPN Linux client version 0.0dev`

(I suppose the version number is the problem.)

# OS/Distribution

Linux, Fedora Core 33.

# Logs

Problem is the same for `eduvpn-cli` and `eduvpn-gui`.

```
$ eduvpn-gui
Traceback (most recent call last):
  File "/usr/bin/eduvpn-gui", line 33, in <module>
    sys.exit(load_entry_point('eduvpn-client==2.1.0', 'gui_scripts', 'eduvpn-gui')())
  File "/usr/bin/eduvpn-gui", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration
```

**Comment by efef** [comment]
Hi @arjenpdevries , I just downloaded a Fedora 33 live image, followed the instructions (https://python-eduvpn-client.readthedocs.io/en/master/installation.html#fedora-and-centos)  and basically did:
$ sudo dnf install dnf-plugins-core
$ sudo dnf copr enable @eduvpn/eduvpn-client
$ sudo dnf install eduvpn-client

Next I could run eduVPN-gui client normally.
Maybe you could elaborate a bit about how you installed it?

**Comment by gijzelaerr** [comment]
we can't replicate this issue and reported didn't respond, closing this issue. Please reopen if you experience this issue again.
