### ISSUE TITLE
Properly skip NM tests if nm is not available

### ISSUE THREAD

**Issue by gijzelaerr** [eduvpn/python-eduvpn-client#434]
This fails during test run while building the packages. There is no network traffic allowed during package building, so the build fails (on copr).

**Comment by gijzelaerr** [comment]
This is still an issue and the test is currently skipped.

**Comment by jwijenbergh** [comment]
I have renamed this issue to tackle a related issue

**Comment by jwijenbergh** [comment]
fixed in master
