### ISSUE TITLE
python client requires gobject-introspection

### ISSUE THREAD

**Issue by RABijl** [eduvpn/python-eduvpn-client#441]
Maybe not a bug in the conventional sense, but I didn't see it in the documentation and thought I should mention it. Installing the python client requires you to have `gobject-introspection` installed (for example with your distro package manager). this stackoverflow [post](https://stackoverflow.com/questions/59140646/package-gobject-introspection-1-0-was-not-found-in-the-pkg-config-search-path-in) gives some more info.

# Installation

installed via pip in a virtualenv

# Version

2.2.0

# OS/Distribution
Arch Linux

# Logs

 ```
Building wheels for collected packages: pygobject
  Building wheel for pygobject (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/shmoopy/virtualenvs/eduvpn/bin/python /home/shmoopy/virtualenvs/eduvpn/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpv3b5td6g
       cwd: /tmp/pip-install-y8b9ahyk/pygobject_56e0c6ad9bd142aa9ae0cb3a0dff98a6
  Complete output (9 lines):
  running bdist_wheel
  running build
  running build_py
  running build_ext
  Package gobject-introspection-1.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `gobject-introspection-1.0.pc'
  to the PKG_CONFIG_PATH environment variable
  Package 'gobject-introspection-1.0', required by 'virtual:world', not found
  Command '('pkg-config', '--print-errors', '--exists', 'gobject-introspection-1.0 >= 1.56.0')' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for pygobject
Failed to build pygobject
ERROR: Could not build wheels for pygobject, which is required to install pyproject.toml-based projects 
```

**Comment by gijzelaerr** [comment]
Arch is not officially supported (yet) but there seems to be a package:

https://github.com/eduvpn/python-eduvpn-client/issues/365

We do cover the installation of `gobject-introspection` implicitly in the installation manual:

https://python-eduvpn-client.readthedocs.io/en/master/installation.html#manual-source-installation

For dnf and deb the package is installed in the make target:

https://github.com/eduvpn/python-eduvpn-client/blob/master/Makefile#L58
https://github.com/eduvpn/python-eduvpn-client/blob/master/Makefile#L41
