### ISSUE TITLE
missing README.md?

### ISSUE THREAD

**Issue by fkooman** [eduvpn/python-eduvpn-client#46]
RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.RpiJB0 (%doc)
    File not found: /home/fkooman/rpmbuild/BUILDROOT/eduvpn_client-0.8-1.fc26.x86_64/usr/share/doc/python2-eduvpn-client/README.md

**Comment by gijzelaerr** [comment]
hm, thats weird. looks like the sdist export doesn't include the `README.md`

**Comment by gijzelaerr** [comment]
fixed
