### ISSUE TITLE
UX: Profile name should be shown in the connection screen

### ISSUE THREAD

**Issue by Lukas-UAUX** [eduvpn/python-eduvpn-client#465]
# Installation
How did you install the eduVPN client? 

-> Via the repository

# Version
What version of the client you are running? Try your package manager or otherwise `$ eduvpn-client -v`.

-> 2.2.1-1

# OS/Distribution
What operating system/distribution and version you are running?

-> Ubuntu 20.04.4

## Do you have a problem during connecting?
Sometimes (ege. when using the back button with an already active VPN) clicking in the free space below the profile list an unidentifiable profile is selected and connected. 

Also the Name is not shown on the connection screen.

**Comment by jwijenbergh** [comment]
first part of this is fixed

**Comment by Lukas-UAUX** [comment]
Looking at the very nice beta release 3.2.0 with the new eduvpn-common this is now fixed.
