### ISSUE TITLE
[v3] does not show selected profile on connected page

### ISSUE THREAD

**Issue by fkooman** [eduvpn/python-eduvpn-client#478]
Also mentioned in #465 for 2.x as well. 

Problem: what is missing on the screen is the current profile you are connected to.

Connected using WireGuard to `WireGuard Only` profile on https://vpn-next.tuxed.net:

![image](https://user-images.githubusercontent.com/616885/164387091-d6cbc12b-9599-4142-aedd-4c3d8cd8e269.png)

Connected using OpenVPN to `OpenVPN Only` profile on https://vpn-next.tuxed.net:

![image](https://user-images.githubusercontent.com/616885/164387310-d45db048-0f31-45b2-9bdf-b43a024ac844.png)

Client version: 9435e9d1d16aa528fca78def71bf9a7264fe1398 with PR #477 applied.

**Comment by jwijenbergh** [comment]
Fixed in version 4, install instructions https://python-eduvpn-client.readthedocs.io/en/latest/installation.html
