### ISSUE TITLE
[v3] client "forgets" authorization from previously added server when adding new one

### ISSUE THREAD

**Issue by fkooman** [eduvpn/python-eduvpn-client#481]
When adding >1 server to the client the authorization from the previous server is lost. But not always. I can't really quite figure it out, but there is something wrong somewhere with token storage/replacement/reading where the wrong one is read, or the old one is overwritten or something.

Client version: https://github.com/eduvpn/python-eduvpn-client/commit/9435e9d1d16aa528fca78def71bf9a7264fe1398 with PR https://github.com/eduvpn/python-eduvpn-client/pull/477 and https://github.com/eduvpn/python-eduvpn-client/pull/480 applied.

**Comment by jwijenbergh** [comment]
Fixed in version 4, install instructions https://python-eduvpn-client.readthedocs.io/en/latest/installation.html
