### ISSUE TITLE
eduvpn does not work. It shows  loading of API endpoints  failed.......

### ISSUE THREAD

**Issue by Vanakeethan** [eduvpn/python-eduvpn-client#485]
# Installation

How did you install the eduVPN client?

# Version

What version of the client you are running? Try your package manager or otherwise `$ eduvpn-client -v`.

# OS/Distribution

What operating system/distribution and version you are running?

# Logs

## Do you have a problem while adding a profile?

Eduvpn will print out information to the console while running. Please try running `eduvpn-client` in a console.  Are there any interesting logs appearing when you try to connect? There is also a more verbose mode available which is enabled with the `-d` flag.

## Do you have a problem during connecting?

Please examine the eduvpn for errors or messages while connecting. Note that the actual VPN connection management is not done by eduVPN, but by network management tool bundeled with your OS named networkManager. You can examine the NetworkManager logs with `$ sudo journalctl -u NetworkManager`.

``
![image](https://user-images.githubusercontent.com/46950912/167124114-79146109-0467-4ea7-93b3-c04e9040e871.png)

**Comment by jwijenbergh** [comment]
Note that this seems to be a server issue, https://eduvpn.ac.lk is not loading for me.

**Comment by gijzelaerr** [comment]
hi @Vanakeethan, @jwijenbergh is correct, it looks like you are using the Windows client. Any issues with the windows client should be reported at https://github.com/Amebis/eduVPN.

**Comment by Vanakeethan** [comment]
> Is this linux or windows? This looks like the windows version, while this repository is for the linux client.

Yeah it is windows version but this message showed in Linux also.

**Comment by Vanakeethan** [comment]
> hi @Vanakeethan, @jwijenbergh is correct, it looks like you are using the Windows client. Any issues with the windows client should be reported at https://github.com/Amebis/eduVPN.  

Now it is working 🤝👏
Thank you ☺️
