### ISSUE TITLE
Flatpak 

### ISSUE THREAD

**Issue by supertoni90** [eduvpn/python-eduvpn-client#487]
I was using eduVPN for a long time but since I switched to Fedora Silverblue I can't install it without layering (which should be avoided). Also I think it's easier to maintain only one distribution-agnostic package.

**Comment by Lukas-UAUX** [comment]
I am pretty sure, that in the current state of flatpak a 'pure' flatpak vpn package is not really possible, especially as system services are not a thing (at least yet) - stock OpenVPN is not available either (in fact I have not found any VPN-App in flathub so far). 

The only way I think could work is by having all openvpn/wireguard dependencies already set up (by a regular package manager or as part of the read-only files system of your immutable distro) and build an App that just interfaces (via D-Bus?) with the NetworkManager to import the Profile. 

Which still means the app can only work, if the dependencies can be fulfilled and it has to break the sandbox which kinda defeats the purpose..

It may be possible in the future through a newly created portal but for now...
