### ISSUE TITLE
Linux eduVPN-client fails getting server details

### ISSUE THREAD

**Issue by ajesteves** [eduvpn/python-eduvpn-client#499]
Lately eduvpn-client stopped working properly on ubuntu 22.04.
When trying to connect to a VPN server, the GUI keeps trying to get server details and don't finish connection.
Someone else have experienced the same problem?

**Comment by jwijenbergh** [comment]
We released another eduVPN version today. The Ubuntu/debian packages will be updated soon. In the meantime can you try the latest release by e.g. cloning this repository with git and running python3 -m eduvpn.ui? Your issue sounds like some of the fixed ones.

If not, then we'd need more information. A video would be nice or some logs.

**Comment by ajesteves** [comment]
it seems the gateway is funcionarios.eduvpn.uminho.pt

**Comment by jwijenbergh** [comment]
Hmmm choosing uminho gives me the login page as expected. Does it only happen for that server? Anyways the best steps forward is to test with the latest release. If you're not able to test it with cloning git, then no problem I will let you know when the packages are updated.

**Comment by jwijenbergh** [comment]
@ajesteves can you do a sudo apt update, and try again?

**Comment by ajesteves** [comment]
there is not a new package to update

**Comment by jwijenbergh** [comment]
> there is not a new package to update

eduvpn-client -v should give you 3.1.0

if it doesn't then you probably did not install through our official repositories. Try:
https://python-eduvpn-client.readthedocs.io/en/master/installation.html#debian-and-ubuntu

If the issue still persists, please upload a video

**Comment by ajesteves** [comment]
sudo apt install eduvpn-client

These packages will be installed:
  eduvpn-client-data python3-eduvpn-client
Suggested packages:
  eduvpn-client-doc
The following NEW packages will be installed:
  eduvpn-client eduvpn-client-data python3-eduvpn-client

Get:1 https://app.eduvpn.org/linux/deb stable/main amd64 eduvpn-client-data all 3.1.0-1 [832 kB]
Get:2 https://app.eduvpn.org/linux/deb stable/main amd64 python3-eduvpn-client all 3.1.0-1 [45.5 kB]
Get:3 https://app.eduvpn.org/linux/deb stable/main amd64 eduvpn-client all 3.1.0-1 [7464 B]

**Comment by ajesteves** [comment]
ubuntu is not retrieving 3.1.10 but instead 3.1.0-1

**Comment by jwijenbergh** [comment]
3.1.0-1 is the latest version

**Comment by ajesteves** [comment]
Next follows the terminal log when i run "python3 -m eduvpn.ui". In my laptop the vpn connection succeeds, but on desktop the eduvpn-client does not succeed on getting the vpn server details.
 
oauth-refresh - INFO - eduvpn.remote - remote.py:25 - Requesting https://eduvpn.uminho.pt/.well-known/vpn-user-portal

load-server-info - INFO - eduvpn.remote - remote.py:25 - Requesting https://eduvpn.uminho.pt/.well-known/vpn-user-portal

Exception in thread load-server-info:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/eduvpn/interface/event.py", line 106, in on_start_connection
    all_profiles = profile_server_info.list_profiles(oauth_session)
  File "/usr/lib/python3/dist-packages/eduvpn/server.py", line 234, in list_profiles
    return [Profile(**data) for data in profiles]
  File "/usr/lib/python3/dist-packages/eduvpn/server.py", line 234, in <listcomp>
    return [Profile(**data) for data in profiles]

TypeError: Profile.__init__() got an unexpected keyword argument 'vpn_proto_preferred'

**Comment by jwijenbergh** [comment]
Thanks for reporting, that helps! This is because the server is not the latest version. Can you try #502?

```
git clone https://github.com/jwijenbergh/python-eduvpn-client.git -b fix-extra-arguments-profile python-eduvpn-client-fixed
cd python-eduvpn-client-fixed
python3 -m eduvpn.ui
```

**Comment by ajesteves** [comment]
Thank you, your suggestion worked fine.
What is the procedure to update the eduvpn, since you said it was not the most recent one?
Now i updated it by copying the content of the downloaded "eduvpn" folder to the system "eduvpn" python folder.

**Comment by jwijenbergh** [comment]
To update the `server`, follow: https://github.com/eduvpn/documentation/blob/v3/INSTALL_UPDATES.md

If you mean the `client`, which is about this repository then you're already the latest version. The fix I gave is not in a new release just yet
