### ISSUE TITLE
make sure 2fa is working

### ISSUE THREAD

**Issue by gijzelaerr** [eduvpn/python-eduvpn-client#51]
https://github.com/eduvpn/python-eduvpn-client/commit/69e0e24050224fe0bde3b3fbb3847bba511c505e will enalbe a password prompt upon connect when a auth-user-pass field is in the openvpn config file.

**Comment by gijzelaerr** [comment]
currently when the ovpn config file contains a 'auth-user-pass' statement it will set authentication type to "password with certificates (TLS)", ask for the password every time and the username is fixed to 'totp'.

I think it is a good idea to enhance the server API to make it possible to query the 2fa type used, so the user is not bothered with entering a username.

That said, I can't get 2FA to work yet. Not sure what, since I have no way to examine the log files.

**Comment by fkooman** [comment]
The problem was the server, it actually works! But indeed, TOTP only.

**Comment by fkooman** [comment]
As for exposing 2FA enrollment, would this help? https://github.com/eduvpn/vpn-user-portal/commit/57d0a0ab7a3f9fdcca0c1283f90f253bde87249e (not released!) it still could return both "yubi" and "totp", so the user would still have to choose...

Currently, the server admin cannot enforce a certain 2FA type to be used, maybe this is something that we want, but it is not there yet.

**Comment by gijzelaerr** [comment]
ok well, 2fa is now supported, but only TOTP. I will add a choice menu when 1.0.6 is released and deployed. 

new issue: https://github.com/eduvpn/python-eduvpn-client/issues/59
