### ISSUE TITLE
Errors when using with Ubuntu 22.04 under WSL2, unable to connect using cli

### ISSUE THREAD

**Issue by jguhlin** [eduvpn/python-eduvpn-client#525]
# Installation

Via the wiki, https://python-eduvpn-client.readthedocs.io/en/master/installation.html Ubuntu options: via apt
(Minor note, those instructions require using the bash shell, and are not compatible with some others, but worked great once I switched over temporarily)

# Version

eduVPN client version 4.0.1

# OS/Distribution

Ubuntu 22.04 under WSL 1.1.6.0 under Windows 10

# Logs
```fish
(base) josephguhlin@Joey-PC:~$ eduvpn-cli interactive
error when checking if keyring is available: g-spawn-exit-error-quark: Error spawning command line “dbus-launch --autolaun
ch=f13bd90ea507e1e5c10c0a0c5efd72b6 --binary-syntax --close-stderr”: Child process exited with code 1 (1)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/eduvpn/nm.py", line 770, in <lambda>
    GLib.idle_add(lambda: action(callback=quit_loop))
  File "/usr/lib/python3/dist-packages/eduvpn/cli.py", line 471, in update_state_callback
    state = self.nm_manager.connection_state
  File "/usr/lib/python3/dist-packages/eduvpn/nm.py", line 175, in connection_state
    for connection in self.client.get_active_connections()
AttributeError: 'NoneType' object has no attribute 'get_active_connections'
```
From here it is frozen, this is my first attempt to connect.

## Do you have a problem while adding before connecting?

n/a

## Do you have a problem during or after connecting?

n/a

**Comment by jwijenbergh** [comment]
Hi,

Unfortunately, the Linux client cannot work under wsl due to limitations with wsl. We use Network manager which relies heavily on dbus and systems which will not play well with wsl
