### ISSUE TITLE
Official fedora repos tracking issue

### ISSUE THREAD

**Issue by kees-closed** [eduvpn/python-eduvpn-client#526]
I have the following installed from your Copr repo:

```
Name         : eduvpn-client
Version      : 3.1.1
Release      : 1.fc37
Architecture : noarch
Size         : 518 k
Source       : eduvpn_client-3.1.1-1.fc37.src.rpm
Repository   : @System
From repo    : copr:copr.fedorainfracloud.org:group_eduvpn:eduvpn-client
Summary      : client for eduVPN
URL          : https://pypi.python.org/pypi/eduvpn_client
License      : GPLv3+
Description  : eduVPN desktop client
```

But since about 2-3 weeks I get this warning:
![Screenshot from 2023-04-11 08-16-27](https://user-images.githubusercontent.com/6113099/231072974-10fca4de-43ed-4464-815f-ececba72e009.png)

No new update was made available through Copr. Please consider to submit the package directly to the Fedora repositories. Then you automatically get scratch builds if you setup a watch on the upstream project here on GitHub. It also integrates it into the mass rebuilds for compile flag hardening and other benefits. I don't think Copr is the best for something like eduVPN.

**Comment by jwijenbergh** [comment]
> Ah, I see that the whole [installation procedure](https://python-eduvpn-client.readthedocs.io/en/master/installation.html#fedora-36-37) has changed. This is not really how a large project like eduVPN should be handled. There are ways to handle this better through the packaging, i.e. facilitate the change in the package so that users don't need to figure this out after an error.
> 

Hi,

I agree it's not perfect. We moved from copr to our own repositories due to it being our own infrastructure instead of a cloud service, which was the perfect time to do this with such a major version. This means users must manually update, which is far from ideal but it would mean that we have all aspects of the packaging under control


> Are there any objections to package eduVPN for the official repos of Fedora? If not, then I can arrange that.

No objections of course, if that means that updating would still be easy instead of going through multiple layers of potentially slow approval. Are you a fedora maintainer?

Meanwhile let me know if you have issues with the instructions at https://python-eduvpn-client.readthedocs.io/en/master/updating.html#additional-instructions-when-coming-from-3-x

**Comment by jwijenbergh** [comment]
> > No objections of course, if that means that updating would still be easy instead of going through multiple layers of potentially slow approval. Are you a fedora maintainer?
> 
> I'm indeed a package maintainer. The approval is only needed for the initial package to be published. After that it's up to the maintainer to keep everything tidy and up to specs of the latest standards. Integrating with the distribution has a lot of benefits and it makes it user friendly as well. The approach now looks more like a Windows method nerd_face

That sounds good :)

Do you want to kickstart the review process in official repos? 

Spec files:

eduvpn-common lib that we use: https://git.sr.ht/~jwijenbergh/python3-eduvpn-common.rpm/tree/main/item/SPECS/python3-eduvpn-common.spec
Linux client: https://git.sr.ht/~jwijenbergh/python3-eduvpn-common.rpm/tree/main/item/SPECS/python3-eduvpn-common.spec

The only problem I can see is that maybe the eduvpn-common lib is a bit unconventional as it builds a go and python component in one package, the go component uses vendored go dependencies

**Comment by jwijenbergh** [comment]
> > Do you want to kickstart the review process for official repos?
> 
> I will! And also look for a sponsor to review the spec files. I'll make some time for this in the weekend. I don't have experience yet with Go packaging and didn't do much with Python packages. So I have to read up on the maintainer docs for that.

Thanks! Let me know how I can help
