### ISSUE TITLE
Fedora 38 RPM packages

### ISSUE THREAD

**Issue by martijnkruiten** [eduvpn/python-eduvpn-client#527]
Fedora 38 is set to be [released](https://fedorapeople.org/groups/schedule/f-38/f-38-devel-tasks.html) in 4 days and there is no repository with RPM packages for it yet. This might prevent users from updating their OS, unless they manually edit the repo file to point to the f37 release.

**Comment by jwijenbergh** [comment]
Hi Martijn, thanks for the issue. I am aware. I am aiming to release a new hotfix version next week together with fedora 38 packages
