### ISSUE TITLE
bug on profile selection

### ISSUE THREAD

**Issue by schwzr** [eduvpn/python-eduvpn-client#529]
After the installation of version 4.1.0 after a connection attempt (which connects to the requested profile) always the first profile is selected in the selection box. 

https://user-images.githubusercontent.com/5512013/233148618-69e37951-8436-4fd0-926a-8a58d15834ef.mp4

If we want to connect to the first profile in the list, the last selected profile will be used, not the first one in the list.

# Installation

How did you install the eduVPN/Let's Connect! client?

Via the official debian/ubuntu apt repository.

# Version

4.1.0

What version of the client you are running? Try your package manager or otherwise `eduvpn-gui -v` or `letsconnect-gui -v`.

Double check that you are running the latest version, see [the releases page](https://github.com/eduvpn/python-eduvpn-client/releases) if a new version is available.

# Check if your issue is in the known issues list

The known issues list is available here: <https://python-eduvpn-client.readthedocs.io/en/latest/knownissues.html>

No, this issue is not in the known issues list.

# OS/Distribution

Ubuntu 22.04 LTS

What operating system/distribution and version you are running?

# Logs

Not appropriate (no log entries since the installation of the new version).

## Do you have a problem while adding before connecting?

eduVPN/Let's Connect! will print out information to the console while running. Please try running `eduvpn-gui -d` or `eduvpn-cli -d` (or `letsconnect-cli -d`, `letsconnect-gui -d` for Let's Connect!) in a console. Note the `-d` flag here for verbose/debug logging. The log file is also located at `~/.config/eduvpn/log` for eduVPN and `~/.config/letsconnect/log` for Let's Connect!.

## Do you have a problem during or after connecting?

Please examine the eduVPN/Let's Connect! for errors or messages while connecting. Note that the actual VPN connection management is not done by eduVPN, but by network management tool bundeled with your OS named NetworkManager. You can examine the NetworkManager logs with `$ sudo journalctl -u NetworkManager`.

**Comment by trimbonz** [comment]
This behaviour was also observed with eduvpn-gui on Fedora 37

**Comment by jwijenbergh** [comment]
No clue how I didn't catch that before the release. I got a fix and will make new builds today. Thanks for the great issue!

**Comment by jwijenbergh** [comment]
some more info: Only the UI does not update, the profile does get switched. To get the current profile for now, run `eduvpn-cli status`

**Comment by rzo1** [comment]
Thanks for the quick fix via https://github.com/eduvpn/python-eduvpn-client/commit/456603cc3d8cb3eef032ab86305f4a491b0e3e5d @jwijenbergh !!

**Comment by jwijenbergh** [comment]
Fedora packages are up, debian packages should be up shortly too. I will try to have some more pre-releases/test builds for other people to try in the future :smile:

**Comment by jwijenbergh** [comment]
Deb packages also online. Updating for fedora and debian is just a dnf update and apt update, updating for pip: `pip install eduvpn-client -U`
