### ISSUE TITLE
Support for Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by psclkllr** [eduvpn/python-eduvpn-client#530]
Hello, would it also be possible to provide a version for Ubuntu 20.04 LTS? In the technical sector we depend on software that ist just working under Ubuntu 20.04 LTS. Therefore I installed this Ubuntu version on my computer and currently I'm not able to connect my computer with the eduvpn-client.

**Comment by jwijenbergh** [comment]
Hi!

Providing builds for 20.04 is possible but more difficult to outdated packages, e.g. the go version. I will see if I can provide builds as there have been multiple reports about this.

For now you can also use pip: https://python-eduvpn-client.readthedocs.io/en/master/installation.html#pip-installation

**Comment by schwzr** [comment]
Hi!

We have students that also request the Ubuntu 20.04 debian package. I tested version 4.1.1 on ubuntu 20.04 via pip and it works flawlessly :-)

**Comment by llguo95** [comment]
I get the following error when trying to run `pip install "eduvpn-client[gui]"`:

`
Requirement already satisfied: eduvpn-client[gui] in ./miniconda3/lib/python3.10/site-packages (4.1.1)
Requirement already satisfied: eduvpn-common==1.1.0 in ./miniconda3/lib/python3.10/site-packages (from eduvpn-client[gui]) (1.1.0)
Requirement already satisfied: wheel in ./miniconda3/lib/python3.10/site-packages (from eduvpn-client[gui]) (0.38.4)
Collecting dbus-python
  Using cached dbus-python-1.3.2.tar.gz (605 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pygobject
  Using cached PyGObject-3.44.1.tar.gz (720 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [43 lines of output]
      Collecting setuptools
        Using cached setuptools-67.7.2-py3-none-any.whl (1.1 MB)
      Collecting wheel
        Using cached wheel-0.40.0-py3-none-any.whl (64 kB)
      Collecting pycairo
        Using cached pycairo-1.23.0.tar.gz (344 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Installing backend dependencies: started
        Installing backend dependencies: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Building wheels for collected packages: pycairo
        Building wheel for pycairo (pyproject.toml): started
        Building wheel for pycairo (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
      
        × Building wheel for pycairo (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [15 lines of output]
            running bdist_wheel
            running build
            running build_py
            creating build
            creating build/lib.linux-x86_64-cpython-310
            creating build/lib.linux-x86_64-cpython-310/cairo
            copying cairo/__init__.py -> build/lib.linux-x86_64-cpython-310/cairo
            copying cairo/__init__.pyi -> build/lib.linux-x86_64-cpython-310/cairo
            copying cairo/py.typed -> build/lib.linux-x86_64-cpython-310/cairo
            running build_ext
            Package cairo was not found in the pkg-config search path.
            Perhaps you should add the directory containing `cairo.pc'
            to the PKG_CONFIG_PATH environment variable
            No package 'cairo' found
            Command '['pkg-config', '--print-errors', '--exists', 'cairo >= 1.15.10']' returned non-zero exit status 1.
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for pycairo
      Failed to build pycairo
      ERROR: Could not build wheels for pycairo, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.
`

**Comment by jwijenbergh** [comment]
> I get the following error when trying to run `pip install "eduvpn-client[gui]"`:
> 
> ```
> Requirement already satisfied: eduvpn-client[gui] in ./miniconda3/lib/python3.10/site-packages (4.1.1)
> Requirement already satisfied: eduvpn-common==1.1.0 in ./miniconda3/lib/python3.10/site-packages (from eduvpn-client[gui]) (1.1.0)
> Requirement already satisfied: wheel in ./miniconda3/lib/python3.10/site-packages (from eduvpn-client[gui]) (0.38.4)
> Collecting dbus-python
>   Using cached dbus-python-1.3.2.tar.gz (605 kB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... done
>   Preparing metadata (pyproject.toml) ... done
> Collecting pygobject
>   Using cached PyGObject-3.44.1.tar.gz (720 kB)
>   Installing build dependencies ... error
>   error: subprocess-exited-with-error
>   
>   × pip subprocess to install build dependencies did not run successfully.
>   │ exit code: 1
>   ╰─> [43 lines of output]
>       Collecting setuptools
>         Using cached setuptools-67.7.2-py3-none-any.whl (1.1 MB)
>       Collecting wheel
>         Using cached wheel-0.40.0-py3-none-any.whl (64 kB)
>       Collecting pycairo
>         Using cached pycairo-1.23.0.tar.gz (344 kB)
>         Installing build dependencies: started
>         Installing build dependencies: finished with status 'done'
>         Getting requirements to build wheel: started
>         Getting requirements to build wheel: finished with status 'done'
>         Installing backend dependencies: started
>         Installing backend dependencies: finished with status 'done'
>         Preparing metadata (pyproject.toml): started
>         Preparing metadata (pyproject.toml): finished with status 'done'
>       Building wheels for collected packages: pycairo
>         Building wheel for pycairo (pyproject.toml): started
>         Building wheel for pycairo (pyproject.toml): finished with status 'error'
>         error: subprocess-exited-with-error
>       
>         × Building wheel for pycairo (pyproject.toml) did not run successfully.
>         │ exit code: 1
>         ╰─> [15 lines of output]
>             running bdist_wheel
>             running build
>             running build_py
>             creating build
>             creating build/lib.linux-x86_64-cpython-310
>             creating build/lib.linux-x86_64-cpython-310/cairo
>             copying cairo/__init__.py -> build/lib.linux-x86_64-cpython-310/cairo
>             copying cairo/__init__.pyi -> build/lib.linux-x86_64-cpython-310/cairo
>             copying cairo/py.typed -> build/lib.linux-x86_64-cpython-310/cairo
>             running build_ext
>             Package cairo was not found in the pkg-config search path.
>             Perhaps you should add the directory containing `cairo.pc'
>             to the PKG_CONFIG_PATH environment variable
>             No package 'cairo' found
>             Command '['pkg-config', '--print-errors', '--exists', 'cairo >= 1.15.10']' returned non-zero exit status 1.
>             [end of output]
>       
>         note: This error originates from a subprocess, and is likely not a problem with pip.
>         ERROR: Failed building wheel for pycairo
>       Failed to build pycairo
>       ERROR: Could not build wheels for pycairo, which is required to install pyproject.toml-based projects
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × pip subprocess to install build dependencies did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> ```

did you install all the dependencies listed here: https://python-eduvpn-client.readthedocs.io/en/master/installation.html#dependencies

if so and it still doesnt work, try `sudo apt install cairo`

**Comment by llguo95** [comment]
I have installed the dependencies. When I attempt to `sudo apt install cairo`, it throws the `Unable to locate package` error.

**Comment by jwijenbergh** [comment]
Apologies, the command is `sudo apt-get install libcairo2-dev`. If that works I will add it to the docs

**Comment by jwijenbergh** [comment]
> That worked. Running `pip install "eduvpn-client[gui]"` no longer throws an error. However, when I now try to run `eduvpn-gui`, I get:
> 
> ```
> ImportError: /lib/x86_64-linux-gnu/libgirepository-1.0.so.1: undefined symbol: ffi_type_uint32, version LIBFFI_BASE_7.0
> ```

Is this a fresh ubuntu 22.04 desktop install? Anything changed? I cannot reproduce this, nor could I reproduce the missing cairo error.

Try to reinstall gobject:

```bash
sudo apt-get --reinstall install gobject-introspection libgirepository1.0-dev
```

**Comment by llguo95** [comment]
I'm using a fresh Ubuntu 20.04 LTS desktop install. Reinstalling `gobject` doesn't seem to work; I still get the same `ImportError` as in my previous message upon executing `eduvpn-gui`.

**Comment by jwijenbergh** [comment]
Support for the last 3 targets makes sense to me and we support older versions through pip

**Comment by jwijenbergh** [comment]
@schwzr @llguo95 official support is now added, pip should no longer be needed for ubuntu 20.04 https://python-eduvpn-client.readthedocs.io/en/latest/installation.html#ubuntu-20-04
