### ISSUE TITLE
Cant install the client on Linux Mint 21.1 Cinnamon

### ISSUE THREAD

**Issue by KBit92** [eduvpn/python-eduvpn-client#535]
# Installation

I tried to install the client via the instructions, but there are two main errors when i try to install in the last step.

# OS/Distribution

Linux Mint 21.1 Cinnamon

# Logs
`                                                                                            
E: Das Depot »https://app.eduvpn.org/linux/v4/deb vera Release« enthält keine Release-Datei.
N: Eine Aktualisierung von solch einem Depot kann nicht auf eine sichere Art durchgeführt werden, daher ist es standardmäßig deaktiviert.
N: Weitere Details zur Erzeugung von Paketdepots sowie zu deren Benutzerkonfiguration finden Sie in der Handbuchseite apt-secure(8).
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
E: Paket eduvpn-client kann nicht gefunden werden.
`

**Comment by jwijenbergh** [comment]
Linux mint is not an official build target, please follow https://python-eduvpn-client.readthedocs.io/en/master/installation.html#pip-installation

**Comment by irm-codebase** [comment]
I am also running into this issue, @jwijenbergh 
Linux Mint is running on Ubuntu 22.04, which is supported. It seems like the issue is just a missing Release file.

I will follow the pip method for now, hopefully this is corrected soon.

Here's the output:
```$ sudo apt update
Err:10 https://app.eduvpn.org/linux/v4/deb victoria Release
  404  Not Found [IP: 130.225.242.245 443]
Reading package lists... Done
E: The repository 'https://app.eduvpn.org/linux/v4/deb victoria Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by jwijenbergh** [comment]
> I am also running into this issue, @jwijenbergh Linux Mint is running on Ubuntu 22.04, which is supported. It seems like the issue is just a missing Release file.
> 
> I will follow the pip method for now, hopefully this is corrected soon.
> 
> Here's the output:
> 
> ```
> $ sudo apt update
> Err:10 https://app.eduvpn.org/linux/v4/deb victoria Release
>   404  Not Found [IP: ---------------------------]
> Reading package lists... Done
> E: The repository 'https://app.eduvpn.org/linux/v4/deb victoria Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> ```

Thanks I am looking at it. So many distributions, so many things to support :laughing:

**Comment by jwijenbergh** [comment]
Please try https://python-eduvpn-client.readthedocs.io/en/latest/installation.html#linux-mint-21-x

This worked for me in a linux mint 21.2 VM. Splitting the docs per codename/distro version should hopefully avoid confusion. Linux mint is just aliased to ubuntu 22.04 now

**Comment by irm-codebase** [comment]
Can confirm: works like a charm. Thank you @jwijenbergh!
