### ISSUE TITLE
Manjaro Linux install of eduvpn by package manager works smoothly, but the gui does not launch

### ISSUE THREAD

**Issue by HannoSpreeuw** [eduvpn/python-eduvpn-client#536]
# Installation

`yay -S python-eduvpn-client`
gives a smooth install

# Version

`eduvpn-gui -v` gives `eduVPN client version 4.1.1`

# OS/Distribution

Manjaro Linux (23.0.0)

## Do you have a problem while adding before connecting?

`eduvpn-gui` gives
```
...
File "/usr/lib/python3.11/site-packages/eduvpn/ui/ui.py", line 149, in setup
    self.info_version.set_text(f"{__version__}")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'set_text'
```

This used to work until relatively recently.

**Comment by jwijenbergh** [comment]
Hmmm do you perhaps have multiple versions installed, e.g. one through pip?

**Comment by HannoSpreeuw** [comment]
Indeed! The problem, however, persisted after removing these installs.

On my pc I have the same OS as on my laptop, but I was able to fix the problem on my pc, by a reinstall, which required taking a few hurdles.
Unfortunately the same steps did not suffice for my laptop.

**Comment by jwijenbergh** [comment]
could you maybe do a `sudo find / -iname "*mainwindow.ui" 2>/dev/null`

and post the results? Maybe the UI file it's trying to load is still from an older version?

**Comment by HannoSpreeuw** [comment]
That yielded this:
```
/home/hanno/.local/share/eduvpn/builder/mainwindow.ui
/usr/share/doc/qt/examples/nfc/ndefeditor/mainwindow.ui
/usr/share/doc/qt/examples/nfc/annotatedurl/mainwindow.ui
/usr/share/doc/qt/examples/dbus/chat/chatmainwindow.ui
/usr/share/doc/qt/examples/widgets/tools/undo/mainwindow.ui
/usr/share/doc/qt/examples/widgets/itemviews/editabletreemodel/mainwindow.ui
/usr/share/doc/qt/examples/widgets/widgets/stylesheet/mainwindow.ui
/usr/share/doc/qt/examples/sensors/sensorgestures/mainwindow.ui
/usr/share/doc/qt/examples/activeqt/mediaplayer/mainwindow.ui
/usr/share/doc/qt/examples/serialbus/can/mainwindow.ui
/usr/share/doc/qt/examples/serialbus/modbus/master/mainwindow.ui
/usr/share/doc/qt/examples/serialbus/modbus/slave/mainwindow.ui
/usr/share/doc/qt/examples/pdfwidgets/pdfviewer/mainwindow.ui
/usr/share/doc/qt/examples/scxml/mediaplayer-common/mainwindow.ui
/usr/share/doc/qt/examples/scxml/pinball/mainwindow.ui
/usr/share/doc/qt/examples/scxml/calculator-widgets/mainwindow.ui
/usr/share/doc/qt/examples/xmlpatterns/filetree/forms/mainwindow.ui
/usr/share/doc/qt/examples/webenginewidgets/cookiebrowser/mainwindow.ui
/usr/share/doc/qt/examples/webenginewidgets/markdowneditor/mainwindow.ui
/usr/share/doc/qt/examples/webenginewidgets/stylesheetbrowser/mainwindow.ui
/usr/share/doc/qt/examples/serialport/terminal/mainwindow.ui
/usr/share/doc/qt/examples/network/secureudpserver/mainwindow.ui
/usr/share/doc/qt/examples/network/secureudpclient/mainwindow.ui
/usr/share/doc/qt/examples/speech/hello_speak/mainwindow.ui
/usr/share/eduvpn/builder/mainwindow.ui
```

**Comment by HannoSpreeuw** [comment]
`/usr/share/eduvpn/builder/mainwindow.ui` is exactly equal to [the file you posted](https://github.com/eduvpn/python-eduvpn-client/blob/4.1.1/share/eduvpn/builder/mainwindow.ui) but `/home/hanno/.local/share/eduvpn/builder/mainwindow.ui` is very much different.

**Comment by HannoSpreeuw** [comment]
However, after modifying `PATH`, i.e. after removing `~/.local` from `PATH`, the error from `eduvpn-gui &` persists.

**Comment by jwijenbergh** [comment]
Could you move `/home/hanno/.local/share/eduvpn/builder/mainwindow.ui` to a new name instead? e.g. `/home/hanno/.local/share/eduvpn/builder/mainwindow_backup.ui` that should work. See the ordering here https://github.com/eduvpn/python-eduvpn-client/blob/fc325e24e3684447be2aa28d3b4934d23bd05044/eduvpn/utils.py#L60-L62

I would advise you to maybe remove or backup the whole `/home/hanno/.local/share/eduvpn` as it looks like a left-over from the pip installation

**Comment by HannoSpreeuw** [comment]
You got it!

This was from a pip installation in a conda py310 environment.
I have not used that environment in a while.
So `pip uninstall "eduvpn-client[gui]"` from my conda base environment nor from my conda py311 environment have apparently removed those files in `~/.local`. Makes sense, since I did not install `eduvpn` from that environment. Duh.

Apparently I have done a `pip install "eduvpn-client[gui]"` on March 6 in my conda py310 environment.

Anyway this fixed it:
```
conda activate py310
pip uninstall "eduvpn-client[gui]"
```
Problem solved, eduvpn works now, thanks for the patience.

**Comment by jwijenbergh** [comment]
No problem (geen probleem), these kinds of things can be really tricky to hunt down. Glad you got it working. If there is any other issue, feel free to make a new issue. Thanks for giving the fixing steps as well as that will help other users.
