### ISSUE TITLE
support MTU configuration in WireGuard configuration file

### ISSUE THREAD

**Issue by fkooman** [eduvpn/python-eduvpn-client#540]
Add support for the `MTU = n` configuration field in WireGuard client configuration files to set the MTU.

This is supported by WireGuard config import with NetworkManager.

**Comment by jwijenbergh** [comment]
Implemented in 596e5afdbc95a2479371774d68b9d2b7a7978447, will be in the next release

**Comment by jwijenbergh** [comment]
Fixed in the latest version
