### ISSUE TITLE
Ubuntu 20.04 LTS: version 4.x available from package manager with unresolvable dependencies

### ISSUE THREAD

**Issue by wmotion** [eduvpn/python-eduvpn-client#541]
# Installation

## Using **synaptic** package to install the eduVPN client. Versions as displayed.

The installation of green-ticked packages is successful:
![Screenshot from 2023-08-29 11-42-47](https://github.com/eduvpn/python-eduvpn-client/assets/21219611/60fe2a35-1c9b-4bfd-a855-f895afe525f2)

In contrast, the installation of **edupvn-client-doc** gives:
![Screenshot from 2023-08-29 11-43-08](https://github.com/eduvpn/python-eduvpn-client/assets/21219611/39e9067d-c6d6-4fa2-9f91-ebd7c32e6054)

# Version

See above.

# Check if your issue is in the known issues list

Not a known issue as of today.

# OS/Distribution

* `uname -a`
  `Linux xxxxxxxx 5.4.0-156-generic #173-Ubuntu SMP Tue Jul 11 07:25:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
* `lsb_release -d`
  `Description:	Ubuntu 20.04.6 LTS`  

_**Ubuntu 20.04 is being maintained until May 2025 included.**_ See https://ubuntu.com/about/release-cycle and the source code of that page:

![image](https://github.com/eduvpn/python-eduvpn-client/assets/21219611/59266042-30e4-4bf4-97be-c32542c43f47)

# Logs

## Do you have a problem while adding before connecting?

The combined stdin and stderr of `eduvpn-gui -d` is:
> A fatal error occurred
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/eduvpn_common/loader.py", line 48, in load_lib
    lib = cdll.LoadLibrary(libfile)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/lib/libeduvpn_common-1.1.0.so)

> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/eduvpn/ui/__main__.py", line 29, in main_loop
    _common = common.EduVPN(*variant_settings, language=country())
  File "/usr/lib/python3/dist-packages/eduvpn_common/main.py", line 54, in __init__
    self.lib = load_lib()
  File "/usr/lib/python3/dist-packages/eduvpn_common/loader.py", line 51, in load_lib
    lib = cdll.LoadLibrary(str(pathlib.Path(__file__).parent / "lib" / libfile))
  File "/usr/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)

> OSError: /usr/lib/python3/dist-packages/eduvpn_common/lib/libeduvpn_common-1.1.0.so: cannot open shared object file: No such file or directory

Consistently, the GUI dialogue displays the last issue with **libeduvpn_common**:
![Screenshot from 2023-08-29 11-44-10](https://github.com/eduvpn/python-eduvpn-client/assets/21219611/dd4e804b-a5db-4e27-bfeb-c73201ca7486)

## Do you have a problem during or after connecting?

n/a

**Comment by wmotion** [comment]
> 20.04 is not supported, did you try the pip package? https://python-eduvpn-client.readthedocs.io/en/master/installation.html#pip-installation

**Evaluation**  
Not exactly long-sighted to withdraw the support for an operating system that is still actively maintained. See https://ubuntu.com/about/release-cycle for information on the applicable timelines. I am up for being future-ready but not so much for being dismissive of the present.

---
**Integration**  
Apparently, though, the package manager believes EduVPN **is** maintained, since today I was offered an update:
![Screenshot from 2023-08-30 06-56-38](https://github.com/eduvpn/python-eduvpn-client/assets/21219611/9d5f453c-f384-40ab-b3d5-aefd1100c36b)
This update is, however, ineffective to fix the error before.

---
**Prospects**
I have not tried the **pip package**. Is a question of trying? The problem signalled above has to do with libraries not found. Which guarantees does the pip package offer in a OS that you do not support? Do you know that the pip package provides them anyhow? How do you suggest to go about the version that is currently installed?  
Thanks for providing additional orientation and information.

**Comment by jwijenbergh** [comment]
> Not exactly long-sighted to withdraw the support for an operating system that is still actively maintained. See https://ubuntu.com/about/release-cycle for information on the applicable timelines (until May 2025 for 20.04 LTS). I am up for being future-ready but not so much for being dismissive of the present.

I am very well aware of the ubuntu release cycle. I was talking what *we* support. But due to popular demand I am now looking at how to support this distro (ubuntu 20.04 and derivatives). This is tricky as the Go version they ship is ancient. I always recommend to update your system anyways but that's besides the point.

> I have not tried the pip package. Is it a question of trying? The problem signalled above has to do with libraries not found.

Well it actually says that the library is compiled with a too new libc dependency. Did you follow the debian 12 instructions manually? Those won't work on an older distro for obvious reasons. The pip version has a chance of working due to being built in containers that try to strive for maximum compatibility.

The other error of the library not being found is a fallback to a different directory because the first one did not work

**Comment by wmotion** [comment]
We are treading water on the following points:

> > Not exactly long-sighted to withdraw the support for an operating system that is still actively maintained. See https://ubuntu.com/about/release-cycle for information on the applicable timelines (until May 2025 for 20.04 LTS). I am up for being future-ready but not so much for being dismissive of the present.
> 
> I am very well aware of the ubuntu release cycle. I was talking about what _we_ support. But due to popular demand I am now looking at how to support this distro (ubuntu 20.04 and derivatives). This is tricky as the Go version they ship is ancient. I always recommend to update your system anyways but that's besides the point. We're already 2 LTS versions newer at this point

* I have opened an issue in the account of EduVPN. I am also talking about what _you_ support or, rather, _do not_ support. Am I perhaps in the wrong repository?
* Updating the distribution release can break a lot of stuff. Once bitten twice shy. Advising to do indiscriminately is dangerous. And this is indeed beside the point.
* The fact that two LTS versions are newer than 20.04 simply implies that there are _three_ LTS versions to take care of. I am restricting myself to the status of 'LTS standard support for Ubuntu Main'.

> > I have not tried the pip package. Is it a question of trying? The problem signalled above has to do with libraries not found.
> 
> Well it actually says that the library is compiled with a too new libc dependency. Did you follow the debian 12 instructions manually? Those won't work on an older distro for obvious reasons. The pip version has a chance of working due to being built in containers that try to strive for maximum compatibility.
> The other error of the library not being found is a fallback to a different directory because the first one did not work

* I have followed precisely the procedure explained at the top of this issue. Does this referring to Debian 12 point to anything I should consider?

**Comment by wmotion** [comment]
> I have added support for ubuntu 20.04 and derivatives. See the installation doc https://python-eduvpn-client.readthedocs.io/en/latest/installation.html#ubuntu-20-04

* I have removed the installation that prompted the issue using synaptic, the package management interface. The expected result is as displayed:
![image](https://github.com/eduvpn/python-eduvpn-client/assets/21219611/e485668f-44eb-43b9-a20b-c0073804a89d)

* I have then followed the installation script newly provided at https://python-eduvpn-client.readthedocs.io/en/latest/installation.html#ubuntu-20-04

* The net outcome is shown below using synaptic again for the sake of convenience:
![image](https://github.com/eduvpn/python-eduvpn-client/assets/21219611/2240eac7-1a4e-4dc8-9e51-d08f66b7ee4f)

* I can launch the EduVPN client, the GUI, and connect to the VPN of two universities.  

Therefore, the new instructions for 20.04 LTS in the documentation resolve the issue. One may want to revise this issue to understand why the automatic installation with synaptic did not produce a working result.

**Comment by jwijenbergh** [comment]
> * I have opened an issue in the account of EduVPN. I am also talking about what _you_ support or, rather, _do not_ support. Am I perhaps in the wrong repository?
> 
> * Updating the distribution release can break a lot of stuff. Once bitten twice shy. Advising to do that indiscriminately is dangerous. And this is indeed beside the point.
> 
> * The fact that two LTS versions are newer than 20.04 simply implies that now there are _three_ LTS versions to take care of. I am restricting myself to the status of 'LTS standard support for Ubuntu Main'.

I am not sure I follow hopefully I didn't come across as rude here. I was just stating the fact what we currently support and why we do (because the latest 2 LTS releases are IMO a good target). But due to popular demand I relaxed this requirement.

> I have followed precisely the procedure explained at the top of this issue. I think I followed the template for an issue closely enough. Does this referring to Debian 12 point to anything I should consider?

Your issue was perfectly fine, as I mentioned in the docs if your target is not supported you can always ask for it and we will see how difficult it is. Note that I had to do some hacks to support ubuntu 20.04, it's not very trivial to just add a build target if it's an older release

> I have removed the installation that prompted the issue using synaptic, the package management interface. The expected result is as displayed:

This is certainly a weird issue and we can move it to a new issue if we want. But I am just wondering how the synaptic prompt got there in the first place. Could you let me know what the instructions were you followed before you made the issue? Thanks.

> Therefore, the new instructions for 20.04 LTS in the documentation resolve the issue. One may want to revise this issue to understand why the automatic installation with synaptic did not produce a working result.

Great to hear that, if there's any other issues let me/us know in this repository

**Comment by wmotion** [comment]
> This is certainly a weird issue and we can move it to a new issue if we want. But I am just wondering how the synaptic prompt (with debian 12 (?) instructions) got there in the first place. Could you let me know what the instructions were you followed before you made the issue? Thanks.

I could replay yesterday the steps above in a laptop with Ubuntu 20.04 LTS and **EduVPN 3.1.01**. 

I had installed that version following the script lines available from the web-based documentation. I cannot recall which ones were available at the time (2021?) but I do not see a motive to have used Debian instructions if Ubuntu instructions had been available. 

Regardless, that version had stopped working because the process of connecting to an accredited server hanged indefinitely. I linked this incident to version 4 being available, an event that the package manager apparently did not not capture. This antecedent applies to the report above too.

In the situation above, I first followed the removal actions indicated in https://python-eduvpn-client.readthedocs.io/en/master/updating.html?highlight=ubuntu%2020.04#debian-and-ubuntu-both-x86-64. Since assistance was promised only for Ubuntu >= 22  --- **and still is, please fix**
![image](https://github.com/eduvpn/python-eduvpn-client/assets/21219611/cf95cf73-72f8-4c00-a99d-ecbaba2a2bef)
--- I then resorted to Synaptic to avoid improvisation. The outcomes are described above.

In yesterday's laptop installation, I have used the script lines newly provided in the documentation and they worked again. Additionally, today the software updater has recognized that a new minor version of eduvpn was available in the repository (4.1.3 with eduvpn-common 1.1.2) and has updated that. This updating too is an improvement with respect to 3.x.

**Comment by jwijenbergh** [comment]
> I could replay yesterday the steps above in a laptop with Ubuntu 20.04 LTS and EduVPN 3.1.01.

What does `lsb_release -cs` return on that laptop?

> I cannot recall which ones were available at the time (2021?) but I do not see a motive to have used Debian instructions if Ubuntu instructions had been available.

In 2021 we had a different repository. So there was unfortunately some manual steps involved for the 4.x upgrade

> In the situation above, I first followed the removal actions indicated in https://python-eduvpn-client.readthedocs.io/en/master/updating.html?highlight=ubuntu%2020.04#debian-and-ubuntu-both-x86-64. Since assistance was promised only for Ubuntu >= 22 --- and still is, please fix

I will update this thanks! But note that these instructions are only really for people that had the old repository defined.

> Additionally, today the software updater has recognized that a new minor version of eduvpn was available in the repository (4.1.3 with eduvpn-common 1.1.2) and has updated that. This updating too is an improvement with respect to 3.x.

Great! Hopefully it works well, if there are any issues let us know

Anyways is there still an issue here? Something I can do?

**Comment by wmotion** [comment]
> Anyways is there still an issue here? Something I can do?

The originating issue has been resolved with https://github.com/eduvpn/python-eduvpn-client/issues/541#issuecomment-1702495280, with thanks. For the rest, I have addressed questions that I received. In that regard, the output of `lsb_release -cs` on the laptop is `focal`, the codename of 20.04. I hope this helps.

**Comment by sebastian-luna-valero** [comment]
Hi,

Today I followed instructions in: https://python-eduvpn-client.readthedocs.io/en/master/installation.html#ubuntu-20-04

Still I get:

```bash
$ eduvpn-gui 
A fatal error occurred
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/eduvpn_common/loader.py", line 48, in load_lib
    lib = cdll.LoadLibrary(libfile)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /lib/libeduvpn_common-1.1.2.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/eduvpn/ui/__main__.py", line 29, in main_loop
    _common = common.EduVPN(*variant_settings, language=country())
  File "/usr/lib/python3/dist-packages/eduvpn_common/main.py", line 54, in __init__
    self.lib = load_lib()
  File "/usr/lib/python3/dist-packages/eduvpn_common/loader.py", line 51, in load_lib
    lib = cdll.LoadLibrary(str(pathlib.Path(__file__).parent / "lib" / libfile))
  File "/usr/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/python3/dist-packages/eduvpn_common/lib/libeduvpn_common-1.1.2.so: cannot open shared object file: No such file or directory
```

With:

```bash
ii  eduvpn-client                                               4.1.3-1+ubuntu+22.04+1                all          VPN client for educational networks
ii  eduvpn-client-data                                          4.1.3-1+ubuntu+22.04+1                all          VPN client for educational networks (data files)
ii  libeduvpn-common                                            1.1.2-1+ubuntu+22.04+1                amd64        EduVPN common Go library
ii  python3-eduvpn-client                                       4.1.3-1+ubuntu+22.04+1                all          eduVPN client (Python 3)
ii  python3-eduvpn-common                                       1.1.2-1+ubuntu+22.04+1                all          Python wrapper for the eduVPN common library
```

```bash
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS (fossa-charmander-14 X60)
Release:	20.04
Codename:	focal
```

Could you please help?
Thanks,
Sebastian

**Comment by jwijenbergh** [comment]
Please give me the output of:

```
/etc/apt/sources.list.d/eduvpn-v4.list
```

**Comment by sebastian-luna-valero** [comment]
Here it is:

```bash
deb [arch=amd64 signed-by=/usr/share/keyrings/eduvpn-v4.gpg] https://app.eduvpn.org/linux/v4/deb/ jammy main
```

Sorry, indeed it should be `focal` instead of `jammy`. I have now replaced it, re-installed it and it works. I must have copy/pasted the wrong info from the page. My apologies for the noise.

**Comment by jwijenbergh** [comment]
No worries! It can be quite confusing, maybe a script here helps
