### ISSUE TITLE
Improve UX for failover: both for end-users and server admins

### ISSUE THREAD

**Issue by ghost** [eduvpn/python-eduvpn-client#543]
Currently the app shows it is doing "online detection" and switching to another protocol. It would be better to not bother the user with this and simply do it while the app remains in the 'connecting' state without informing the user. 

Information about the used protocol remains available in the "Connection Info" pull-out.

**Comment by jwijenbergh** [comment]
Regarding: https://codeberg.org/eduVPN/documentation/issues/8

If the clients shows the prefer TCP or the full failover, we might need to show some more explanation in the client somewhere such that server administrators can easily tell what went wrong. The tricky part is not bothering the user about this too much

**Comment by jwijenbergh** [comment]
Should be better in the latest version
