### ISSUE TITLE
Debian 12: gui not starting due to python error

### ISSUE THREAD

**Issue by gothicVI** [eduvpn/python-eduvpn-client#548]
# Installation

How did you install the eduVPN/Let's Connect! client?

https://python-eduvpn-client.readthedocs.io/en/master/installation.html#debian-12

# Version

What version of the client you are running? Try your package manager or otherwise `eduvpn-gui -v` or `letsconnect-gui -v`.

Double check that you are running the latest version, see [the releases page](https://github.com/eduvpn/python-eduvpn-client/releases) if a new version is available.

```bash
$ eduvpn-gui -v
eduVPN GUI version: 4.1.3 with eduvpn-common version: 1.1.2
```

# Check if your issue is in the known issues list

The known issues list is available here: <https://python-eduvpn-client.readthedocs.io/en/latest/knownissues.html>

No.

# OS/Distribution

What operating system/distribution and version you are running?

Debian 12

# Logs

## Do you have a problem while adding before connecting?

eduVPN/Let's Connect! will print out information to the console while running. Please try running `eduvpn-gui -d` or `eduvpn-cli -d` (or `letsconnect-cli -d`, `letsconnect-gui -d` for Let's Connect!) in a console. Note the `-d` flag here for verbose/debug logging. The log file is also located at `~/.config/eduvpn/log` for eduVPN and `~/.config/letsconnect/log` for Let's Connect!.

Yes. The gui does not start. When trying to start it via the CLI I get a python error:

```bash
$ eduvpn-gui 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/eduvpn/ui/app.py", line 72, in do_activate
    self.window = EduVpnGtkWindow(application=self)  # type: ignore
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/eduvpn/ui/ui.py", line 95, in __new__
    window.setup(builder, application)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/eduvpn/ui/ui.py", line 165, in setup
    self.common_version.set_text(f"{commonver}")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'set_text'

$ python3 --version
Python 3.11.2
```

## Do you have a problem during or after connecting?

Please examine the eduVPN/Let's Connect! for errors or messages while connecting. Note that the actual VPN connection management is not done by eduVPN, but by network management tool bundled with your OS named NetworkManager. You can examine the NetworkManager logs with `$ sudo journalctl -u NetworkManager`.

No. Connecting via eduvpn-cli works fine.

**Comment by jwijenbergh** [comment]
I am guessing you had the pip version installed previously or still have. Please run:

```bash
pip uninstall "eduvpn-client[gui]"
```

If that doesn't work see if there are files in ```~/.local/share/eduvpn```

**Comment by gothicVI** [comment]
Hi @jwijenbergh 

thanks for the reply. There are no pip installations for the user. There is, however, `/usr/lib/python3/dist-packages/eduvpn` and `/usr/lib/python3/dist-packages/eduvpn_client-4.1.3.egg-info` which were never installed by me given this would require a root pip installation which is a big no-no in the first place ;)
Could these be from the proper installation or from the previous Debian 11 installation - the machine has been upgraded recently.
There are files in the mentioned directory:
```bash
$ ls ~/.local/share/eduvpn/
builder  images  country_codes.json  eduvpn.png
```
Can they be deleted or does this remove the saved config that is used by the cli version?

**Comment by jwijenbergh** [comment]
@gothicVI The files you see in `~/.local/share/eduvpn` are probably leftover files from a previous pip installation. Could you try to move this directory e.g. to `~/.local/share/eduvpn2` and launch the client again?

**Comment by gothicVI** [comment]
That did the trick.
Thanks a lot!

**Comment by jwijenbergh** [comment]
> That did the trick. Thanks a lot!

Thanks for making an issue and glad it worked. I made it a section in the `Known Issues` doc: https://python-eduvpn-client.readthedocs.io/en/latest/knownissues.html#gui-does-not-launch-due-to-getting-attribute-errors
