### ISSUE TITLE
EduVPN as a flatpak/AppImage

### ISSUE THREAD

**Issue by knyazer** [eduvpn/python-eduvpn-client#556]
I think most of the Linux users could agree that they prefer installation of apps with Flatpak. Besides, another really common approach for 'isolated' app installation is using an AppImage. In some cases, for example for read-only systems, installing apps via package manages is nearly prohibited, thus limiting the ability to install EduVPN on such systems.

Of course, there is enormous discussion to have about whether Flatpaks/AppImages/packages are better than one another, but I reckon providing the possibility to install the app in a preferred way would be awesome.

I am not precisely sure how hard making either/both of these installation variants would be, but I would really appreciate their presence. Besides, I am up to contributing with GH Action scripts to automatically pack the EduVPN into the AppImage, if you are ok with that.

**Comment by jwijenbergh** [comment]
There was some progress making flatpaks in #537, I managed to make a flatpak work with the help of @kees-closed, but I unfortunately do not have the time to support this.

Note that isolation for VPN apps is almost useless, so unfortunately the resulting flatpak did need a lot of permissions. I have not looked at appimages

**Comment by jwijenbergh** [comment]
Closing due to inactivitiy
