### ISSUE TITLE
The "Connected" button breaks often

### ISSUE THREAD

**Issue by fkooman** [eduvpn/python-eduvpn-client#56]
It happens almost every time you set a connection to enabled, or disable it, that it spews errors. Just using it a few times to connect/disconnect will trigger it.

**Comment by fkooman** [comment]
Also, sometimes after connecting successfully it will not switch to "on", making it impossible to disconnect. Trying a few times on this disabled button will make eduVPN client hang with "eduVPN Configuration Manager is not responding".

**Comment by fkooman** [comment]
This is on Debian with your DEB package.

**Comment by gijzelaerr** [comment]
yeah the signal handling of network manager events is not working properly.

**Comment by gijzelaerr** [comment]
related to #36

**Comment by gijzelaerr** [comment]
an attempt to make this work better is in the nmfork branch https://github.com/eduvpn/python-eduvpn-client/tree/nmfork

**Comment by gijzelaerr** [comment]
fixed per https://github.com/eduvpn/python-eduvpn-client/commit/aaac20bdaa7ec3ee91e7599376047fb09f70748a
