### ISSUE TITLE
Request for ARM64 Support

### ISSUE THREAD

**Issue by ay-kay** [eduvpn/python-eduvpn-client#561]
I am writing to enquire about your plans to provide ARM64 builds of the eduVPN client.

It would be greatly appreciated if ARM64 support could be considered, especially in the form of Debian packages or pip-installable versions. Currently, installation via pip fails since the `eduvpn-common` dependency seems to be available for x86 systems only when installed via pip.

Given the growing use of ARM64 in various environments, the availability of the eduVPN client on ARM64 would be highly valuable.

**Comment by jwijenbergh** [comment]
Thanks for making an issue. I have been meaning to try this for a while. I have just cross compiled an arm package for eduvpn-common to pip. Could you try it?

**Comment by ay-kay** [comment]
Thank you for your quick action on this issue.

I have successfully installed the `eduvpn-client` along with the newly cross-compiled `eduvpn-common` package for ARM using the regular pip installation method. The installation process went smoothly and I can confirm that the eduVPN client is now working correctly on my ARM64 system. Once again, many thanks!

**Comment by jwijenbergh** [comment]
Wow very nice! I will document that works. No worries

**Comment by miekg** [comment]
Adding a second request for arm64 packages.

(Now that Asahi Linux works really well on Macs, more people might want arm64. Note that Asahi Linux is based on fedora)
