### ISSUE TITLE
Use client without network manager

### ISSUE THREAD

**Issue by nezos** [eduvpn/python-eduvpn-client#562]
It would be nice if network manager was not necessary for using the client.

**Comment by jwijenbergh** [comment]
This has been requested a few times. The problem with having integration without NetworkManager, the client would need to have additional privileges to set up the connection. Maybe it would be fine to have the CLI able to work without NetworkManager by just downloading configs, see #547. What do you think?

**Comment by nezos** [comment]
Yes, if this is possible, would do as well. I guess it is still WIP.
