### ISSUE TITLE
Support for opensuse

### ISSUE THREAD

**Issue by thomasschaeferm** [eduvpn/python-eduvpn-client#564]
If your target is not supported you can make an issue on the [GitHub](https://github.com/eduvpn/python-eduvpn-client).

Here is the issue.

**Comment by jwijenbergh** [comment]
are you using leap 15.5 or tumbleweed?

**Comment by thomasschaeferm** [comment]
For work I use 15.5. The last(first) time (long ago) the pip installation worked for me. But now I have trouble with it. ( I also have mixed python and pip versions on my notebook).
Since the servers (lrz) provide wg+ovpn the old client doesn't work anymore. The old certificates lifetime run out - so the simple networkmananger connection also fails without new account verification.

**Comment by thomasschaeferm** [comment]
I have not tried eduvpn on tumbleweed yet. I have some devices with tumbleweed for testing, but usually not for serious things.

**Comment by jwijenbergh** [comment]
I tried to package for leap 15.5 but it's not really trivial as the package names are not the same as in fedora and centos and it doesn't have all the packages we need for building. Which error did you get in the pip installation?

>  also have mixed python and pip versions on my notebook

Any reason why?

**Comment by thomasschaeferm** [comment]
The reason is simple. Opensuse 15.5 python is quite old 3.6. For some other reasons ( I cant remember) I needed a newer python version. Is 3.6 still supported by eduvpn? Otherwise I try tumbleweed with 3.11 first. 
Is it reasonable to use venv ?

**Comment by jwijenbergh** [comment]
I actually do not recommend using a venv but using [pipx instead](https://github.com/pypa/pipx). Regarding 3.6, that is indeed quite old, I will have to try it

**Comment by jwijenbergh** [comment]
Works fine on opensuse 15.5 and normal pip:

install deps:
```bash
sudo zypper install python3-pip libnotify libsecret gtk3 python3-gobject python3-pytest gobject-introspection-devel
```

install client
```bash
pip install "eduvpn-client[gui]"
```

make sure to *reboot*, I had to otherwise the client wont start (but my vm was acting funny with dbus problems).

run:
```bash
~/.local/bin/eduvpn-gui
```

**Comment by thomasschaeferm** [comment]
Thanks a lot some things is broken with my machine. I will try another one soon.
```
free(): invalid pointer
Abgebrochen (Speicherabzug geschrieben)
```

**Comment by jwijenbergh** [comment]
> Thanks a lot. Some things are broken with my machine. I will try another one soon.
> 
> ```
> free(): invalid pointer
> Abgebrochen (Speicherabzug geschrieben)
> ```

weird, when does that happen? on startup or?

**Comment by thomasschaeferm** [comment]
tumbleweed: python311 and using pipx works finally

some libs have different names:
```
'python3-gobject' wurde in den Paketnamen nicht gefunden. Fähigkeiten werden durchsucht.
'python311-gobject', welches 'python3-gobject' bietet, ist bereits installiert.
'gtk3' wurde in den Paketnamen nicht gefunden. Fähigkeiten werden durchsucht.
'libgtk-3-0', welches 'gtk3' bietet, ist bereits installiert.
'python3-pytest' wurde in den Paketnamen nicht gefunden. Fähigkeiten werden durchsucht.
'libsecret' wurde in den Paketnamen nicht gefunden. Fähigkeiten werden durchsucht.
'libsecret-1-0', welches 'libsecret' bietet, ist bereits installiert.
'libnotify' wurde in den Paketnamen nicht gefunden. Fähigkeiten werden durchsucht.
'python3-pip' wurde in den Paketnamen nicht gefunden. Fähigkeiten werden durchsucht.
'python311-pip', welches 'python3-pip' bietet, ist bereits installiert.
```
I have had some trouble with "notify" - bad after installation of all packages with "notify" in the name it was solved.

I will do some further attempts on my 15.5 installations later. Now, I know, I have a chance that it works.
By the way wireguard works too, but the lower mtu is a contra point.

**Comment by jwijenbergh** [comment]
> tumbleweed: python311 and using pipx works finally

Great!

> I have had some trouble with "notify" - bad after installation of all packages with "notify" in the name it was solved.

If you have some general hints you can make a docs pr

>  By the way wireguard works too, but the lower mtu is a contra point.

Could you expand on this? Do you mean that the clients set a too low MTU and you notice a performance degradation compared to OpenVPN? Note that we use the MTU that the server has set in the WireGuard config

**Comment by thomasschaeferm** [comment]
After installing opensuse 15.5 from zero it works finally. (my  former installation was quite old, with a lot of distribution updates)

`python3.11 -m pipx install "eduvpn-client[gui]"`

Packages hard to find:  gtk3-devel libnotify-devel

**Comment by jwijenbergh** [comment]
Considering official packages wasn't trivial and the pip packages work, do you think I can close this?

> Packages hard to find: gtk3-devel libnotify-devel

Are those the names on opensuse or are they different?

**Comment by thomasschaeferm** [comment]
You can close it. 
The hardest tasks are: have a clean system, find the right required packages (from opensuse). As long that issue is visible, it may other people help.
