### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by amuhz** [eduvpn/python-eduvpn-client#568]
# Installation :

I've installed the RPM packages from your repositories, by command lines first and after seeing that it doesn't work, i've tested with drakconf.

# Version  : 

2.2.0

# OS/Distribution : 

Mageia 9

# Logs :

![image](https://github.com/eduvpn/python-eduvpn-client/assets/138972690/b95a72a0-fa3d-4354-a0e1-09873e6e4599)

**Comment by jwijenbergh** [comment]
Closed due to inactivity
