### ISSUE TITLE
Error connecting: Could not find source connection.

### ISSUE THREAD

**Issue by TimFaro** [eduvpn/python-eduvpn-client#570]
# Installation

Tried both the installation script provided here https://docs.eduvpn.org/client/linux/installation.html and the manual installation.

# Version

eduVPN CLI version: 4.2.1 with eduvpn-common version: 1.2.0

# Check if your issue is in the known issues list
Same problem was reported in https://github.com/eduvpn/python-eduvpn-client/issues/413 and the documentation also mentions the issue. 

# OS/Distribution

Ubuntu 20.04.6 LTS server connected to via SSH 

# Logs
<details>
<summary>~/.config/eduvpn/log output </summary>

```
(base) ###@###:~$ cat ~/.config/eduvpn/log 
2024-02-12 18:21:30,659 - <function ApplicationModelTransitions.get_previous_servers at 0x7f4c7f556550> - DEBUG - eduvpn.app - app.py:42 - Transition: NO_SERVER, old state: DEREGISTERED
2024-02-12 18:21:30,659 - MainThread - DEBUG - eduvpn.nm - nm.py:791 - calling action with CLI mainloop
2024-02-12 18:21:30,697 - MainThread - DEBUG - eduvpn.nm - nm.py:795 - Quiting main loop, thanks!
2024-02-12 18:21:30,697 - MainThread - DEBUG - eduvpn.nm - nm.py:791 - calling action with CLI mainloop
2024-02-12 18:21:30,700 - <function ApplicationModelTransitions.loading_server at 0x7f4c7f556790> - DEBUG - eduvpn.app - app.py:66 - Transition: LOADING_SERVER, old state: NO_SERVER
2024-02-12 18:21:30,700 - <function ApplicationModelTransitions.chosen_server at 0x7f4c7f556940> - DEBUG - eduvpn.app - app.py:71 - Transition: CHOSEN_SERVER, old state: LOADING_SERVER
2024/02/12 18:21:30 - Go - DEBUG - Getting access token
2024/02/12 18:21:30 - Go - DEBUG - Access token is not expired, returning
2024-02-12 18:21:30,719 - <function ApplicationModelTransitions.authorized at 0x7f4c7f559040> - DEBUG - eduvpn.app - app.py:91 - Transition: AUTHORIZED, old state: CHOSEN_SERVER
2024-02-12 18:21:30,719 - <function ApplicationModelTransitions.parse_request_config at 0x7f4c7f5593a0> - DEBUG - eduvpn.app - app.py:102 - Transition: REQUEST_CONFIG, old state: AUTHORIZED
2024/02/12 18:21:30 - Go - DEBUG - Getting access token
2024/02/12 18:21:30 - Go - DEBUG - Access token is not expired, returning
2024/02/12 18:21:30 - Go - DEBUG - Getting access token
2024/02/12 18:21:30 - Go - DEBUG - Access token is not expired, returning
2024-02-12 18:21:30,766 - <function ApplicationModelTransitions.parse_config at 0x7f4c7f559550> - DEBUG - eduvpn.app - app.py:107 - Transition: DISCONNECTED, old state: REQUEST_CONFIG
2024/02/12 18:21:30 - Go - DEBUG - Running token callback
2024-02-12 18:21:30,771 - connect - DEBUG - eduvpn.app - app.py:345 - Save tokens called
2024-02-12 18:21:30,775 - <function ApplicationModelTransitions.parse_connecting at 0x7f4c7f5599d0> - DEBUG - eduvpn.app - app.py:130 - Transition: CONNECTING, old state: DISCONNECTED
2024-02-12 18:21:30,775 - connect - DEBUG - eduvpn.nm - nm.py:417 - writing ovpn configuration to Network Manager
2024-02-12 18:21:30,776 - connect - DEBUG - eduvpn.nm - nm.py:349 - Writing configuration to /tmp/tmpb8pdj59q/eduVPN.ovpn
2024-02-12 18:21:30,782 - MainThread - DEBUG - eduvpn.nm - nm.py:377 - Updating existing connection with new configuration
2024-02-12 18:21:30,789 - MainThread - DEBUG - eduvpn.nm - nm.py:821 - Connection updated for uuid: 10320d5d-f999-489e-bf4b-67118a2decfa, result: True, remote_con: <NM.RemoteConnection object at 0x7f4c4443d380 (NMRemoteConnection at 0x14aaab0)>
2024-02-12 18:21:30,790 - MainThread - DEBUG - eduvpn.nm - nm.py:599 - activate_connection: <NM.RemoteConnection object at 0x7f4c44436200 (NMRemoteConnection at 0x14aaab0)>
2024-02-12 18:21:30,791 - MainThread - ERROR - eduvpn.nm - nm.py:612 - nm-manager-error-quark: Could not find source connection. (2)
2024-02-12 18:21:30,792 - MainThread - ERROR - /usr/lib/python3/dist-packages/eduvpn/utils.py - utils.py:27 - Unhandled exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/eduvpn/nm.py", line 632, in activate_connection_callback
    signal = self.active_connection.connect("state-changed", changed_state)
AttributeError: 'NoneType' object has no attribute 'connect'
```

</details>

## Do you have a problem while adding before connecting?

No, I could add the server without a problem.

## Do you have a problem during or after connecting?
Yes, when trying to connect to the server, it fails with the message 

```
2024-02-12 18:34:37,613 - MainThread - ERROR - eduvpn.nm - nm.py:612 - nm-manager-error-quark: Could not find source connection. (2)
2024-02-12 18:34:37,614 - MainThread - ERROR - /usr/lib/python3/dist-packages/eduvpn/utils.py - utils.py:27 - Unhandled exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/eduvpn/nm.py", line 632, in activate_connection_callback
    signal = self.active_connection.connect("state-changed", changed_state)
AttributeError: 'NoneType' object has no attribute 'connect'
```
I checked the Docs and GitHub, all say it's because of an unmanaged network device. My device actually was unmanaged, but I fixed it and it's now managed, but the error persists.

```
(base) ###@###:~$ nmcli dev status
DEVICE  TYPE      STATE      CONNECTION 
ens160  ethernet  connected  ens160     
lo      loopback  unmanaged  --    
``` 
```
(base) ###@###:~$ nmcli device show
GENERAL.DEVICE:                         ens160
GENERAL.TYPE:                           ethernet
GENERAL.HWADDR:                         ###
GENERAL.MTU:                            1500
GENERAL.STATE:                          100 (connected)
GENERAL.CONNECTION:                     ens160
GENERAL.CON-PATH:                       /org/freedesktop/NetworkManager/ActiveConnection/1
WIRED-PROPERTIES.CARRIER:               on
IP4.ADDRESS[1]:                         ###
IP4.GATEWAY:                            ###
IP4.ROUTE[1]:                           dst = 0.0.0.0/0, nh = ###, mt = 0
IP4.ROUTE[2]:                           dst = ###/24, nh = 0.0.0.0, mt = 0
IP6.ADDRESS[1]:                         ###
IP6.GATEWAY:                            --
IP6.ROUTE[1]:                           dst = fe80::/64, nh = ::, mt = 256
```

NetworkManager log

```
Feb 12 18:30:40 ### NetworkManager[920]: <info>  [1707762640.6913] audit: op="connection-update" uuid="10320d5d-f999-489e-bf4b-67118a2decfa" name="eduVPN" args="vpn.data" pid=6072 uid=1001 result="success"
Feb 12 18:30:40 ### NetworkManager[920]: <info>  [1707762640.6932] audit: op="connection-activate" uuid="10320d5d-f999-489e-bf4b-67118a2decfa" name="eduVPN" pid=6072 uid=1001 result="fail" reason="Could not find source connection."
```

**Comment by jwijenbergh** [comment]
Thanks, did you reboot after setting the device to managed?

**Comment by TimFaro** [comment]
> Thanks, did you reboot after setting the device to managed?

Yes, i restarted the service and the machine

**Comment by jwijenbergh** [comment]
> Ubuntu 20.04.6 LTS server connected to via SSH

The client will not work headless, are you running an x or wayland server?

**Comment by TimFaro** [comment]
> > Ubuntu 20.04.6 LTS server connected to via SSH
> 
> The client will not work headless, are you running an x or wayland server?

I'm connected with ssh -X to the server and X11 forwarding is enabled and works, the gui opens when using `eduvpn-gui`. But then it shows the error message ```NetworkManager not managing device. The application will not be able to configure the network. NetworkManager is installed but no device of the primary connection is currently managed by it. ``` But I assume this message just pops up when the above mentioned error occurs? Or is there another way to check if the connection is actually managed besides the ways I showed above? 

The error also occurs when I'm connecting from Windows using Remote Desktop Connection.

**Comment by jwijenbergh** [comment]
> But I assume this message just pops up when the above mentioned error occurs? Or is there another way to check if the connection is actually managed besides the ways I showed above?

Correct. It checks if `any device of the primary connection is managed by Network Manager.` How did you set it up so that NetworkManager manages the connection?

Did you set managed to True in `/etc/NetworkManager/NetworkManager.conf`?

I think `nmcli dev status` is indeed the correct way. Maybe also try to manage the loopback device?

I think for ubuntu server you need to do some netplan configuration https://ubuntu.com/core/docs/networkmanager/networkmanager-and-netplan. I recommend to use a client only on a desktop os and import wireguard/openvpn configs from the eduVPN portal for server OS

**Comment by TimFaro** [comment]
> How did you set it up so that NetworkManager manages the connection? 
> Did you set managed to True in /etc/NetworkManager/NetworkManager.conf?

I had to do multiple steps and edit different configs, since NetworkManager relies on more than one config. If I remember correctly, the step that finally worked was adding `except:type:ethernet` to `unmanaged-devices=*,` in the file `/lib/NetworkManager/conf.d/10-globally-managed-devices.conf`. But `managed=true` in `/etc/NetworkManager/NetworkManager.conf` is also set, yes. 

> Maybe also try to manage the loopback device?

I can try but it was quite complicated to get the other one to be managed. 

> I recommend to use a client only on a desktop os and import wireguard/openvpn configs from the eduVPN portal for server OS

I'm not quite sure how I would do that, could you explain?

**Comment by jwijenbergh** [comment]
> I had to do multiple steps and edit different configs, since NetworkManager relies on more than one config. If I remember correctly, the step that finally worked was adding except:type:ethernet to unmanaged-devices=*, in the file /lib/NetworkManager/conf.d/10-globally-managed-devices.conf. But managed=true in /etc/NetworkManager/NetworkManager.conf is also set, yes.

Right that doesn't sound trivial indeed.

> I can try but it was quite complicated to get the other one to be managed.

Gotcha

> I'm not quite sure how I would do that, could you explain?

Which server are you trying to connect to and secure internet or institute access?

**Comment by TimFaro** [comment]
> Which server are you trying to connect to and secure internet or institute access?

I need institute access to [78]: Technical University of Munich via LRZ-VPN

**Comment by jwijenbergh** [comment]
> > Which server are you trying to connect to and secure internet or institute access?
> 
> I need institute access to [78]: Technical University of Munich via LRZ-VPN

at https://tum.eduvpn.lrz.de/ you should be able to login and download an openvpn/wireguard file from the web page

**Comment by TimFaro** [comment]
Thanks! I needed to install version 2.5 of OpenVPN (explained [here](https://community.openvpn.net/openvpn/wiki/OpenvpnSoftwareRepos)) because I got an error message `Options error: Unrecognized option or missing or extra parameter(s) in ###.ovpn:12: data-ciphers (2.4.12)` but then the config import worked. 

It tried to connect but got an error from OpenVPN `sitnl_send: rtnl: generic error (-101): Network is unreachable`. But this could be a server issue on my end, I might need to revert the changes I did to NetworkManager.

On a side note, in case anyone comes across this issue, I found out that the interface was probably still not managed by NM but by netplan. The file `/etc/netplan/01-network-manager-all.yaml` contained configurations for the device but shouldn't. I first wanted to try to use OpenVPN, but should someone else need it, for NM to manage the device, according to [this](https://askubuntu.com/a/1112883), the netplan /`etc/netplan/*.yaml` file should look like this:
```
network:
  version: 2
  renderer: NetworkManager
```

**Comment by jwijenbergh** [comment]
> Thanks! I needed to install version 2.5 of OpenVPN (explained [here](https://community.openvpn.net/openvpn/wiki/OpenvpnSoftwareRepos)) because I got an error message Options error: Unrecognized option or missing or extra parameter(s) in ###.ovpn:12: data-ciphers (2.4.12) but then the config import worked.

Ah that is not good, sorry for the bad user experience :(

> It tried to connect but got an error from OpenVPN sitnl_send: rtnl: generic error (-101): Network is unreachable. But this could be a server issue on my end, I might need to revert the changes I did to NetworkManager.

Let me know if there is anything I can do

> On a side note, in case anyone comes across this issue, I found out that the interface was probably still not managed by NM but by netplan. The file /etc/netplan/01-network-manager-all.yaml contained configurations for the device but shouldn't. I first want to try to get OpenVPN to work, but should someone else need it, for NM to manage the device, according to [this](https://askubuntu.com/a/1112883), the netplan /etc/netplan/*.yaml file should look like this:

Do you know if with this configuration the client works?

**Comment by jwijenbergh** [comment]
> Thanks, unfortunately it turns out that, while the OpenVPN most likely would work for others, in my case it doesn't because apparently, the firewalls won't allow such a VPN connection since I'm working from inside a high security environment.

Right. Thanks for the update

> I'm afraid I won't be able to test this, I don't want to run the risk that if I change the configuration it would mess up the server (e.g. change the IP since in the .yaml, it's statically set) since it's actually a VM set up by our IT department inside the secure environment.

That makes sense. If you have any issues with the client on e.g. a desktop distro, feel free to make another issue
