### ISSUE TITLE
unclear error message / missing dependency?

### ISSUE THREAD

**Issue by borutmrak** [eduvpn/python-eduvpn-client#572]
# Installation

Let's connect installed via released .deb packages

# Version

Let's Connect! GUI version: 4.2.1 with eduvpn-common version: 1.2.0

# Check if your issue is in the known issues list

Checked.

# OS/Distribution

Unknown

# Logs

2024-02-28 13:01:20,760 - call-model - ERROR - /usr/lib/python3.11/site-packages/eduvpn/utils.py - utils.py:59 - Error occurred: Expected one openvpn VPN plugins, got: 0

## Do you have a problem while adding before connecting?

The user that reported this was missing network-manager-openvpn package. The error went away after installing that but I had to search in the code where the message came from and realised what VPN plugin it is talking about.

Either this should be added to the package dependencies (but probably not since NM itself is not a requirement) or the error message should be clearer - Expected one Network Manager OpenVPN plugin, got: x.

**Comment by borutmrak** [comment]
I now notice that network-manager-openvpn and network-manager-openvpn-gnome is already a Depends: of the letsconnect-client package... I'll check with the user how they actually installed it.

**Comment by borutmrak** [comment]
> > Unknown
> 
> unknown distro? what does `/etc/os-release` tell us?

I got a very short bug report from the user and I was under the impression that it is Debian or Ubuntu, but it is not, it's Arch. As the issue was solved by installing the network-manager-openvpn I did not investigate further with them at the time.

> > so the error message should still be improved
> 
> I will try to add a better error message but I don't see anything wrong with the DEB packaging

Correct, nothing wrong with the packaging, the user installed the package from https://aur.archlinux.org/packages/python-eduvpn-client/.

> 
> > but probably not since NM itself is not a requirement
> 
> it is a requirement for the client, maybe the aur package needs to be changed

I'm new to this software and when I wrote that I was thought it's not necessary. I was wrong.

> > I was under the wrong impression, the user is not actually using .deb packages but Arch, that's the reason the package was not installed. Can you add something @janhrastnik?
> 
> Right, we do not maintain those. I am guessing maybe all that is needed is moving the network-manager-openvpn to the depends instead of optdepends. I guess if you only want WireGuard you don't need it, but most servers are still on OpenVPN.

Agreed, I will ask the user to take it up further if they want.

I guess it would be nice if you make the error message clearer, otherwise you can close this issue.

Thank you!

**Comment by jwijenbergh** [comment]
> I got a very short bug report from the user and I was under the impression that it is Debian or Ubuntu, but it is not, it's Arch. As the issue was solved by installing the network-manager-openvpn I did not investigate further with them at the time.

Right, thanks for the explanation.

> Correct, nothing wrong with the packaging, the user installed the package from https://aur.archlinux.org/packages/python-eduvpn-client/.

Yeah I was a bit confused at first if this was about deb or aur, apologies.

> I'm new to this software and when I wrote that I thought it's not necessary. I was wrong.

No worries!

> Agreed, I will ask the user to take it up further if they want.
> I guess it would be nice if you make the error message clearer, otherwise you can close this issue.

I will thank you!

**Comment by jwijenbergh** [comment]
Should be fixed in the arch package. Thanks a lot @hv15!
