### ISSUE TITLE
Installation Instructions for Arch and NixOS

### ISSUE THREAD

**Issue by fstoehr** [eduvpn/python-eduvpn-client#573]
The current installation instructions for Arch Linux can confuse people at first glance. The AUR package checks the downloaded version of EduVPN using a pgp key, which is a good thing, but means the installation will fail if the pgp public key hasn't previously be imported. (This information is provided in a comment on the package page in the AUR website, but many Arch users don't check the website and use an AUR helper to install the package directly, ideally after taking a look at the build instructions.)

I've attached a more detailed description of how to install in Arch and another one for NixOS below, perhaps you can copy-and-paste them into the install documentation / website if you have no corrections to make:

--------

# Arch

First import the gpg key:
$ curl https://app.eduvpn.org/linux/v4/deb/app+linux@eduvpn.org.asc | gpg --import -

Then, build from AUR using your preferred helper or method. 
If you are using pamac, that's

$ pamac build python-eduvpn-client

For yay, it's

$ yay -S python-eduvpn-client

# NixOS

The eduvpn client is part of the official nixpkgs repository. The package name is "eduvpn-client".
You can install it using your preferred method.

Example for nix run:

$ nix run nixpkgs#eduvpn-client

if you don't have flakes and nix-command enabled globally, instead use:

$ nix run --extra-experimental-features nix-command --extra-experimental-features flakes run nixpkgs#eduvpn-client

**Comment by pietro-sillano** [comment]
I am not sure if you also have encountered my same issue but I am getting an error trying to update with yay on ArchLinux:

```
curl https://app.eduvpn.org/linux/v4/deb/app+linux@eduvpn.org.asc | gpg --import
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   449  100   449    0     0   1966      0 --:--:-- --:--:-- --:--:--  1969
gpg: key 02BB8048BBFF222C: "eduVPN Linux App Repository Signing Key <app+linux@eduvpn.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
❯ yay -S python-eduvpn-client
AUR Explicit (1): python-eduvpn-client-4.2.1-1
AUR Dependency (1): python-eduvpn_common-1.2.0-1
:: PKGBUILD up to date, skipping download: python-eduvpn-client
:: PKGBUILD up to date, skipping download: python-eduvpn_common
  2 python-eduvpn-client             (Build Files Exist)
  1 python-eduvpn_common             (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
  2 python-eduvpn_common             (Build Files Exist)
  1 python-eduvpn-client             (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
==> Making package: python-eduvpn-client 4.2.1-1 (Wed 28 Feb 2024 05:05:54 PM CET)
==> Retrieving sources...
  -> Found python-eduvpn-client-4.2.1.tar.xz
  -> Found python-eduvpn-client-4.2.1.tar.xz.asc
==> WARNING: Skipping verification of source file PGP signatures.
==> Validating source files with sha256sums...
    python-eduvpn-client-4.2.1.tar.xz ... Passed
    python-eduvpn-client-4.2.1.tar.xz.asc ... Skipped
==> Making package: python-eduvpn_common 1.2.0-1 (Wed 28 Feb 2024 05:05:55 PM CET)
==> Retrieving sources...
  -> Found eduvpn-common-1.2.0.tar.xz
  -> Found eduvpn-common-1.2.0.tar.xz.asc
==> WARNING: Skipping verification of source file PGP signatures.
==> Validating source files with sha256sums...
    eduvpn-common-1.2.0.tar.xz ... Passed
    eduvpn-common-1.2.0.tar.xz.asc ... Skipped
:: (1/2) Parsing SRCINFO: python-eduvpn-client
:: (2/2) Parsing SRCINFO: python-eduvpn_common
pub   ed25519 2023-03-01 [SC] [expires: 2033-02-26]
      227FF3F8F829D9A9314D9EBA02BB8048BBFF222C
uid           [ unknown] eduVPN Linux App Repository Signing Key <app+linux@eduvpn.org>

pub   ed25519 2023-03-01 [SC] [expires: 2033-02-26]
      227FF3F8F829D9A9314D9EBA02BB8048BBFF222C
uid           [ unknown] eduVPN Linux App Repository Signing Key <app+linux@eduvpn.org>

==> Making package: python-eduvpn_common 1.2.0-1 (Wed 28 Feb 2024 05:05:56 PM CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found eduvpn-common-1.2.0.tar.xz
  -> Found eduvpn-common-1.2.0.tar.xz.asc
==> Validating source files with sha256sums...
    eduvpn-common-1.2.0.tar.xz ... Passed
    eduvpn-common-1.2.0.tar.xz.asc ... Skipped
==> Verifying source file signatures with gpg...
    eduvpn-common-1.2.0.tar.xz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting eduvpn-common-1.2.0.tar.xz with bsdtar
==> Sources are ready.
==> Making package: python-eduvpn_common 1.2.0-1 (Wed 28 Feb 2024 05:05:58 PM CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Removing existing $pkgdir/ directory...
==> Starting build()...
make -C exports
make[1]: Entering directory '/home/pietro/.cache/yay/python-eduvpn_common/src/eduvpn-common-1.2.0/exports'
CGO_ENABLED=1 go build -o lib/linux/amd64/libeduvpn_common-1.2.0.so -buildmode=c-shared .
disco.go:45:2: cannot find package "github.com/eduvpn/eduvpn-common/client" in any of:
        /usr/lib/go/src/github.com/eduvpn/eduvpn-common/client (from $GOROOT)
        /home/pietro/go/src/github.com/eduvpn/eduvpn-common/client (from $GOPATH)
exports.go:46:2: cannot find package "github.com/eduvpn/eduvpn-common/internal/log" in any of:
        /usr/lib/go/src/github.com/eduvpn/eduvpn-common/internal/log (from $GOROOT)
        /home/pietro/go/src/github.com/eduvpn/eduvpn-common/internal/log (from $GOPATH)
exports.go:47:2: cannot find package "github.com/eduvpn/eduvpn-common/internal/oauth" in any of:
        /usr/lib/go/src/github.com/eduvpn/eduvpn-common/internal/oauth (from $GOROOT)
        /home/pietro/go/src/github.com/eduvpn/eduvpn-common/internal/oauth (from $GOPATH)
exports.go:48:2: cannot find package "github.com/eduvpn/eduvpn-common/internal/server" in any of:
        /usr/lib/go/src/github.com/eduvpn/eduvpn-common/internal/server (from $GOROOT)
        /home/pietro/go/src/github.com/eduvpn/eduvpn-common/internal/server (from $GOPATH)
disco.go:46:2: cannot find package "github.com/eduvpn/eduvpn-common/types" in any of:
        /usr/lib/go/src/github.com/eduvpn/eduvpn-common/types (from $GOROOT)
        /home/pietro/go/src/github.com/eduvpn/eduvpn-common/types (from $GOPATH)
exports.go:49:2: cannot find package "github.com/go-errors/errors" in any of:
        /usr/lib/go/src/github.com/go-errors/errors (from $GOROOT)
        /home/pietro/go/src/github.com/go-errors/errors (from $GOPATH)
make[1]: *** [Makefile:20: lib/linux/amd64/libeduvpn_common-1.2.0.so] Error 1
make[1]: Leaving directory '/home/pietro/.cache/yay/python-eduvpn_common/src/eduvpn-common-1.2.0/exports'
make: *** [Makefile:4: build] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
 -> Failed to install layer, rolling up to next layer.error:error making: python-eduvpn_common - exit status 4
==> Making package: python-eduvpn-client 4.2.1-1 (Wed 28 Feb 2024 05:05:59 PM CET)
==> Checking runtime dependencies...
==> Missing dependencies:
  -> python-eduvpn_common>=1.1.0
==> Checking buildtime dependencies...
==> ERROR: Could not resolve all dependencies.
 -> error making: python-eduvpn-client-exit status 8
==> Making package: python-eduvpn_common 1.2.0-1 (Wed 28 Feb 2024 05:06:00 PM CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found eduvpn-common-1.2.0.tar.xz
  -> Found eduvpn-common-1.2.0.tar.xz.asc
==> Validating source files with sha256sums...
    eduvpn-common-1.2.0.tar.xz ... Passed
    eduvpn-common-1.2.0.tar.xz.asc ... Skipped
==> Verifying source file signatures with gpg...
    eduvpn-common-1.2.0.tar.xz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting eduvpn-common-1.2.0.tar.xz with bsdtar
==> Sources are ready.
==> Making package: python-eduvpn_common 1.2.0-1 (Wed 28 Feb 2024 05:06:02 PM CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Removing existing $pkgdir/ directory...
==> Starting build()...
make -C exports
make[1]: Entering directory '/home/pietro/.cache/yay/python-eduvpn_common/src/eduvpn-common-1.2.0/exports'
CGO_ENABLED=1 go build -o lib/linux/amd64/libeduvpn_common-1.2.0.so -buildmode=c-shared .
disco.go:45:2: cannot find package "github.com/eduvpn/eduvpn-common/client" in any of:
        /usr/lib/go/src/github.com/eduvpn/eduvpn-common/client (from $GOROOT)
        /home/pietro/go/src/github.com/eduvpn/eduvpn-common/client (from $GOPATH)
exports.go:46:2: cannot find package "github.com/eduvpn/eduvpn-common/internal/log" in any of:
        /usr/lib/go/src/github.com/eduvpn/eduvpn-common/internal/log (from $GOROOT)
        /home/pietro/go/src/github.com/eduvpn/eduvpn-common/internal/log (from $GOPATH)
exports.go:47:2: cannot find package "github.com/eduvpn/eduvpn-common/internal/oauth" in any of:
        /usr/lib/go/src/github.com/eduvpn/eduvpn-common/internal/oauth (from $GOROOT)
        /home/pietro/go/src/github.com/eduvpn/eduvpn-common/internal/oauth (from $GOPATH)
exports.go:48:2: cannot find package "github.com/eduvpn/eduvpn-common/internal/server" in any of:
        /usr/lib/go/src/github.com/eduvpn/eduvpn-common/internal/server (from $GOROOT)
        /home/pietro/go/src/github.com/eduvpn/eduvpn-common/internal/server (from $GOPATH)
disco.go:46:2: cannot find package "github.com/eduvpn/eduvpn-common/types" in any of:
        /usr/lib/go/src/github.com/eduvpn/eduvpn-common/types (from $GOROOT)
        /home/pietro/go/src/github.com/eduvpn/eduvpn-common/types (from $GOPATH)
exports.go:49:2: cannot find package "github.com/go-errors/errors" in any of:
        /usr/lib/go/src/github.com/go-errors/errors (from $GOROOT)
        /home/pietro/go/src/github.com/go-errors/errors (from $GOPATH)
make[1]: *** [Makefile:20: lib/linux/amd64/libeduvpn_common-1.2.0.so] Error 1
make[1]: Leaving directory '/home/pietro/.cache/yay/python-eduvpn_common/src/eduvpn-common-1.2.0/exports'
make: *** [Makefile:4: build] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: python-eduvpn_common-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
python-eduvpn-client - exit status 8
python-eduvpn_common - exit status 4
```

**Comment by fstoehr** [comment]
> I am not sure if you also have encountered my same issue but I am getting an error trying to update with yay on ArchLinux:

I haven't encountered this issue, I just rebuilt eduVPN using yay to check and it built flawlessly again. I should add that I'm using Manjaro rather than standard Arch, but it seems rather unlikely that that's making a difference. No idea how to fix your issue -- the only thing I can come up with is to clear any cache and previous build attempts and then try again.

**Comment by pietro-sillano** [comment]
Actually I'm on EndeavourOS but It should not make any difference, I will
try again deleting the cache! Thank you for the help :)

**Comment by jwijenbergh** [comment]
Could you make a PR?

Note that we do not maintain the AUR packages. I submitted the NixOS packages but I was waiting for the 24.05 release first to document it.

**Comment by jwijenbergh** [comment]
> I am not sure if you also have encountered my same issue but I am getting an error trying to update with yay on ArchLinux:
> 
> ```
> curl https://app.eduvpn.org/linux/v4/deb/app+linux@eduvpn.org.asc | gpg --import
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   449  100   449    0     0   1966      0 --:--:-- --:--:-- --:--:--  1969
> gpg: key 02BB8048BBFF222C: "eduVPN Linux App Repository Signing Key <app+linux@eduvpn.org>" not changed
> gpg: Total number processed: 1
> gpg:              unchanged: 1
> ❯ yay -S python-eduvpn-client
> AUR Explicit (1): python-eduvpn-client-4.2.1-1
> AUR Dependency (1): python-eduvpn_common-1.2.0-1
> :: PKGBUILD up to date, skipping download: python-eduvpn-client
> :: PKGBUILD up to date, skipping download: python-eduvpn_common
>   2 python-eduvpn-client             (Build Files Exist)
>   1 python-eduvpn_common             (Build Files Exist)
> ==> Packages to cleanBuild?
> ==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
> ==> 
>   2 python-eduvpn_common             (Build Files Exist)
>   1 python-eduvpn-client             (Build Files Exist)
> ==> Diffs to show?
> ==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
> ==> 
> ==> Making package: python-eduvpn-client 4.2.1-1 (Wed 28 Feb 2024 05:05:54 PM CET)
> ==> Retrieving sources...
>   -> Found python-eduvpn-client-4.2.1.tar.xz
>   -> Found python-eduvpn-client-4.2.1.tar.xz.asc
> ==> WARNING: Skipping verification of source file PGP signatures.
> ==> Validating source files with sha256sums...
>     python-eduvpn-client-4.2.1.tar.xz ... Passed
>     python-eduvpn-client-4.2.1.tar.xz.asc ... Skipped
> ==> Making package: python-eduvpn_common 1.2.0-1 (Wed 28 Feb 2024 05:05:55 PM CET)
> ==> Retrieving sources...
>   -> Found eduvpn-common-1.2.0.tar.xz
>   -> Found eduvpn-common-1.2.0.tar.xz.asc
> ==> WARNING: Skipping verification of source file PGP signatures.
> ==> Validating source files with sha256sums...
>     eduvpn-common-1.2.0.tar.xz ... Passed
>     eduvpn-common-1.2.0.tar.xz.asc ... Skipped
> :: (1/2) Parsing SRCINFO: python-eduvpn-client
> :: (2/2) Parsing SRCINFO: python-eduvpn_common
> pub   ed25519 2023-03-01 [SC] [expires: 2033-02-26]
>       227FF3F8F829D9A9314D9EBA02BB8048BBFF222C
> uid           [ unknown] eduVPN Linux App Repository Signing Key <app+linux@eduvpn.org>
> 
> pub   ed25519 2023-03-01 [SC] [expires: 2033-02-26]
>       227FF3F8F829D9A9314D9EBA02BB8048BBFF222C
> uid           [ unknown] eduVPN Linux App Repository Signing Key <app+linux@eduvpn.org>
> 
> ==> Making package: python-eduvpn_common 1.2.0-1 (Wed 28 Feb 2024 05:05:56 PM CET)
> ==> Checking runtime dependencies...
> ==> Checking buildtime dependencies...
> ==> Retrieving sources...
>   -> Found eduvpn-common-1.2.0.tar.xz
>   -> Found eduvpn-common-1.2.0.tar.xz.asc
> ==> Validating source files with sha256sums...
>     eduvpn-common-1.2.0.tar.xz ... Passed
>     eduvpn-common-1.2.0.tar.xz.asc ... Skipped
> ==> Verifying source file signatures with gpg...
>     eduvpn-common-1.2.0.tar.xz ... Passed
> ==> Removing existing $srcdir/ directory...
> ==> Extracting sources...
>   -> Extracting eduvpn-common-1.2.0.tar.xz with bsdtar
> ==> Sources are ready.
> ==> Making package: python-eduvpn_common 1.2.0-1 (Wed 28 Feb 2024 05:05:58 PM CET)
> ==> Checking runtime dependencies...
> ==> Checking buildtime dependencies...
> ==> WARNING: Using existing $srcdir/ tree
> ==> Removing existing $pkgdir/ directory...
> ==> Starting build()...
> make -C exports
> make[1]: Entering directory '/home/pietro/.cache/yay/python-eduvpn_common/src/eduvpn-common-1.2.0/exports'
> CGO_ENABLED=1 go build -o lib/linux/amd64/libeduvpn_common-1.2.0.so -buildmode=c-shared .
> disco.go:45:2: cannot find package "github.com/eduvpn/eduvpn-common/client" in any of:
>         /usr/lib/go/src/github.com/eduvpn/eduvpn-common/client (from $GOROOT)
>         /home/pietro/go/src/github.com/eduvpn/eduvpn-common/client (from $GOPATH)
> exports.go:46:2: cannot find package "github.com/eduvpn/eduvpn-common/internal/log" in any of:
>         /usr/lib/go/src/github.com/eduvpn/eduvpn-common/internal/log (from $GOROOT)
>         /home/pietro/go/src/github.com/eduvpn/eduvpn-common/internal/log (from $GOPATH)
> exports.go:47:2: cannot find package "github.com/eduvpn/eduvpn-common/internal/oauth" in any of:
>         /usr/lib/go/src/github.com/eduvpn/eduvpn-common/internal/oauth (from $GOROOT)
>         /home/pietro/go/src/github.com/eduvpn/eduvpn-common/internal/oauth (from $GOPATH)
> exports.go:48:2: cannot find package "github.com/eduvpn/eduvpn-common/internal/server" in any of:
>         /usr/lib/go/src/github.com/eduvpn/eduvpn-common/internal/server (from $GOROOT)
>         /home/pietro/go/src/github.com/eduvpn/eduvpn-common/internal/server (from $GOPATH)
> disco.go:46:2: cannot find package "github.com/eduvpn/eduvpn-common/types" in any of:
>         /usr/lib/go/src/github.com/eduvpn/eduvpn-common/types (from $GOROOT)
>         /home/pietro/go/src/github.com/eduvpn/eduvpn-common/types (from $GOPATH)
> exports.go:49:2: cannot find package "github.com/go-errors/errors" in any of:
>         /usr/lib/go/src/github.com/go-errors/errors (from $GOROOT)
>         /home/pietro/go/src/github.com/go-errors/errors (from $GOPATH)
> make[1]: *** [Makefile:20: lib/linux/amd64/libeduvpn_common-1.2.0.so] Error 1
> make[1]: Leaving directory '/home/pietro/.cache/yay/python-eduvpn_common/src/eduvpn-common-1.2.0/exports'
> make: *** [Makefile:4: build] Error 2
> ==> ERROR: A failure occurred in build().
>     Aborting...
>  -> Failed to install layer, rolling up to next layer.error:error making: python-eduvpn_common - exit status 4
> ==> Making package: python-eduvpn-client 4.2.1-1 (Wed 28 Feb 2024 05:05:59 PM CET)
> ==> Checking runtime dependencies...
> ==> Missing dependencies:
>   -> python-eduvpn_common>=1.1.0
> ==> Checking buildtime dependencies...
> ==> ERROR: Could not resolve all dependencies.
>  -> error making: python-eduvpn-client-exit status 8
> ==> Making package: python-eduvpn_common 1.2.0-1 (Wed 28 Feb 2024 05:06:00 PM CET)
> ==> Checking runtime dependencies...
> ==> Checking buildtime dependencies...
> ==> Retrieving sources...
>   -> Found eduvpn-common-1.2.0.tar.xz
>   -> Found eduvpn-common-1.2.0.tar.xz.asc
> ==> Validating source files with sha256sums...
>     eduvpn-common-1.2.0.tar.xz ... Passed
>     eduvpn-common-1.2.0.tar.xz.asc ... Skipped
> ==> Verifying source file signatures with gpg...
>     eduvpn-common-1.2.0.tar.xz ... Passed
> ==> Removing existing $srcdir/ directory...
> ==> Extracting sources...
>   -> Extracting eduvpn-common-1.2.0.tar.xz with bsdtar
> ==> Sources are ready.
> ==> Making package: python-eduvpn_common 1.2.0-1 (Wed 28 Feb 2024 05:06:02 PM CET)
> ==> Checking runtime dependencies...
> ==> Checking buildtime dependencies...
> ==> WARNING: Using existing $srcdir/ tree
> ==> Removing existing $pkgdir/ directory...
> ==> Starting build()...
> make -C exports
> make[1]: Entering directory '/home/pietro/.cache/yay/python-eduvpn_common/src/eduvpn-common-1.2.0/exports'
> CGO_ENABLED=1 go build -o lib/linux/amd64/libeduvpn_common-1.2.0.so -buildmode=c-shared .
> disco.go:45:2: cannot find package "github.com/eduvpn/eduvpn-common/client" in any of:
>         /usr/lib/go/src/github.com/eduvpn/eduvpn-common/client (from $GOROOT)
>         /home/pietro/go/src/github.com/eduvpn/eduvpn-common/client (from $GOPATH)
> exports.go:46:2: cannot find package "github.com/eduvpn/eduvpn-common/internal/log" in any of:
>         /usr/lib/go/src/github.com/eduvpn/eduvpn-common/internal/log (from $GOROOT)
>         /home/pietro/go/src/github.com/eduvpn/eduvpn-common/internal/log (from $GOPATH)
> exports.go:47:2: cannot find package "github.com/eduvpn/eduvpn-common/internal/oauth" in any of:
>         /usr/lib/go/src/github.com/eduvpn/eduvpn-common/internal/oauth (from $GOROOT)
>         /home/pietro/go/src/github.com/eduvpn/eduvpn-common/internal/oauth (from $GOPATH)
> exports.go:48:2: cannot find package "github.com/eduvpn/eduvpn-common/internal/server" in any of:
>         /usr/lib/go/src/github.com/eduvpn/eduvpn-common/internal/server (from $GOROOT)
>         /home/pietro/go/src/github.com/eduvpn/eduvpn-common/internal/server (from $GOPATH)
> disco.go:46:2: cannot find package "github.com/eduvpn/eduvpn-common/types" in any of:
>         /usr/lib/go/src/github.com/eduvpn/eduvpn-common/types (from $GOROOT)
>         /home/pietro/go/src/github.com/eduvpn/eduvpn-common/types (from $GOPATH)
> exports.go:49:2: cannot find package "github.com/go-errors/errors" in any of:
>         /usr/lib/go/src/github.com/go-errors/errors (from $GOROOT)
>         /home/pietro/go/src/github.com/go-errors/errors (from $GOPATH)
> make[1]: *** [Makefile:20: lib/linux/amd64/libeduvpn_common-1.2.0.so] Error 1
> make[1]: Leaving directory '/home/pietro/.cache/yay/python-eduvpn_common/src/eduvpn-common-1.2.0/exports'
> make: *** [Makefile:4: build] Error 2
> ==> ERROR: A failure occurred in build().
>     Aborting...
>  -> error making: python-eduvpn_common-exit status 4
>  -> Failed to install the following packages. Manual intervention is required:
> python-eduvpn-client - exit status 8
> python-eduvpn_common - exit status 4
> ```

not sure, could you submit this on the aur package as an issue?

**Comment by jwijenbergh** [comment]
I documented Arch and NixOS: a70d4e797f42d3ebacd165d147bb6fe13179c3ef
