### ISSUE TITLE
Support for Fedora 40

### ISSUE THREAD

**Issue by PunkPangolin** [eduvpn/python-eduvpn-client#577]
Fedora 40 is expected to be released in three weeks, and the beta will be released tomorrow. Adding a build for Fedora 40 would allow EduVPN to be tested there before the main release. Currently, installing EduVPN from the repo blocks an upgrade to the F40 beta.

**Comment by jwijenbergh** [comment]
Sorry for taking so long, packages are online for fedora 40 (current stable packages). Pre-releases for fedora 40 will follow later this week
