### ISSUE TITLE
openSuse official support

### ISSUE THREAD

**Issue by Deeds87** [eduvpn/python-eduvpn-client#579]
As the title says. I  wish for official openSuse support.

**Comment by jwijenbergh** [comment]
See https://github.com/eduvpn/python-eduvpn-client/issues/565

**Comment by ltsavar** [comment]
pip way is not working for me

**Comment by jwijenbergh** [comment]
Nothing actionable here I am afraid, packaging for opensuse was difficult as it involved doing checks in our packages
