### ISSUE TITLE
Closing the client

### ISSUE THREAD

**Issue by aloispichler** [eduvpn/python-eduvpn-client#580]
Would be nice to have a shortcut (as C-q or C-w) on Linux to close the client, enabled if not connected. Now, only killing seems to be possible. Or did I miss anything here? 
Thanks

**Comment by jwijenbergh** [comment]
Will add a shortcut, I think ctrl+q makes sense. 

Regarding killing, which window manager/desktop environment are you using. For KDE/GNOME there should be a window titlebar with a close button. If you are using a window manager a shortcut should be available to gracefully close a window.

**Comment by aloispichler** [comment]
I use hyprland with `killactive`. But I do prefer properly closing the connection and properly closing the client instead of killing everything.

**Comment by jwijenbergh** [comment]
Right and do you know if `killactive` forcefully closes? Anyways I will make sure the option is there in a new version

**Comment by jwijenbergh** [comment]
I added ctrl+q to close, will release soon

**Comment by jwijenbergh** [comment]
New version is released

**Comment by aloispichler** [comment]
Thank you, great, this works now.
