### ISSUE TITLE
Ubuntu 24.04 install fails

### ISSUE THREAD

**Issue by defnull** [eduvpn/python-eduvpn-client#585]
Following https://docs.eduvpn.org/client/linux/installation.html#ubuntu-2404 leads to an error: 

```
Setting up python3-eduvpn-common (1.2.0-3+ubuntu+24.04+1) ...
/usr/lib/python3/dist-packages/eduvpn_common/main.py:92: SyntaxWarning: invalid escape sequence '\*'
  """Call an internal go function and properly forward the arguments.
```

This is because the [deb repository](https://app.eduvpn.org/linux/v4/deb/) does not contain a recent enough version of [python3-eduvpn-common](https://app.eduvpn.org/linux/v4/deb/pool/main/p/python3-eduvpn-common/). Version 1.2.0 contains a syntax error that was just a warning in Python 3.11 but throws an exception starting with Python 3.12. In version 1.99.0 (strange versioning scheme by the way) this is fixed, but that version is not available as deb.

**Comment by jwijenbergh** [comment]
This is only a warning not an error. 1.99.0 is a pre-release

**Comment by jwijenbergh** [comment]
this has been fixed in the DEB and RPM packages, run `sudo apt update && sudo apt upgrade`
