### ISSUE TITLE
Improve the Mac menu bar icon, hardly visible if connected or not

### ISSUE THREAD

**Issue by b-johannes** [eduvpn/python-eduvpn-client#586]
Please change the icon on the menu bar. It is very hard to see if it is connected. Please follow the Apple UI guidelines: here for example the volume button is light grey if volume is deactivated and solid white when connected. Wireguard VPN Client does the same, as many other software, too.

Connected
![Screenshot 2024-05-17 at 14 40 38](https://github.com/eduvpn/python-eduvpn-client/assets/101400690/7d62cf94-267f-436b-932b-efefb7139c70)
Not connected
![Screenshot 2024-05-17 at 14 40 30](https://github.com/eduvpn/python-eduvpn-client/assets/101400690/ba953701-e9a9-444b-a8f0-0480f4bddfca)
As reference Volume muted
![Screenshot 2024-05-17 at 14 40 55](https://github.com/eduvpn/python-eduvpn-client/assets/101400690/e410fd0e-cc16-4029-8f52-15b1f65f0420)
Volume on
![Screenshot 2024-05-17 at 14 40 47](https://github.com/eduvpn/python-eduvpn-client/assets/101400690/18aea491-148a-4d5f-bbff-9d05c3a71ca5)

**Comment by jwijenbergh** [comment]
This icon is not controlled by us but NetworkManager
