### ISSUE TITLE
Dash icon missing on ubungtu 24.02

### ISSUE THREAD

**Issue by phavekes** [eduvpn/python-eduvpn-client#588]
The icon in the Launcher is correct, the dash showd the default "unknown/gear" icon.

# Installation

With apt using https://app.eduvpn.org/linux/v4/deb/ as source 

# Version

4.2.1

# Check if your issue is in the known issues list

No

# OS/Distribution

Ubuntu 24.04 (upgraded from 23.10, where the icon showed correctly)

# Logs

Not relevant i assume.

## Do you have a problem while adding before connecting?

No

## Do you have a problem during or after connecting?

no

![image](https://github.com/eduvpn/python-eduvpn-client/assets/3096423/0b5866b7-5da0-4339-8d29-3f3ba7787312)

**Comment by jwijenbergh** [comment]
can you check where the working icons are located? e.g. for spotify?

**Comment by phavekes** [comment]
The icon is present and working in the app launcher, only missing in the dash. 

After doing some googeling:

[This is because the window created by the application is not associated with the shortcut used to start the application. In Ubuntu 22.04 and earlier, you’ll get duplicated app icons on the dock. However, in Ubuntu 24.04 it falls back to the executable icon (the gear icon) instead.](https://ubuntuhandbook.org/index.php/2024/04/missing-icon-dock-ubuntu-2404/#:~:text=This%20is%20because%20the%20window%20created%20by%20the%20application%20is%20not%20associated%20with%20the%20shortcut%20used%20to%20start%20the%20application.%20In%20Ubuntu%2022.04%20and%20earlier%2C%20you%E2%80%99ll%20get%20duplicated%20app%20icons%20on%20the%20dock.%20However%2C%20in%20Ubuntu%2024.04%20it%20falls%20back%20to%20the%20executable%20icon%20(the%20gear%20icon)%20instead.)

**Comment by jwijenbergh** [comment]
nice, and thanks for the pr!

**Comment by jwijenbergh** [comment]
I will leave this open until I make a new release. I am planning to make one next week

**Comment by jwijenbergh** [comment]
New version is released
