### ISSUE TITLE
Cannot add http server in let's connect variant

### ISSUE THREAD

**Issue by Derkades** [eduvpn/python-eduvpn-client#599]
I would like make connections using plain http so I can inspect them with wireshark. I have installed the let's connect variant v4.3.1 via fedora packages. 

When entering a URL with http://, it fails to add the server with the following error message:
> The following error was reported: Failed to add a server with URL: 'https:/'. The cause of the error is: http: no Host in request URL.

Blocking plain HTTP might be intentional, but in any case the error message is unexpected

**Comment by Derkades** [comment]
I entered: `http://eduvpn.rslot.nl` (resolves to a private network address)

I have also tried entering a HTTPS URL (with HTTPS temporarily enabled on the server side) and then later modifying it to HTTP in state.json, that also failed

**Comment by jwijenbergh** [comment]
Thanks. Will see if I can improve the error message.

Maybe use a self-signed certificate and then:


```
On Unix systems other than macOS the environment variables SSL_CERT_FILE and SSL_CERT_DIR can be used to override the system default locations for the SSL certificate file and SSL certificate files directory, respectively. The latter can be a colon-separated list. 
```
https://pkg.go.dev/crypto/x509

**Comment by Derkades** [comment]
Thanks. I have a trusted certificate, but I was struggling with decrypting TLS in Wireshark. I'll try harder..

**Comment by jwijenbergh** [comment]
hmmm I cannot reproduce this:

`/etc/hosts`

```
127.0.0.1 eduvpn.rslot.nl
```

then starting a python server on port 80:

```
Failed to add a server with URL: 'https://eduvpn.rslot.nl/'. The cause of the error is: connection refused.
```

or when using 443:

```
Failed to add a server with URL: 'https://eduvpn.rslot.nl/'. The cause of the error is: tls: first record does not look like a TLS handshake.
```

**Comment by jwijenbergh** [comment]
> I was struggling with decrypting TLS in Wireshark so I thought HTTP would be easier.

For Wireshark docs on this, see https://wiki.wireshark.org/TLS#tls-decryption

Maybe for your case mitmproxy is easier? https://docs.mitmproxy.org/stable/concepts-certificates/#the-mitmproxy-certificate-authority

steps:

- run `mitmproxy`
- run eduvpn with `SSL_CERT_DIR=~/.mitmproxy HTTPS_PROXY=127.0.0.1:8080 eduvpn-gui`

**Comment by Derkades** [comment]
Good idea, mitmproxy seems like the easiest solution indeed. I can no longer reproduce the bug either. I have no idea what changed. In any case, this issue can be closed, thanks for the help!

![Screenshot_20240621_122151](https://github.com/eduvpn/python-eduvpn-client/assets/15892014/f95d794e-0172-4ac3-9f34-9086625730e5)
![Screenshot_20240621_122213](https://github.com/eduvpn/python-eduvpn-client/assets/15892014/286af421-8f55-4eec-b4ea-3ae03cd70fc8)

**Comment by jwijenbergh** [comment]
Very weird in any case, if there is a problem in the end feel free to re-open.

Glad it works

**Comment by Derkades** [comment]
mitmproxy works with HTTPS_PROXY like you said. What I didn't consider is that this of course doesn't include ProxyGuard traffic, as it is not HTTP but websocket. And the reason I wanted a capture in the first place is to do stress testing with TRex, which doesn't support TLS. I will find a different approach

**Comment by jwijenbergh** [comment]
ProxyGuard does use HTTP(s) for the upgrade handshake, afterwards it's not websocket but regular TCP that encapsulates UDP packets with a length header. Maybe you can still try the wireshark + mitmproxy approach I linked. It would still use the mitmproxy TLS cert I think as the handshake is HTTPS

**Comment by jwijenbergh** [comment]
Ah you can't see proxyguard in mitmproxy because it's in a separate routine. To see proxyguard, patch proxyguard like so:

```diff
diff --git a/client.go b/client.go
index 44bcbfa..45ca27c 100644
--- a/client.go
+++ b/client.go
@@ -184,10 +184,15 @@ func (c *Client) tryTunnel(ctx context.Context, peer string, pips []string, firs
 	if c.httpc == nil {
 		c.httpc = &http.Client{}
 	}
+	proxy, err := url.Parse("https://127.0.0.1:8080")
+	if err != nil {
+		return err
+	}
 	transport := &http.Transport{
 		DialContext: func(ctx context.Context, network string, addr string) (conn net.Conn, err error) {
 			return c.dialContext(ctx, dialer, network, addr, peerhost, pips)
 		},
+		Proxy: http.ProxyURL(proxy),
 	}
 	c.httpc.Transport = transport
 
```

then patch common like this:

```diff
diff --git a/go.mod b/go.mod
index b79bd9f..f1d3e79 100644
--- a/go.mod
+++ b/go.mod
@@ -2,6 +2,8 @@ module github.com/eduvpn/eduvpn-common
 
 go 1.18
 
+replace codeberg.org/eduVPN/proxyguard => ../proxyguard
+
 require (
 	codeberg.org/eduVPN/proxyguard v0.0.0-20240503081809-7a66ae6a0c71
 	github.com/jedisct1/go-minisign v0.0.0-20230811132847-661be99b8267
```

and patch the client like this (to allow traffic from any source port)

```
diff --git a/eduvpn/nm.py b/eduvpn/nm.py
index 0e6999f..ebd35f2 100644
--- a/eduvpn/nm.py
+++ b/eduvpn/nm.py
@@ -568,8 +568,8 @@ class NMManager:
                         continue
                     proxy_rule = NM.IPRoutingRule.new(family)
                     proxy_rule.set_priority(prios[1])
-                    sport = int(proxy.source_port)
-                    proxy_rule.set_source_port(sport, sport)
+                    #sport = int(proxy.source_port)
+                    #proxy_rule.set_source_port(sport, sport)
                     proxy_rule.set_to(proxy_peer_ip, subnet)
                     proxy_rule.set_destination_port(dport_proxy, dport_proxy)
                     proxy_rule.set_ipproto(IPPROTO_TCP)
```

now you can see the upgrade header + TCP stream in mitmproxy

**Comment by Derkades** [comment]
Thank you for the detailed response. I applied the patches and changed __main__ in eduvpn.ui to start letsconnect() instead of eduvpn(). I used http:// for the proxy URL in proxyguard instead of HTTPS. ProxyGuard is working:
```
2024/06/25 13:35:42 - Go - INFO - [Proxyguard] Connecting to HTTP server...
2024/06/25 13:35:42 - Go - INFO - [Proxyguard] Connected to HTTP server
2024/06/25 13:35:42 - Go - INFO - [Proxyguard] Waiting for first UDP packet...
2024/06/25 13:35:42 - Go - INFO - [Proxyguard] First UDP packet received with address: 127.0.0.1:59644
2024/06/25 13:35:42 - Go - INFO - [Proxyguard] Client is ready for converting UDP<->HTTP
```

mitmproxy still does not show any ProxyGuard flows for me. Did you do anything special to get mitmproxy to show TCP? Even with `--tcp-hosts ".*"` it only shows HTTP traffic to /info and /connect

**Comment by jwijenbergh** [comment]
if you use http instead of https then you need to use HTTP_PROXY=127.0.0.1:8080 on top of the HTTPS_PROXY env var I guess

**Comment by jwijenbergh** [comment]
which mitmproxy version is this? I am on 10.3.0

**Comment by Derkades** [comment]
I am using version 10.3.1, I will try 10.3.0 just in case

**Comment by jwijenbergh** [comment]
Maybe python is still taking common from the global python path? Try to add some logging to proxyguard to see if the changes are being picked up in the first place

**Comment by Derkades** [comment]
Yes, coincidentally that's exactly what I tried and indeed it fixed the issue! Now that I come to report back I see you have suggested the same

**Comment by jwijenbergh** [comment]
Nice! If you have any other questions let me know.
