### ISSUE TITLE
No succesful connection after OS upgrade to Ubuntu 24.04 noble

### ISSUE THREAD

**Issue by ottojwittner** [eduvpn/python-eduvpn-client#607]
# Installation

Issue occure after OS upgrade to Ubuntu 24.04. Old eduvpn-client has been purged and new (v4) client installed following instructions from https://docs.eduvpn.org/client/linux/installation.html#ubuntu-2404

# Version

eduVPN GUI version 4.4.0
eduvpn-common version 2.1.0

# Check if your issue is in the known issues list
Not among known issues

# OS/Distribution
Ubuntu 24.04

# Logs

## Do you have a problem while adding before connecting?
No. Adding a connection and authorizing seems to work.

## Do you have a problem during or after connecting?
Yes, connections never succeed.  Logs attached.

[eduvpn-gui-d.log](https://github.com/user-attachments/files/16994459/eduvpn-gui-d.log)
[journalctl-u-NetworkManager.log](https://github.com/user-attachments/files/16994460/journalctl-u-NetworkManager.log)
[config-eduvpn-log.log](https://github.com/user-attachments/files/16994461/config-eduvpn-log.log)

**Comment by jwijenbergh** [comment]
What are your contents of `/etc/apt/sources.list.d/eduvpn-v4.list`?

**Comment by jwijenbergh** [comment]
Can you try to manually import a configuration into networkmanager by going to the base URL of your server in the browser to download a VPN configuration (base URL can be found here: https://disco.eduvpn.org/v2/server_list.json)

And then for wireguard running:

`nmcli con import type wireguard file filename.conf`

`nmcli con import type openvpn file filename.ovpn`

And then activating the VPN if it hasn't yet with `nmcli con up conname`

**Comment by jwijenbergh** [comment]
Please let me know if this is still an issue
