### ISSUE TITLE
eduvpn-cli with CLI only VM

### ISSUE THREAD

**Issue by alexbarchiesi** [eduvpn/python-eduvpn-client#608]
# Installation

I installed following the docs on ubuntu 22 

# Version

eduVPN CLI version: 4.4.0 with eduvpn-common version: 2.1.0

# OS/Distribution

ubuntu 22

Hi I usually use the gui successfully at my institute GARR. I'm trying the cli client on a VM ubuntu 22 (deployed on our cloud O~S). 
I'm having difficulties in connecting 
Here are the steps I follow:
`eduvpn-cli interactive`
`[eduVPN]: connect`
`Please select a server number or enter a search query: garr`
`Input is not a number: garr`
`Please select a server number: 1`

Then I installed lynx as a cli browser to complete the auth process and this opens the following link: 
`Document: https://sso.dir.garr.it/auth/realms/GARR/protocol/openid-connect/auth?response_type=code&scope=openid&client_id=eduvpn-preprod&state=ur5V0RJJlgK
rNXlVD5ctpD2TT8c&redirect_uri=https%3A%2F%2Fpreprod.eduvpn.infra.garr.it%2Fvpn-user-portal%2Fredirect_uri&nonce=zedIO9zwnhsI7WGAsZmEs3163NYgmjSgBghVtgbd0hE`
asking for ` Username or email`
and I get a 404    Cookie not found. Please make sure cookies are enabled in your browser.

Is there any faq related to the use of cli client or any suggestion that you can provide to workaround this auth step?

The use case is related to a provisioning of a kubeflow cluster with jupyter notebooks as a service. 

Thanks in advance  Alex

**Comment by jwijenbergh** [comment]
In the case you want to use the client headless (meaning no display server), the best option is to go to the server in your browser, download a configuration and upload it to the VM. and then use openvpn/wireguard manually. In the future we might support then importing this configuration in the client

**Comment by alexbarchiesi** [comment]
Thanks that was my guess.
