### ISSUE TITLE
Ubuntu 24.04 NetworkManager issues

### ISSUE THREAD

**Issue by jwijenbergh** [eduvpn/python-eduvpn-client#609]
There has been quite a lot of reports for NetworkManager crashing on Ubuntu 24.04. We're currently not sure if this is a client issue but as NetworkManager is *crashing* it does not make sense to only be an issue of this client.

I currently can not reproduce this issue in a VM. So it's tricky to figure out what is wrong.

The issues that have been reported:

- https://github.com/eduvpn/python-eduvpn-client/issues/607
- https://github.com/eduvpn/eduvpn-common/issues/61

# Use the correct version

Make sure you are using the correct version of the client. For Ubuntu 24.04, the install instructions are the following:

https://docs.eduvpn.org/client/linux/installation.html#ubuntu-2404

If you're having issues please post the output of `/etc/apt/sources.list.d/eduvpn-v4.list`

# Run updates

Maybe this has already been fixed in the Ubuntu 24.04 packaging, make sure your system is fully up to date and rebooted by running:

```
sudo apt update
sudo apt upgrade
```

and then rebooting your machine.

# Try manually importing a configuration

If NetworkManager is still crashing, please try to manually import a WireGuard or OpenVPN config and report here that this step does work:

- Go to the base URL of your server in the browser: You can find the base URL here: https://disco.eduvpn.org/v2/ by searching for your server. Or in the case you're testing a custom server, you should already know the URL.
- If WireGuard: `nmcli con import type wireguard file pathtowg.conf`
- If OpenVPN: `nmcli con import type openvpn file pathtoopenvpn.ovpn`
- Then make sure the VPN is up with `nmcli con up nameofvpnprofile`

# Possible upstream issues
- https://bugs.launchpad.net/ubuntu/+source/network-manager/+bug/2080489

**Comment by KajWiik** [comment]
Yes, I just updated and rebooted, no change. I also tried with wireless and wired connections, no effect. Upgrade of the working computer did have no effect, eduvpn is working there fine.

**Comment by KajWiik** [comment]
Do you have any further instructions how I could find our wireguard setup?

**Comment by jwijenbergh** [comment]
So what you can do is go to the URL manually https://eduvpn.utu.fi. you say you do not see any wireguard configs. Do you see OpenVPN ones? Try to manually import these with networkmanager:

WireGuard:
```
nmcli con import type wireguard file file.conf
```

OpenVPN
```
nmcli con import type openvpn file file.ovpn
```

**Comment by jwijenbergh** [comment]
Oh right okay. What is the contents of ```
/etc/apt/sources.list.d/eduvpn-v4.list
```?

**Comment by KajWiik** [comment]
```
deb [arch=amd64 signed-by=/usr/share/keyrings/eduvpn-v4.gpg] https://app.eduvpn.org/linux/v4/deb/ noble main
```

**Comment by jwijenbergh** [comment]
> ```
> deb [arch=amd64 signed-by=/usr/share/keyrings/eduvpn-v4.gpg] https://app.eduvpn.org/linux/v4/deb/ noble main
> ```

Sorry I removed my comment as I saw you already mentioned it. 

In journalctl -u NetworkManager or dmesg do you see indeed that NM is crashing when you try to connect?

**Comment by jwijenbergh** [comment]
I'm going to close this as no reports any more. If there is an issue still, please comment here so I can re-open
