### ISSUE TITLE
EDUVPN Problems with connections

### ISSUE THREAD

**Issue by Network-Joe** [eduvpn/python-eduvpn-client#610]
Hello Support,

many of our users are complaining that they can connect via VPN but can't do anything (surf, access our service etc.). It seems that the traffic is blocked, but when you reconnect it works again. The error occurs every 2 days and you have to reconnect 5-20 times to get it working again.
Sometimes it also connects, but has no connection, this is only shown by the fact that it stops at 1.5kB when downloading and 50kB when uploading.

Error message:

System.Exception: Failed to obtain a VPN configuration for server: 'https://eduvpn.xx-xxx.de/'. The cause of the error is: Timeout reached contacting URL: 'https://eduvpn.xx-xxx.de/vpn-user-portal/api/v3/info'.with eduVPN.Engine.GetConfig(Cookie cookie, ServerType type, String id, Boolean tcp, Boolean startup)
with eduVPN.ViewModels.Windows.ConnectWizard.<>c__DisplayClass69_0.<Connect>b__0()
for System.Threading.Tasks.Task`1.InnerInvoke()
for System.Threading.Tasks.Task.Execute()
--- End of stack monitoring from the previous location where the exception was raised ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
with System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
for eduVPN.ViewModels.Windows.ConnectWizard.<Connect>d__69.MoveNext()
--- End of batch monitoring from the previous location where the exception was raised ---
for System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
with System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
with System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

THX

**Comment by jwijenbergh** [comment]
This is about the windows client and not the linux client?

**Comment by Network-Joe** [comment]
> This is about the windows client and not the linux client?

Yes Windows Clients.

**Comment by jwijenbergh** [comment]
does this only happen on windows or also macos or e.g. linux?

**Comment by Network-Joe** [comment]
i have tickets at the moment with windows.

**Comment by jwijenbergh** [comment]
Got it. This is the linux client repo, for windows issues see https://github.com/Amebis/eduVPN/issues

**Comment by jwijenbergh** [comment]
I have reported the issue for you: https://github.com/Amebis/eduVPN/issues/252
