### ISSUE TITLE
Allow downloading profile

### ISSUE THREAD

**Issue by b10n** [eduvpn/python-eduvpn-client#614]
It would be nice if users that don't run NetworkManager could still use the application to download a OpenVPN or WireGuard profile.

**Comment by jwijenbergh** [comment]
There was some work regarding this, but I think that it would make a lot of sense if the client also works completely headless. E.g. without OAuth (or headless OAuth)

**Comment by jwijenbergh** [comment]
This repository was moved to Codeberg: https://codeberg.org/eduVPN/linux-app/issues/614
