### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by fkooman** [eduvpn/python-eduvpn-client#86]
Debian 9 package.
![screenshot from 2017-10-05 09-55-33](https://user-images.githubusercontent.com/616885/31214325-66d28c62-a9b3-11e7-89fc-49e53875897a.png)

**Comment by gijzelaerr** [comment]
is this a new configuration or an old one?

**Comment by gijzelaerr** [comment]
Ah I see now, this is tested but skipped on travis since no dbus daemon is running.

**Comment by gijzelaerr** [comment]
solved, also extended the test suite so it covers most of the UI flow and it doesn't depend on dbus anymore.
