### ISSUE TITLE
comp-lzo=SHA256

### ISSUE THREAD

**Issue by efef** [eduvpn/python-eduvpn-client#89]
The VPN config file in the network manager config directory contains:

comp-lzo=SHA256

Is this a parse error? Just think "comp-lzo" is enough

**Comment by gijzelaerr** [comment]
what do you mean with 'network manage config directory'? The network manager menu?

**Comment by efef** [comment]
config file in this directory /etc/NetworkManager/system-connections

**Comment by gijzelaerr** [comment]
yes, this was a bug in the parser, it is fixed in the master branch now.
