### ISSUE TITLE
Ubuntu 17.10 > no protocol specified

### ISSUE THREAD

**Issue by mkoelewijn** [eduvpn/python-eduvpn-client#93]
With a clean installation of 17.10 i try to run eduVPN:

<img width="600" alt="screen shot 2017-10-23 at 23 23 37" src="https://user-images.githubusercontent.com/26085443/31914871-b8fa57de-b84c-11e7-9ca4-3d36e0b22199.png">

Syslog:

<img width="961" alt="screen shot 2017-10-23 at 23 46 31" src="https://user-images.githubusercontent.com/26085443/31914882-c64084ae-b84c-11e7-88b0-d9eddc457eb5.png">

**Comment by gijzelaerr** [comment]
I had a similar issue when I tried to #92 with a headless system, but with `network-manager` installed. Is that the case here also?

**Comment by mkoelewijn** [comment]
I've got networkmanager 1.8.4-1ubuntu3 installed. The system is a VM i operate local with VMware Fusion.

**Comment by gijzelaerr** [comment]
but do you have the desktop packages (`ubuntu-desktop`) installed and running?

**Comment by mkoelewijn** [comment]
<img width="1920" alt="screen shot 2017-10-24 at 16 39 17" src="https://user-images.githubusercontent.com/26085443/31949554-e78c97c8-b8d9-11e7-811c-c08811c523ad.png">

**Comment by gijzelaerr** [comment]
why do you run it as root? We don't support that (yet): https://github.com/eduvpn/python-eduvpn-client/issues/78

**Comment by mkoelewijn** [comment]
Because i like to be root xD. Alright, works when run as a user.
