### ISSUE TITLE
OAuth client ID

### ISSUE THREAD

**Issue by fkooman** [eduvpn/python-eduvpn-client#95]
The current `client_id` is `org.eduvpn.app`. Please start using `org.eduvpn.app.linux`. Everything else related to OAuth stays the same.

**Comment by gijzelaerr** [comment]
is this something that needs to be fixed ASAP or can it wait to the next bug fix sprint?

**Comment by fkooman** [comment]
Oh sorry, yeah it can wait. The old registration is still there for the time being.
